#!/usr/bin/env python3
"""
generate_bindings.py

Generates Python dataclass bindings from a bindings_graph.json produced by
analyze_bindings.py.

Usage:
    python generate_bindings.py region_graph.json --out bitcraft_types/

Output:
    bitcraft_types/
        __init__.py         — imports everything
        claim_local_state.py
        inventory_state.py
        pocket.py
        item_stack.py
        item_type.py
        ...                 — one .py per type
"""

import json
import re
import argparse
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# SDK primitive types — these come from the STDB SDK, not from type files.
# Map TS type name -> (Python type annotation, Python default, import line or None)
# ---------------------------------------------------------------------------

SDK_TYPES = {
    'Timestamp':   ('int', '0',    None),   # micros since unix epoch
    'TimeDuration':('int', '0',    None),   # micros
    'Identity':    ('str', "''",   None),   # hex string
    'ConnectionId':('int', '0',    None),
}

# AlgebraicType method -> (Python annotation, Python default)
ALGEBRAIC_TYPE_MAP = {
    'createU8Type':    ('int',   '0'),
    'createU16Type':   ('int',   '0'),
    'createU32Type':   ('int',   '0'),
    'createU64Type':   ('int',   '0'),
    'createU128Type':  ('int',   '0'),
    'createU256Type':  ('int',   '0'),
    'createI8Type':    ('int',   '0'),
    'createI16Type':   ('int',   '0'),
    'createI32Type':   ('int',   '0'),
    'createI64Type':   ('int',   '0'),
    'createI128Type':  ('int',   '0'),
    'createI256Type':  ('int',   '0'),
    'createF32Type':   ('float', '0.0'),
    'createF64Type':   ('float', '0.0'),
    'createBoolType':  ('bool',  'False'),
    'createStringType':('str',   "''"),
    'createTimestampType': ('int', '0'),
    'createTimeDurationType': ('int', '0'),
    'createBytesType': ('bytes', "b''"),
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _snake(name: str) -> str:
    """Convert PascalCase / camelCase to snake_case."""
    s = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', name)
    s = re.sub(r'([a-z\d])([A-Z])', r'\1_\2', s)
    return s.lower()


def _module_name(type_name: str) -> str:
    """e.g. ClaimLocalState -> claim_local_state, ItemType -> item_type"""
    return _snake(type_name)


def _py_type(ts_type: str, types: dict) -> str:
    """Map a TypeScript type string to a Python type annotation."""
    ts_type = ts_type.strip().rstrip(',')

    if ts_type == 'bigint':     return 'int'
    if ts_type == 'number':     return 'int'   # default; overridden by algebraic type info
    if ts_type == 'boolean':    return 'bool'
    if ts_type == 'string':     return 'str'

    if '| undefined' in ts_type:
        inner = ts_type.replace('| undefined', '').strip()
        inner_py = _py_type(inner, types)
        return f'{inner_py} | None'

    if ts_type.endswith('[]'):
        inner = re.sub(r'^__', '', ts_type[:-2].strip())
        return f'list[{_py_type(inner, types)}]'

    ts_type = re.sub(r'^__', '', ts_type)

    if ts_type in SDK_TYPES:
        return SDK_TYPES[ts_type][0]

    if ts_type in types:
        return ts_type

    return 'object'  # unknown fallback


def _py_type_from_algebraic(algebraic_method: str) -> tuple[str, str] | None:
    """Return (py_annotation, py_default) for a createXType() method name, or None."""
    return ALGEBRAIC_TYPE_MAP.get(algebraic_method)


def _default_for(ts_type: str, algebraic_method: str | None = None) -> str:
    ts_type = ts_type.strip().rstrip(',')
    if algebraic_method and algebraic_method in ALGEBRAIC_TYPE_MAP:
        return ALGEBRAIC_TYPE_MAP[algebraic_method][1]
    if '| undefined' in ts_type:
        return 'None'
    if ts_type.endswith('[]'):
        return 'field(default_factory=list)'
    if ts_type == 'boolean':
        return 'False'
    if ts_type in ('number', 'bigint'):
        return '0'
    if ts_type == 'string':
        return "''"
    if ts_type in SDK_TYPES:
        return SDK_TYPES[ts_type][1]
    return 'None'


# ---------------------------------------------------------------------------
# Code generators
# ---------------------------------------------------------------------------

HEADER = '''\
# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
'''


def _imports_for(type_info: dict, all_types: dict) -> list[str]:
    imports = []
    for dep in type_info.get('deps', []):
        if dep in all_types:
            mod = _module_name(dep)
            imports.append(f'from .{mod} import {dep}')
    return sorted(set(imports))


def _generate_enum(type_name: str, type_info: dict) -> str:
    lines = [
        HEADER,
        'from enum import IntEnum',
        '',
        '',
        f'class {type_name}(IntEnum):',
    ]
    for i, variant in enumerate(type_info.get('variants', [])):
        lines.append(f'    {variant.upper()} = {i}')
    if not type_info.get('variants'):
        lines.append('    pass')
    lines += [
        '',
        '',
        '    @classmethod',
        f'    def from_row(cls, raw) -> \'{type_name}\':',
        '        """',
        '        Raw wire format: [variant_index, payload]',
        f'        e.g. [0, []] for {type_info["variants"][0] if type_info["variants"] else "variant0"}',
        '        """',
        '        if isinstance(raw, list):',
        '            return cls(raw[0])',
        '        if isinstance(raw, int):',
        '            return cls(raw)',
        f'        raise ValueError(f\'Cannot parse {type_name} from {{raw!r}}\')',
        '',
    ]
    return '\n'.join(lines)


# SDK types that come as dicts on the wire and need unwrapping
SDK_WIRE_UNWRAP = {
    'Timestamp':    '__timestamp_micros_since_unix_epoch__',
    'TimeDuration': '__time_duration_micros__',
    'Identity':     '__identity__',
    'ConnectionId': '__connection_id__',
}


def _field_from_row(field_name: str, index: int, ts_type: str, all_types: dict) -> str:
    ts_type   = ts_type.strip().rstrip(',')
    snake_key = _snake(field_name)
    # Use .get() with sensible defaults so missing fields (e.g. padding fields
    # that STDB omits from the wire format) don't raise KeyError
    base      = f'(raw.get({repr(snake_key)}) if isinstance(raw, dict) else raw[{index}])'

    # Option<T>
    if '| undefined' in ts_type:
        inner_ts = re.sub(r'^__', '', ts_type.replace('| undefined', '').strip())
        if inner_ts in SDK_WIRE_UNWRAP:
            key          = SDK_WIRE_UNWRAP[inner_ts]
            inner_from   = f'_v[1][{repr(key)}] if isinstance(_v[1], dict) else _v[1]'
        elif inner_ts in all_types:
            inner_from = f'{inner_ts}.from_row(_v[1])'
        else:
            inner_from = '_v[1]'
        return (
            f'(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) '
            f'else ({inner_from}))({base})'
        )

    # Array
    if ts_type.endswith('[]'):
        inner_ts = re.sub(r'^__', '', ts_type[:-2].strip())
        if inner_ts in all_types:
            item_expr = f'{inner_ts}.from_row(_item)'
        else:
            item_expr = '_item'
        return f'[{item_expr} for _item in ({base} or [])]'

    ts_clean = re.sub(r'^__', '', ts_type)

    # SDK types that come as dicts on the wire — unwrap them
    if ts_clean in SDK_WIRE_UNWRAP:
        key = SDK_WIRE_UNWRAP[ts_clean]
        return f'({base}[{repr(key)}] if isinstance({base}, dict) else {base})'

    # Known type
    if ts_clean in all_types:
        return f'{ts_clean}.from_row({base})'

    # Primitive
    return base


def _generate_dataclass(type_name: str, type_info: dict, all_types: dict) -> str:
    fields    = type_info.get('fields', [])
    ts_fields = type_info.get('ts_fields', {})
    # algebraic_types maps camelCase field name -> createXType method name
    # (parsed by analyze_bindings from ProductTypeElement list)
    algebraic = type_info.get('algebraic_types', {})

    import_lines = _imports_for(type_info, all_types)

    lines = [HEADER]
    if import_lines:
        lines += import_lines
        lines.append('')
    lines += ['', '', '@dataclass', f'class {type_name}:']

    if not fields:
        lines.append('    pass')
    else:
        for f in fields:
            ts_t  = ts_fields.get(f, 'number')
            alg   = algebraic.get(f)            # e.g. 'createF32Type'
            snake = _snake(f)

            # Prefer algebraic type info for precise annotation + default
            if alg and alg in ALGEBRAIC_TYPE_MAP:
                py_t, default = ALGEBRAIC_TYPE_MAP[alg]
                lines.append(f'    {snake}: {py_t} = {default}')
            elif '| undefined' in ts_t or ts_t.endswith('[]'):
                default = _default_for(ts_t)
                py_t    = _py_type(ts_t, all_types)
                if 'factory' in default:
                    lines.append(f'    {snake}: list = {default}')
                else:
                    lines.append(f'    {snake}: {py_t} = {default}')
            elif ts_t == 'boolean':
                lines.append(f'    {snake}: bool = False')
            elif ts_t == 'bigint':
                lines.append(f'    {snake}: int = 0')
            elif ts_t == 'string':
                lines.append(f'    {snake}: str = \'\'')
            else:
                py_t = _py_type(ts_t, all_types)
                lines.append(f'    {snake}: {py_t} = 0')

    lines += [
        '',
        '    @classmethod',
        f'    def from_row(cls, raw) -> \'{type_name}\':',
        '        if raw is None:',
        '            return cls()',
    ]

    if fields:
        lines.append('        return cls(')
        for i, f in enumerate(fields):
            ts_t  = ts_fields.get(f, 'number')
            snake = _snake(f)
            expr  = _field_from_row(f, i, ts_t, all_types)
            comma = ',' if i < len(fields) - 1 else ''
            lines.append(f'            {snake}={expr}{comma}')
        lines.append('        )')
    else:
        lines.append('        return cls()')

    lines.append('')
    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def _generate_package(graph_path: Path, out_dir: Path) -> tuple[list, list]:
    """Generate all type files for one graph into out_dir. Returns (generated, errors)."""
    with open(graph_path) as f:
        graph = json.load(f)

    all_types = graph['types']
    topo      = graph['summary']['topo_order']
    out_dir.mkdir(parents=True, exist_ok=True)

    generated = []
    errors    = []

    for type_name in topo:
        info = all_types.get(type_name)
        if not info:
            continue
        module_file = out_dir / f'{_module_name(type_name)}.py'
        try:
            if info['is_sum']:
                code = _generate_enum(type_name, info)
            else:
                code = _generate_dataclass(type_name, info, all_types)
            module_file.write_text(code, encoding='utf-8')
            generated.append(type_name)
        except Exception as e:
            errors.append((type_name, str(e)))
            print(f'  ERROR generating {type_name}: {e}')

    # Package __init__.py
    init_lines = [
        '# AUTO-GENERATED — do not edit manually.',
        'from __future__ import annotations',
        '',
    ]
    for type_name in topo:
        if type_name in all_types:
            mod = _module_name(type_name)
            init_lines.append(f'from .{mod} import {type_name}')
    init_lines.append('')
    (out_dir / '__init__.py').write_text('\n'.join(init_lines), encoding='utf-8')

    return generated, errors


def main():
    parser = argparse.ArgumentParser(
        description='Generate Python bindings from bindings graph(s).',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''\
Examples:
  # Single module
  python generate_bindings.py --region-graph region_graph.json --out bitcraft_types

  # Both modules (generates region/ and global_/ subpackages)
  python generate_bindings.py \\
      --region-graph region_graph.json \\
      --global-graph global_graph.json \\
      --out D:\\Dev\\Bitcraft_Projects\\Bindings\\bitcraft_types
''')
    parser.add_argument('--region-graph', metavar='FILE', help='Path to region graph JSON')
    parser.add_argument('--global-graph', metavar='FILE', help='Path to global graph JSON')
    parser.add_argument('--out', default='bitcraft_types', help='Output root directory')
    args = parser.parse_args()

    if not args.region_graph and not args.global_graph:
        print('ERROR: Specify at least one of --region-graph or --global-graph')
        sys.exit(1)

    root = Path(args.out)
    root.mkdir(parents=True, exist_ok=True)

    all_generated = {}  # module -> [type_names]
    all_errors    = {}

    if args.region_graph:
        p = Path(args.region_graph)
        if not p.exists():
            print(f'ERROR: {p} not found'); sys.exit(1)
        print(f'Generating region package...')
        gen, err = _generate_package(p, root / 'region')
        all_generated['region'] = gen
        all_errors['region']    = err
        print(f'  {len(gen)} types generated, {len(err)} errors.')

    if args.global_graph:
        p = Path(args.global_graph)
        if not p.exists():
            print(f'ERROR: {p} not found'); sys.exit(1)
        print(f'Generating global package...')
        gen, err = _generate_package(p, root / 'global_')
        all_generated['global_'] = gen
        all_errors['global_']    = err
        print(f'  {len(gen)} types generated, {len(err)} errors.')

    # Top-level __init__.py that re-exports from both subpackages
    top_init = [
        '# AUTO-GENERATED — imports from region and/or global subpackages.',
        'from __future__ import annotations',
        '',
    ]
    if 'region' in all_generated:
        top_init.append('from .region import *  # noqa: F401, F403')
    if 'global_' in all_generated:
        top_init.append('from .global_ import *  # noqa: F401, F403')
    top_init.append('')
    (root / '__init__.py').write_text('\n'.join(top_init), encoding='utf-8')

    print(f'\nDone. Output: {root}')
    for mod, errors in all_errors.items():
        if errors:
            print(f'  {mod} errors:')
            for name, err in errors:
                print(f'    {name}: {err}')

    if not any(all_errors.values()):
        print('  No errors.')


if __name__ == '__main__':
    main()
