# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class AbilityType(IntEnum):
    _UNSUPPORTED = 0
    EAT = 1
    COMBATACTION = 2
    AUTOATTACK = 3
    CUSTOM = 4
    PROSPECTING = 5
    EQUIP = 6
    DEPLOYABLEDEPLOY = 7
    ADDTOTOOLBELT = 8
    DEPLOYABLETOGGLE = 9
    EMOTE = 10
    EQUIPPRESET = 11


    @classmethod
    def from_row(cls, raw) -> 'AbilityType':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for _Unsupported
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse AbilityType from {raw!r}')
