# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .buff_effect import BuffEffect



@dataclass
class AbilityCustomDesc:
    id: int = 0
    ability_name: str = ''
    stamina_cost: int = 0
    health_cost: int = 0
    cast_time: float = 0.0
    range: float = 0.0
    friendly: bool = False
    radius: float = 0.0
    buffs: list = field(default_factory=list)
    buff_toggle: bool = False
    damage: int = 0
    threat_value: float = 0.0
    cooldown: float = 0.0
    global_cooldown: float = 0.0
    linked_ability_buff_desc_id: int = 0
    animation: str = ''
    icon_path: str = ''

    @classmethod
    def from_row(cls, raw) -> 'AbilityCustomDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            ability_name=(raw.get('ability_name') if isinstance(raw, dict) else raw[1]),
            stamina_cost=(raw.get('stamina_cost') if isinstance(raw, dict) else raw[2]),
            health_cost=(raw.get('health_cost') if isinstance(raw, dict) else raw[3]),
            cast_time=(raw.get('cast_time') if isinstance(raw, dict) else raw[4]),
            range=(raw.get('range') if isinstance(raw, dict) else raw[5]),
            friendly=(raw.get('friendly') if isinstance(raw, dict) else raw[6]),
            radius=(raw.get('radius') if isinstance(raw, dict) else raw[7]),
            buffs=[BuffEffect.from_row(_item) for _item in ((raw.get('buffs') if isinstance(raw, dict) else raw[8]) or [])],
            buff_toggle=(raw.get('buff_toggle') if isinstance(raw, dict) else raw[9]),
            damage=(raw.get('damage') if isinstance(raw, dict) else raw[10]),
            threat_value=(raw.get('threat_value') if isinstance(raw, dict) else raw[11]),
            cooldown=(raw.get('cooldown') if isinstance(raw, dict) else raw[12]),
            global_cooldown=(raw.get('global_cooldown') if isinstance(raw, dict) else raw[13]),
            linked_ability_buff_desc_id=(raw.get('linked_ability_buff_desc_id') if isinstance(raw, dict) else raw[14]),
            animation=(raw.get('animation') if isinstance(raw, dict) else raw[15]),
            icon_path=(raw.get('icon_path') if isinstance(raw, dict) else raw[16])
        )
