# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .active_buff import ActiveBuff



@dataclass
class ActiveBuffState:
    entity_id: int = 0
    active_buffs: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'ActiveBuffState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            active_buffs=[ActiveBuff.from_row(_item) for _item in ((raw.get('active_buffs') if isinstance(raw, dict) else raw[1]) or [])]
        )
