# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ActionCooldown:
    timestamp: int = 0
    cooldown: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'ActionCooldown':
        if raw is None:
            return cls()
        return cls(
            timestamp=(raw.get('timestamp') if isinstance(raw, dict) else raw[0]),
            cooldown=(raw.get('cooldown') if isinstance(raw, dict) else raw[1])
        )
