# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ActiveConnectionState:
    entity_id: int = 0
    connection_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ActiveConnectionState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            connection_id=((raw.get('connection_id') if isinstance(raw, dict) else raw[1])['__connection_id__'] if isinstance((raw.get('connection_id') if isinstance(raw, dict) else raw[1]), dict) else ((raw.get('connection_id') if isinstance(raw, dict) else raw[1])[0] if isinstance((raw.get('connection_id') if isinstance(raw, dict) else raw[1]), list) else (raw.get('connection_id') if isinstance(raw, dict) else raw[1])))
        )
