# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class BiomeDesc:
    biome_type: int = 0
    name: str = ''
    description: str = ''
    hazard_level: str = ''
    icon_address: str = ''
    disallow_player_build: bool = False

    @classmethod
    def from_row(cls, raw) -> 'BiomeDesc':
        if raw is None:
            return cls()
        return cls(
            biome_type=(raw.get('biome_type') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            description=(raw.get('description') if isinstance(raw, dict) else raw[2]),
            hazard_level=(raw.get('hazard_level') if isinstance(raw, dict) else raw[3]),
            icon_address=(raw.get('icon_address') if isinstance(raw, dict) else raw[4]),
            disallow_player_build=(raw.get('disallow_player_build') if isinstance(raw, dict) else raw[5])
        )
