# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class BlockedPlayerState:
    owner_entity_id: int = 0
    blocked_entity_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'BlockedPlayerState':
        if raw is None:
            return cls()
        return cls(
            owner_entity_id=(raw.get('owner_entity_id') if isinstance(raw, dict) else raw[0]),
            blocked_entity_id=(raw.get('blocked_entity_id') if isinstance(raw, dict) else raw[1])
        )
