# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class BuffEffect:
    buff_id: int = 0
    duration: object | None = None

    @classmethod
    def from_row(cls, raw) -> 'BuffEffect':
        if raw is None:
            return cls()
        return cls(
            buff_id=(raw.get('buff_id') if isinstance(raw, dict) else raw[0]),
            duration=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]))((raw.get('duration') if isinstance(raw, dict) else raw[1]))
        )
