# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .building_function import BuildingFunction
from .building_interaction_level import BuildingInteractionLevel
from .footprint_tile import FootprintTile



@dataclass
class BuildingDesc:
    id: int = 0
    functions: list = field(default_factory=list)
    name: str = ''
    description: str = ''
    rested_buff_duration: int = 0
    light_radius: int = 0
    model_asset_name: str = ''
    icon_asset_name: str = ''
    unenterable: bool = False
    wilderness: bool = False
    footprint: list = field(default_factory=list)
    max_health: int = 0
    ignore_damage: bool = False
    defense_level: int = 0
    decay: float = 0.0
    maintenance: float = 0.0
    build_permission: BuildingInteractionLevel = 0
    interact_permission: BuildingInteractionLevel = 0
    has_action: bool = False
    show_in_compendium: bool = False
    is_ruins: bool = False
    not_deconstructible: bool = False
    destroy_on_unclaim: bool = False

    @classmethod
    def from_row(cls, raw) -> 'BuildingDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            functions=[BuildingFunction.from_row(_item) for _item in ((raw.get('functions') if isinstance(raw, dict) else raw[1]) or [])],
            name=(raw.get('name') if isinstance(raw, dict) else raw[2]),
            description=(raw.get('description') if isinstance(raw, dict) else raw[3]),
            rested_buff_duration=(raw.get('rested_buff_duration') if isinstance(raw, dict) else raw[4]),
            light_radius=(raw.get('light_radius') if isinstance(raw, dict) else raw[5]),
            model_asset_name=(raw.get('model_asset_name') if isinstance(raw, dict) else raw[6]),
            icon_asset_name=(raw.get('icon_asset_name') if isinstance(raw, dict) else raw[7]),
            unenterable=(raw.get('unenterable') if isinstance(raw, dict) else raw[8]),
            wilderness=(raw.get('wilderness') if isinstance(raw, dict) else raw[9]),
            footprint=[FootprintTile.from_row(_item) for _item in ((raw.get('footprint') if isinstance(raw, dict) else raw[10]) or [])],
            max_health=(raw.get('max_health') if isinstance(raw, dict) else raw[11]),
            ignore_damage=(raw.get('ignore_damage') if isinstance(raw, dict) else raw[12]),
            defense_level=(raw.get('defense_level') if isinstance(raw, dict) else raw[13]),
            decay=(raw.get('decay') if isinstance(raw, dict) else raw[14]),
            maintenance=(raw.get('maintenance') if isinstance(raw, dict) else raw[15]),
            build_permission=BuildingInteractionLevel.from_row((raw.get('build_permission') if isinstance(raw, dict) else raw[16])),
            interact_permission=BuildingInteractionLevel.from_row((raw.get('interact_permission') if isinstance(raw, dict) else raw[17])),
            has_action=(raw.get('has_action') if isinstance(raw, dict) else raw[18]),
            show_in_compendium=(raw.get('show_in_compendium') if isinstance(raw, dict) else raw[19]),
            is_ruins=(raw.get('is_ruins') if isinstance(raw, dict) else raw[20]),
            not_deconstructible=(raw.get('not_deconstructible') if isinstance(raw, dict) else raw[21]),
            destroy_on_unclaim=(raw.get('destroy_on_unclaim') if isinstance(raw, dict) else raw[22])
        )
