# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class BuildingSpawnType(IntEnum):
    TRAVELERCAMP = 0
    CHEST = 1
    BUILDING = 2
    RESOURCE = 3
    STATIONARYNPC = 4
    PAVING = 5
    ENEMY = 6


    @classmethod
    def from_row(cls, raw) -> 'BuildingSpawnType':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for TravelerCamp
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse BuildingSpawnType from {raw!r}')
