# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class BuildingFunctionTypeMappingDesc:
    type_id: int = 0
    desc_ids: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'BuildingFunctionTypeMappingDesc':
        if raw is None:
            return cls()
        return cls(
            type_id=(raw.get('type_id') if isinstance(raw, dict) else raw[0]),
            desc_ids=[_item for _item in ((raw.get('desc_ids') if isinstance(raw, dict) else raw[1]) or [])]
        )
