# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .building_category import BuildingCategory



@dataclass
class BuildingTypeDesc:
    id: int = 0
    name: str = ''
    category: BuildingCategory = 0
    actions: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'BuildingTypeDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            category=BuildingCategory.from_row((raw.get('category') if isinstance(raw, dict) else raw[2])),
            actions=[_item for _item in ((raw.get('actions') if isinstance(raw, dict) else raw[3]) or [])]
        )
