# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class BuildingPortalDesc:
    id: int = 0
    name: str = ''
    building_id: int = 0
    allow_deployables: bool = False
    enemy_lock: bool = False
    pos_x: int = 0
    pos_z: int = 0

    @classmethod
    def from_row(cls, raw) -> 'BuildingPortalDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            building_id=(raw.get('building_id') if isinstance(raw, dict) else raw[2]),
            allow_deployables=(raw.get('allow_deployables') if isinstance(raw, dict) else raw[3]),
            enemy_lock=(raw.get('enemy_lock') if isinstance(raw, dict) else raw[4]),
            pos_x=(raw.get('pos_x') if isinstance(raw, dict) else raw[5]),
            pos_z=(raw.get('pos_z') if isinstance(raw, dict) else raw[6])
        )
