# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class BuildingRequirement:
    building_type: int = 0
    tier: int = 0

    @classmethod
    def from_row(cls, raw) -> 'BuildingRequirement':
        if raw is None:
            return cls()
        return cls(
            building_type=(raw.get('building_type') if isinstance(raw, dict) else raw[0]),
            tier=(raw.get('tier') if isinstance(raw, dict) else raw[1])
        )
