# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .rarity import Rarity



@dataclass
class CargoDesc:
    id: int = 0
    name: str = ''
    description: str = ''
    volume: int = 0
    secondary_knowledge_id: int = 0
    model_asset_name: str = ''
    icon_asset_name: str = ''
    carried_model_asset_name: str = ''
    pick_up_animation_start: str = ''
    pick_up_animation_end: str = ''
    drop_animation_start: str = ''
    drop_animation_end: str = ''
    pick_up_time: float = 0.0
    place_time: float = 0.0
    animator_state: str = ''
    movement_modifier: float = 0.0
    blocks_path: bool = False
    on_destroy_yield_cargos: list = field(default_factory=list)
    despawn_time: float = 0.0
    tier: int = 0
    tag: str = ''
    rarity: Rarity = 0
    not_pickupable: bool = False
    cannot_store_in_buildings: bool = False
    cannot_store_in_deployables: bool = False

    @classmethod
    def from_row(cls, raw) -> 'CargoDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            description=(raw.get('description') if isinstance(raw, dict) else raw[2]),
            volume=(raw.get('volume') if isinstance(raw, dict) else raw[3]),
            secondary_knowledge_id=(raw.get('secondary_knowledge_id') if isinstance(raw, dict) else raw[4]),
            model_asset_name=(raw.get('model_asset_name') if isinstance(raw, dict) else raw[5]),
            icon_asset_name=(raw.get('icon_asset_name') if isinstance(raw, dict) else raw[6]),
            carried_model_asset_name=(raw.get('carried_model_asset_name') if isinstance(raw, dict) else raw[7]),
            pick_up_animation_start=(raw.get('pick_up_animation_start') if isinstance(raw, dict) else raw[8]),
            pick_up_animation_end=(raw.get('pick_up_animation_end') if isinstance(raw, dict) else raw[9]),
            drop_animation_start=(raw.get('drop_animation_start') if isinstance(raw, dict) else raw[10]),
            drop_animation_end=(raw.get('drop_animation_end') if isinstance(raw, dict) else raw[11]),
            pick_up_time=(raw.get('pick_up_time') if isinstance(raw, dict) else raw[12]),
            place_time=(raw.get('place_time') if isinstance(raw, dict) else raw[13]),
            animator_state=(raw.get('animator_state') if isinstance(raw, dict) else raw[14]),
            movement_modifier=(raw.get('movement_modifier') if isinstance(raw, dict) else raw[15]),
            blocks_path=(raw.get('blocks_path') if isinstance(raw, dict) else raw[16]),
            on_destroy_yield_cargos=[_item for _item in ((raw.get('on_destroy_yield_cargos') if isinstance(raw, dict) else raw[17]) or [])],
            despawn_time=(raw.get('despawn_time') if isinstance(raw, dict) else raw[18]),
            tier=(raw.get('tier') if isinstance(raw, dict) else raw[19]),
            tag=(raw.get('tag') if isinstance(raw, dict) else raw[20]),
            rarity=Rarity.from_row((raw.get('rarity') if isinstance(raw, dict) else raw[21])),
            not_pickupable=(raw.get('not_pickupable') if isinstance(raw, dict) else raw[22]),
            cannot_store_in_buildings=(raw.get('cannot_store_in_buildings') if isinstance(raw, dict) else raw[23]),
            cannot_store_in_deployables=(raw.get('cannot_store_in_deployables') if isinstance(raw, dict) else raw[24])
        )
