# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .chat_channel_visibility import ChatChannelVisibility



@dataclass
class ChatChannelState:
    entity_id: int = 0
    name: str = ''
    lowercase_name: str = ''
    description: str = ''
    visibility: ChatChannelVisibility = 0

    @classmethod
    def from_row(cls, raw) -> 'ChatChannelState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            lowercase_name=(raw.get('lowercase_name') if isinstance(raw, dict) else raw[2]),
            description=(raw.get('description') if isinstance(raw, dict) else raw[3]),
            visibility=ChatChannelVisibility.from_row((raw.get('visibility') if isinstance(raw, dict) else raw[4]))
        )
