# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class ChatChannelVisibility(IntEnum):
    UNLISTED = 0
    CONTROLLED = 1
    PUBLIC = 2


    @classmethod
    def from_row(cls, raw) -> 'ChatChannelVisibility':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for Unlisted
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse ChatChannelVisibility from {raw!r}')
