# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_small_message import OffsetCoordinatesSmallMessage



@dataclass
class ClaimLocalState:
    entity_id: int = 0
    supplies: int = 0
    building_maintenance: float = 0.0
    num_tiles: int = 0
    num_tile_neighbors: int = 0
    location: OffsetCoordinatesSmallMessage | None = None
    treasury: int = 0
    xp_gained_since_last_coin_minting: int = 0
    supplies_purchase_threshold: int = 0
    supplies_purchase_price: float = 0.0
    building_description_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ClaimLocalState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            supplies=(raw.get('supplies') if isinstance(raw, dict) else raw[1]),
            building_maintenance=(raw.get('building_maintenance') if isinstance(raw, dict) else raw[2]),
            num_tiles=(raw.get('num_tiles') if isinstance(raw, dict) else raw[3]),
            num_tile_neighbors=(raw.get('num_tile_neighbors') if isinstance(raw, dict) else raw[4]),
            location=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (OffsetCoordinatesSmallMessage.from_row(_v[1])))((raw.get('location') if isinstance(raw, dict) else raw[5])),
            treasury=(raw.get('treasury') if isinstance(raw, dict) else raw[6]),
            xp_gained_since_last_coin_minting=(raw.get('xp_gained_since_last_coin_minting') if isinstance(raw, dict) else raw[7]),
            supplies_purchase_threshold=(raw.get('supplies_purchase_threshold') if isinstance(raw, dict) else raw[8]),
            supplies_purchase_price=(raw.get('supplies_purchase_price') if isinstance(raw, dict) else raw[9]),
            building_description_id=(raw.get('building_description_id') if isinstance(raw, dict) else raw[10])
        )
