# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .buff_effect import BuffEffect
from .level_requirement import LevelRequirement



@dataclass
class CombatActionDesc:
    name: str = ''
    id: int = 0
    learned_by_player: bool = False
    range: int = 0
    max_range: float = 0.0
    auto_cast: bool = False
    weapon_type_requirements: list = field(default_factory=list)
    lead_in_time: float = 0.0
    inaction_time: float = 0.0
    can_move_during_lead_in: bool = False
    cooldown: float = 0.0
    global_cooldown: float = 0.0
    ignore_global_cooldown: bool = False
    strength_multiplier: float = 0.0
    accuracy_multiplier: float = 0.0
    stamina_use: float = 0.0
    weapon_durability_lost: int = 0
    self_buffs: list = field(default_factory=list)
    target_buffs: list = field(default_factory=list)
    level_requirement: LevelRequirement | None = None
    icon_asset_name: str = ''
    player_animation_id: int = 0
    npc_animation_name: str = ''
    hit_vfx: str = ''
    projectile_speed: float = 0.0
    projectile_vfx: str = ''
    description: str = ''
    self_threat_against_buildings: float = 0.0
    self_threat_against_enemies: float = 0.0
    base_threat: float = 0.0
    threat_per_damage: float = 0.0
    is_self_targeting: bool = False
    is_taunt_action: bool = False

    @classmethod
    def from_row(cls, raw) -> 'CombatActionDesc':
        if raw is None:
            return cls()
        return cls(
            name=(raw.get('name') if isinstance(raw, dict) else raw[0]),
            id=(raw.get('id') if isinstance(raw, dict) else raw[1]),
            learned_by_player=(raw.get('learned_by_player') if isinstance(raw, dict) else raw[2]),
            range=(raw.get('range') if isinstance(raw, dict) else raw[3]),
            max_range=(raw.get('max_range') if isinstance(raw, dict) else raw[4]),
            auto_cast=(raw.get('auto_cast') if isinstance(raw, dict) else raw[5]),
            weapon_type_requirements=[_item for _item in ((raw.get('weapon_type_requirements') if isinstance(raw, dict) else raw[6]) or [])],
            lead_in_time=(raw.get('lead_in_time') if isinstance(raw, dict) else raw[7]),
            inaction_time=(raw.get('inaction_time') if isinstance(raw, dict) else raw[8]),
            can_move_during_lead_in=(raw.get('can_move_during_lead_in') if isinstance(raw, dict) else raw[9]),
            cooldown=(raw.get('cooldown') if isinstance(raw, dict) else raw[10]),
            global_cooldown=(raw.get('global_cooldown') if isinstance(raw, dict) else raw[11]),
            ignore_global_cooldown=(raw.get('ignore_global_cooldown') if isinstance(raw, dict) else raw[12]),
            strength_multiplier=(raw.get('strength_multiplier') if isinstance(raw, dict) else raw[13]),
            accuracy_multiplier=(raw.get('accuracy_multiplier') if isinstance(raw, dict) else raw[14]),
            stamina_use=(raw.get('stamina_use') if isinstance(raw, dict) else raw[15]),
            weapon_durability_lost=(raw.get('weapon_durability_lost') if isinstance(raw, dict) else raw[16]),
            self_buffs=[BuffEffect.from_row(_item) for _item in ((raw.get('self_buffs') if isinstance(raw, dict) else raw[17]) or [])],
            target_buffs=[BuffEffect.from_row(_item) for _item in ((raw.get('target_buffs') if isinstance(raw, dict) else raw[18]) or [])],
            level_requirement=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (LevelRequirement.from_row(_v[1])))((raw.get('level_requirement') if isinstance(raw, dict) else raw[19])),
            icon_asset_name=(raw.get('icon_asset_name') if isinstance(raw, dict) else raw[20]),
            player_animation_id=(raw.get('player_animation_id') if isinstance(raw, dict) else raw[21]),
            npc_animation_name=(raw.get('npc_animation_name') if isinstance(raw, dict) else raw[22]),
            hit_vfx=(raw.get('hit_vfx') if isinstance(raw, dict) else raw[23]),
            projectile_speed=(raw.get('projectile_speed') if isinstance(raw, dict) else raw[24]),
            projectile_vfx=(raw.get('projectile_vfx') if isinstance(raw, dict) else raw[25]),
            description=(raw.get('description') if isinstance(raw, dict) else raw[26]),
            self_threat_against_buildings=(raw.get('self_threat_against_buildings') if isinstance(raw, dict) else raw[27]),
            self_threat_against_enemies=(raw.get('self_threat_against_enemies') if isinstance(raw, dict) else raw[28]),
            base_threat=(raw.get('base_threat') if isinstance(raw, dict) else raw[29]),
            threat_per_damage=(raw.get('threat_per_damage') if isinstance(raw, dict) else raw[30]),
            is_self_targeting=(raw.get('is_self_targeting') if isinstance(raw, dict) else raw[31]),
            is_taunt_action=(raw.get('is_taunt_action') if isinstance(raw, dict) else raw[32])
        )
