# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class CombatImmunityState:
    entity_id: int = 0
    immunity_end_timestamp: int = 0
    crumb_trail_entity_id: int | None = None

    @classmethod
    def from_row(cls, raw) -> 'CombatImmunityState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            immunity_end_timestamp=((raw.get('immunity_end_timestamp') if isinstance(raw, dict) else raw[1])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('immunity_end_timestamp') if isinstance(raw, dict) else raw[1]), dict) else (raw.get('immunity_end_timestamp') if isinstance(raw, dict) else raw[1])),
            crumb_trail_entity_id=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]))((raw.get('crumb_trail_entity_id') if isinstance(raw, dict) else raw[2]))
        )
