# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ContributionLootDesc:
    id: int = 0
    enemy_type_id: int = 0
    item_list_id: int = 0
    minimum_contribution: int = 0
    weighted: bool = False

    @classmethod
    def from_row(cls, raw) -> 'ContributionLootDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            enemy_type_id=(raw.get('enemy_type_id') if isinstance(raw, dict) else raw[1]),
            item_list_id=(raw.get('item_list_id') if isinstance(raw, dict) else raw[2]),
            minimum_contribution=(raw.get('minimum_contribution') if isinstance(raw, dict) else raw[3]),
            weighted=(raw.get('weighted') if isinstance(raw, dict) else raw[4])
        )
