# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .building_requirement import BuildingRequirement
from .experience_stack_f32 import ExperienceStackF32
from .input_item_stack import InputItemStack
from .item_stack import ItemStack
from .level_requirement import LevelRequirement
from .tool_requirement import ToolRequirement



@dataclass
class CraftingRecipeDesc:
    id: int = 0
    name: str = ''
    time_requirement: float = 0.0
    stamina_requirement: float = 0.0
    tool_durability_lost: int = 0
    building_requirement: BuildingRequirement | None = None
    level_requirements: list = field(default_factory=list)
    tool_requirements: list = field(default_factory=list)
    consumed_item_stacks: list = field(default_factory=list)
    discovery_triggers: list = field(default_factory=list)
    required_claim_tech_id: int = 0
    full_discovery_score: int = 0
    experience_per_progress: list = field(default_factory=list)
    crafted_item_stacks: list = field(default_factory=list)
    actions_required: int = 0
    tool_mesh_index: int = 0
    recipe_performance_id: int = 0
    required_knowledges: list = field(default_factory=list)
    blocking_knowledges: list = field(default_factory=list)
    hide_without_required_knowledge: bool = False
    hide_with_blocking_knowledges: bool = False
    allow_use_hands: bool = False
    is_passive: bool = False
    show_in_progression: bool = False

    @classmethod
    def from_row(cls, raw) -> 'CraftingRecipeDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            time_requirement=(raw.get('time_requirement') if isinstance(raw, dict) else raw[2]),
            stamina_requirement=(raw.get('stamina_requirement') if isinstance(raw, dict) else raw[3]),
            tool_durability_lost=(raw.get('tool_durability_lost') if isinstance(raw, dict) else raw[4]),
            building_requirement=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (BuildingRequirement.from_row(_v[1])))((raw.get('building_requirement') if isinstance(raw, dict) else raw[5])),
            level_requirements=[LevelRequirement.from_row(_item) for _item in ((raw.get('level_requirements') if isinstance(raw, dict) else raw[6]) or [])],
            tool_requirements=[ToolRequirement.from_row(_item) for _item in ((raw.get('tool_requirements') if isinstance(raw, dict) else raw[7]) or [])],
            consumed_item_stacks=[InputItemStack.from_row(_item) for _item in ((raw.get('consumed_item_stacks') if isinstance(raw, dict) else raw[8]) or [])],
            discovery_triggers=[_item for _item in ((raw.get('discovery_triggers') if isinstance(raw, dict) else raw[9]) or [])],
            required_claim_tech_id=(raw.get('required_claim_tech_id') if isinstance(raw, dict) else raw[10]),
            full_discovery_score=(raw.get('full_discovery_score') if isinstance(raw, dict) else raw[11]),
            experience_per_progress=[ExperienceStackF32.from_row(_item) for _item in ((raw.get('experience_per_progress') if isinstance(raw, dict) else raw[12]) or [])],
            crafted_item_stacks=[ItemStack.from_row(_item) for _item in ((raw.get('crafted_item_stacks') if isinstance(raw, dict) else raw[13]) or [])],
            actions_required=(raw.get('actions_required') if isinstance(raw, dict) else raw[14]),
            tool_mesh_index=(raw.get('tool_mesh_index') if isinstance(raw, dict) else raw[15]),
            recipe_performance_id=(raw.get('recipe_performance_id') if isinstance(raw, dict) else raw[16]),
            required_knowledges=[_item for _item in ((raw.get('required_knowledges') if isinstance(raw, dict) else raw[17]) or [])],
            blocking_knowledges=[_item for _item in ((raw.get('blocking_knowledges') if isinstance(raw, dict) else raw[18]) or [])],
            hide_without_required_knowledge=(raw.get('hide_without_required_knowledge') if isinstance(raw, dict) else raw[19]),
            hide_with_blocking_knowledges=(raw.get('hide_with_blocking_knowledges') if isinstance(raw, dict) else raw[20]),
            allow_use_hands=(raw.get('allow_use_hands') if isinstance(raw, dict) else raw[21]),
            is_passive=(raw.get('is_passive') if isinstance(raw, dict) else raw[22]),
            show_in_progression=(raw.get('show_in_progression') if isinstance(raw, dict) else raw[23])
        )
