# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class CrumbTrailContributionSpentState:
    entity_id: int = 0
    player_entity_id: int = 0
    crumb_trail_entity_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'CrumbTrailContributionSpentState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[1]),
            crumb_trail_entity_id=(raw.get('crumb_trail_entity_id') if isinstance(raw, dict) else raw[2])
        )
