# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class DeployableState:
    entity_id: int = 0
    owner_id: int = 0
    claim_entity_id: int = 0
    direction: int = 0
    deployable_description_id: int = 0
    nickname: str = ''
    hidden: bool = False

    @classmethod
    def from_row(cls, raw) -> 'DeployableState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            owner_id=(raw.get('owner_id') if isinstance(raw, dict) else raw[1]),
            claim_entity_id=(raw.get('claim_entity_id') if isinstance(raw, dict) else raw[2]),
            direction=(raw.get('direction') if isinstance(raw, dict) else raw[3]),
            deployable_description_id=(raw.get('deployable_description_id') if isinstance(raw, dict) else raw[4]),
            nickname=(raw.get('nickname') if isinstance(raw, dict) else raw[5]),
            hidden=(raw.get('hidden') if isinstance(raw, dict) else raw[6])
        )
