# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .dimension_type import DimensionType



@dataclass
class DimensionDescriptionState:
    entity_id: int = 0
    dimension_network_entity_id: int = 0
    collapse_timestamp: int = 0
    interior_instance_id: int = 0
    dimension_position_large_x: int = 0
    dimension_position_large_z: int = 0
    dimension_size_large_x: int = 0
    dimension_size_large_z: int = 0
    dimension_id: int = 0
    dimension_type: DimensionType = 0

    @classmethod
    def from_row(cls, raw) -> 'DimensionDescriptionState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            dimension_network_entity_id=(raw.get('dimension_network_entity_id') if isinstance(raw, dict) else raw[1]),
            collapse_timestamp=(raw.get('collapse_timestamp') if isinstance(raw, dict) else raw[2]),
            interior_instance_id=(raw.get('interior_instance_id') if isinstance(raw, dict) else raw[3]),
            dimension_position_large_x=(raw.get('dimension_position_large_x') if isinstance(raw, dict) else raw[4]),
            dimension_position_large_z=(raw.get('dimension_position_large_z') if isinstance(raw, dict) else raw[5]),
            dimension_size_large_x=(raw.get('dimension_size_large_x') if isinstance(raw, dict) else raw[6]),
            dimension_size_large_z=(raw.get('dimension_size_large_z') if isinstance(raw, dict) else raw[7]),
            dimension_id=(raw.get('dimension_id') if isinstance(raw, dict) else raw[8]),
            dimension_type=DimensionType.from_row((raw.get('dimension_type') if isinstance(raw, dict) else raw[9]))
        )
