# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class DuelState:
    entity_id: int = 0
    initiator_entity_id: int = 0
    acceptor_entity_id: int = 0
    victor: object | None = None
    player_entity_ids: list = field(default_factory=list)
    out_of_range_timestamps: object = 0

    @classmethod
    def from_row(cls, raw) -> 'DuelState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            initiator_entity_id=(raw.get('initiator_entity_id') if isinstance(raw, dict) else raw[1]),
            acceptor_entity_id=(raw.get('acceptor_entity_id') if isinstance(raw, dict) else raw[2]),
            victor=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]))((raw.get('victor') if isinstance(raw, dict) else raw[3])),
            player_entity_ids=[_item for _item in ((raw.get('player_entity_ids') if isinstance(raw, dict) else raw[4]) or [])],
            out_of_range_timestamps=(raw.get('out_of_range_timestamps') if isinstance(raw, dict) else raw[5])
        )
