# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ElevatorDesc:
    building_id: int = 0
    max_cliff_height: int = 0
    speed: float = 0.0
    usable_with_deployable: bool = False
    top_platform_address: str = ''
    basket_address: str = ''
    bottom_platform_address: str = ''

    @classmethod
    def from_row(cls, raw) -> 'ElevatorDesc':
        if raw is None:
            return cls()
        return cls(
            building_id=(raw.get('building_id') if isinstance(raw, dict) else raw[0]),
            max_cliff_height=(raw.get('max_cliff_height') if isinstance(raw, dict) else raw[1]),
            speed=(raw.get('speed') if isinstance(raw, dict) else raw[2]),
            usable_with_deployable=(raw.get('usable_with_deployable') if isinstance(raw, dict) else raw[3]),
            top_platform_address=(raw.get('top_platform_address') if isinstance(raw, dict) else raw[4]),
            basket_address=(raw.get('basket_address') if isinstance(raw, dict) else raw[5]),
            bottom_platform_address=(raw.get('bottom_platform_address') if isinstance(raw, dict) else raw[6])
        )
