# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireEmblemState:
    entity_id: int = 0
    icon_id: int = 0
    shape_id: int = 0
    color1_id: int = 0
    color2_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'EmpireEmblemState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            icon_id=(raw.get('icon_id') if isinstance(raw, dict) else raw[1]),
            shape_id=(raw.get('shape_id') if isinstance(raw, dict) else raw[2]),
            color1_id=(raw.get('color1_id') if isinstance(raw, dict) else raw[3]),
            color2_id=(raw.get('color2_id') if isinstance(raw, dict) else raw[4])
        )
