# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireWithdrawItemMsg:
    player_entity_id: int = 0
    item_id: int = 0
    is_cargo: bool = False
    count: int = 0

    @classmethod
    def from_row(cls, raw) -> 'EmpireWithdrawItemMsg':
        if raw is None:
            return cls()
        return cls(
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[0]),
            item_id=(raw.get('item_id') if isinstance(raw, dict) else raw[1]),
            is_cargo=(raw.get('is_cargo') if isinstance(raw, dict) else raw[2]),
            count=(raw.get('count') if isinstance(raw, dict) else raw[3])
        )
