# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpirePlayerLogState:
    entity_id: int = 0
    empire_entity_id: int = 0
    last_viewed: int = 0

    @classmethod
    def from_row(cls, raw) -> 'EmpirePlayerLogState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            empire_entity_id=(raw.get('empire_entity_id') if isinstance(raw, dict) else raw[1]),
            last_viewed=(raw.get('last_viewed') if isinstance(raw, dict) else raw[2])
        )
