# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireIconDesc:
    id: int = 0
    icon_unicode: str = ''
    is_shape: bool = False

    @classmethod
    def from_row(cls, raw) -> 'EmpireIconDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            icon_unicode=(raw.get('icon_unicode') if isinstance(raw, dict) else raw[1]),
            is_shape=(raw.get('is_shape') if isinstance(raw, dict) else raw[2])
        )
