# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_small_message import OffsetCoordinatesSmallMessage



@dataclass
class EmpireStartSiegeMsg:
    building_coord: OffsetCoordinatesSmallMessage = 0
    player_entity_id: int = 0
    building_entity_id: int = 0
    deployable_entity_id: int = 0
    supplies: int = 0
    supply_cargo_id: int = 0
    is_depleted_watchtower: bool = False

    @classmethod
    def from_row(cls, raw) -> 'EmpireStartSiegeMsg':
        if raw is None:
            return cls()
        return cls(
            building_coord=OffsetCoordinatesSmallMessage.from_row((raw.get('building_coord') if isinstance(raw, dict) else raw[0])),
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[1]),
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[2]),
            deployable_entity_id=(raw.get('deployable_entity_id') if isinstance(raw, dict) else raw[3]),
            supplies=(raw.get('supplies') if isinstance(raw, dict) else raw[4]),
            supply_cargo_id=(raw.get('supply_cargo_id') if isinstance(raw, dict) else raw[5]),
            is_depleted_watchtower=(raw.get('is_depleted_watchtower') if isinstance(raw, dict) else raw[6])
        )
