# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireNodeSiegeState:
    entity_id: int = 0
    building_entity_id: int = 0
    empire_entity_id: int = 0
    energy: int = 0
    active: bool = False
    start_timestamp: int | None = None

    @classmethod
    def from_row(cls, raw) -> 'EmpireNodeSiegeState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[1]),
            empire_entity_id=(raw.get('empire_entity_id') if isinstance(raw, dict) else raw[2]),
            energy=(raw.get('energy') if isinstance(raw, dict) else raw[3]),
            active=(raw.get('active') if isinstance(raw, dict) else raw[4]),
            start_timestamp=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else ((_v[1]['__timestamp_micros_since_unix_epoch__'] if isinstance(_v[1], dict) else (_v[1][0] if isinstance(_v[1], list) else _v[1]))))((raw.get('start_timestamp') if isinstance(raw, dict) else raw[5]))
        )
