# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .empire_notification_type import EmpireNotificationType



@dataclass
class EmpireNotificationDesc:
    id: int = 0
    notification_type: EmpireNotificationType = 0
    priority: int = 0
    show_on_login: bool = False
    text: str = ''

    @classmethod
    def from_row(cls, raw) -> 'EmpireNotificationDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            notification_type=EmpireNotificationType.from_row((raw.get('notification_type') if isinstance(raw, dict) else raw[1])),
            priority=(raw.get('priority') if isinstance(raw, dict) else raw[2]),
            show_on_login=(raw.get('show_on_login') if isinstance(raw, dict) else raw[3]),
            text=(raw.get('text') if isinstance(raw, dict) else raw[4])
        )
