# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class EmpirePermission(IntEnum):
    SUPPLYNODE = 0
    COLLECTHEXITECAPSULE = 1
    BUILDWATCHTOWER = 2
    FLAGWATCHTOWERTOSIEGE = 3
    APROVEEMPIRESUBMISSIONS = 4
    PROMOTELESSERRANKS = 5
    CRAFTHEXITECAPSULE = 6
    COUNT = 7
    HARVESTEMPIRERESOURCES = 8
    WITHDRAWEMPIRECURRENCY = 9


    @classmethod
    def from_row(cls, raw) -> 'EmpirePermission':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for SupplyNode
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse EmpirePermission from {raw!r}')
