# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireFoundryState:
    entity_id: int = 0
    empire_entity_id: int = 0
    hexite_capsules: int = 0
    queued: int = 0
    started: int = 0

    @classmethod
    def from_row(cls, raw) -> 'EmpireFoundryState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            empire_entity_id=(raw.get('empire_entity_id') if isinstance(raw, dict) else raw[1]),
            hexite_capsules=(raw.get('hexite_capsules') if isinstance(raw, dict) else raw[2]),
            queued=(raw.get('queued') if isinstance(raw, dict) else raw[3]),
            started=((raw.get('started') if isinstance(raw, dict) else raw[4])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('started') if isinstance(raw, dict) else raw[4]), dict) else ((raw.get('started') if isinstance(raw, dict) else raw[4])[0] if isinstance((raw.get('started') if isinstance(raw, dict) else raw[4]), list) else (raw.get('started') if isinstance(raw, dict) else raw[4])))
        )
