# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireSetDirectiveMessageRequest:
    empire_entity_id: int = 0
    message: str = ''

    @classmethod
    def from_row(cls, raw) -> 'EmpireSetDirectiveMessageRequest':
        if raw is None:
            return cls()
        return cls(
            empire_entity_id=(raw.get('empire_entity_id') if isinstance(raw, dict) else raw[0]),
            message=(raw.get('message') if isinstance(raw, dict) else raw[1])
        )
