# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireDirectiveState:
    entity_id: int = 0
    directive_message: str = ''
    directive_message_timestamp: int | None = None

    @classmethod
    def from_row(cls, raw) -> 'EmpireDirectiveState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            directive_message=(raw.get('directive_message') if isinstance(raw, dict) else raw[1]),
            directive_message_timestamp=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]['__timestamp_micros_since_unix_epoch__'] if isinstance(_v[1], dict) else _v[1]))((raw.get('directive_message_timestamp') if isinstance(raw, dict) else raw[2]))
        )
