# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .empire_notification_type import EmpireNotificationType



@dataclass
class EmpireNotificationState:
    entity_id: int = 0
    empire_entity_id: int = 0
    notification_type: EmpireNotificationType = 0
    text_replacement: list = field(default_factory=list)
    timestamp: int = 0

    @classmethod
    def from_row(cls, raw) -> 'EmpireNotificationState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            empire_entity_id=(raw.get('empire_entity_id') if isinstance(raw, dict) else raw[1]),
            notification_type=EmpireNotificationType.from_row((raw.get('notification_type') if isinstance(raw, dict) else raw[2])),
            text_replacement=[_item for _item in ((raw.get('text_replacement') if isinstance(raw, dict) else raw[3]) or [])],
            timestamp=(raw.get('timestamp') if isinstance(raw, dict) else raw[4])
        )
