# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireColorDesc:
    id: int = 0
    color_argb: int = 0
    color2_argb: object | None = None

    @classmethod
    def from_row(cls, raw) -> 'EmpireColorDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            color_argb=(raw.get('color_argb') if isinstance(raw, dict) else raw[1]),
            color2_argb=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]))((raw.get('color2_argb') if isinstance(raw, dict) else raw[2]))
        )
