# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .biome import Biome
from .enemy_type import EnemyType



@dataclass
class EnemyAiParamsDesc:
    id: int = 0
    enemy_type: EnemyType = 0
    biome: Biome = 0
    avg_herd_size: int = 0
    var_herd_size: float = 0.0
    herds_per_chunk: float = 0.0
    roaming_distance: int = 0
    spawn_eagerness: float = 0.0
    time_of_day_start: float = 0.0
    time_of_day_end: float = 0.0
    spawn_frequency_minutes: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'EnemyAiParamsDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            enemy_type=EnemyType.from_row((raw.get('enemy_type') if isinstance(raw, dict) else raw[1])),
            biome=Biome.from_row((raw.get('biome') if isinstance(raw, dict) else raw[2])),
            avg_herd_size=(raw.get('avg_herd_size') if isinstance(raw, dict) else raw[3]),
            var_herd_size=(raw.get('var_herd_size') if isinstance(raw, dict) else raw[4]),
            herds_per_chunk=(raw.get('herds_per_chunk') if isinstance(raw, dict) else raw[5]),
            roaming_distance=(raw.get('roaming_distance') if isinstance(raw, dict) else raw[6]),
            spawn_eagerness=(raw.get('spawn_eagerness') if isinstance(raw, dict) else raw[7]),
            time_of_day_start=(raw.get('time_of_day_start') if isinstance(raw, dict) else raw[8]),
            time_of_day_end=(raw.get('time_of_day_end') if isinstance(raw, dict) else raw[9]),
            spawn_frequency_minutes=(raw.get('spawn_frequency_minutes') if isinstance(raw, dict) else raw[10])
        )
