# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .experience_stack_f32 import ExperienceStackF32
from .probabilistic_item_stack import ProbabilisticItemStack
from .rarity import Rarity



@dataclass
class EnemyDesc:
    enemy_type: int = 0
    name: str = ''
    pathfinding_id: int = 0
    targeting_matrix_id: int = 0
    combat_actions_ids: list = field(default_factory=list)
    description: str = ''
    min_speed: int = 0
    max_speed: int = 0
    radius: float = 0.0
    awareness_destination_threshold: float = 0.0
    min_awareness_tick_sec: float = 0.0
    max_awareness_tick_sec: float = 0.0
    max_health: int = 0
    ignore_damage: bool = False
    health_regen_quantity: float = 0.0
    armor: int = 0
    accuracy: int = 0
    evasion: int = 0
    strength: int = 0
    min_damage: int = 0
    max_damage: int = 0
    cooldown_multiplier: float = 0.0
    daytime_detect_range: int = 0
    daytime_aggro_range: int = 0
    daytime_deaggro_range: int = 0
    nighttime_detect_range: int = 0
    nighttime_aggro_range: int = 0
    nighttime_deaggro_range: int = 0
    evade_range: int = 0
    deaggro_health_threshold: float = 0.0
    attack_level: int = 0
    defense_level: int = 0
    prefab_address: str = ''
    icon_address: str = ''
    extracted_item_stacks: list = field(default_factory=list)
    experience_per_damage_dealt: list = field(default_factory=list)
    tier: int = 0
    tag: str = ''
    rarity: Rarity = 0
    huntable: bool = False

    @classmethod
    def from_row(cls, raw) -> 'EnemyDesc':
        if raw is None:
            return cls()
        return cls(
            enemy_type=(raw.get('enemy_type') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            pathfinding_id=(raw.get('pathfinding_id') if isinstance(raw, dict) else raw[2]),
            targeting_matrix_id=(raw.get('targeting_matrix_id') if isinstance(raw, dict) else raw[3]),
            combat_actions_ids=[_item for _item in ((raw.get('combat_actions_ids') if isinstance(raw, dict) else raw[4]) or [])],
            description=(raw.get('description') if isinstance(raw, dict) else raw[5]),
            min_speed=(raw.get('min_speed') if isinstance(raw, dict) else raw[6]),
            max_speed=(raw.get('max_speed') if isinstance(raw, dict) else raw[7]),
            radius=(raw.get('radius') if isinstance(raw, dict) else raw[8]),
            awareness_destination_threshold=(raw.get('awareness_destination_threshold') if isinstance(raw, dict) else raw[9]),
            min_awareness_tick_sec=(raw.get('min_awareness_tick_sec') if isinstance(raw, dict) else raw[10]),
            max_awareness_tick_sec=(raw.get('max_awareness_tick_sec') if isinstance(raw, dict) else raw[11]),
            max_health=(raw.get('max_health') if isinstance(raw, dict) else raw[12]),
            ignore_damage=(raw.get('ignore_damage') if isinstance(raw, dict) else raw[13]),
            health_regen_quantity=(raw.get('health_regen_quantity') if isinstance(raw, dict) else raw[14]),
            armor=(raw.get('armor') if isinstance(raw, dict) else raw[15]),
            accuracy=(raw.get('accuracy') if isinstance(raw, dict) else raw[16]),
            evasion=(raw.get('evasion') if isinstance(raw, dict) else raw[17]),
            strength=(raw.get('strength') if isinstance(raw, dict) else raw[18]),
            min_damage=(raw.get('min_damage') if isinstance(raw, dict) else raw[19]),
            max_damage=(raw.get('max_damage') if isinstance(raw, dict) else raw[20]),
            cooldown_multiplier=(raw.get('cooldown_multiplier') if isinstance(raw, dict) else raw[21]),
            daytime_detect_range=(raw.get('daytime_detect_range') if isinstance(raw, dict) else raw[22]),
            daytime_aggro_range=(raw.get('daytime_aggro_range') if isinstance(raw, dict) else raw[23]),
            daytime_deaggro_range=(raw.get('daytime_deaggro_range') if isinstance(raw, dict) else raw[24]),
            nighttime_detect_range=(raw.get('nighttime_detect_range') if isinstance(raw, dict) else raw[25]),
            nighttime_aggro_range=(raw.get('nighttime_aggro_range') if isinstance(raw, dict) else raw[26]),
            nighttime_deaggro_range=(raw.get('nighttime_deaggro_range') if isinstance(raw, dict) else raw[27]),
            evade_range=(raw.get('evade_range') if isinstance(raw, dict) else raw[28]),
            deaggro_health_threshold=(raw.get('deaggro_health_threshold') if isinstance(raw, dict) else raw[29]),
            attack_level=(raw.get('attack_level') if isinstance(raw, dict) else raw[30]),
            defense_level=(raw.get('defense_level') if isinstance(raw, dict) else raw[31]),
            prefab_address=(raw.get('prefab_address') if isinstance(raw, dict) else raw[32]),
            icon_address=(raw.get('icon_address') if isinstance(raw, dict) else raw[33]),
            extracted_item_stacks=[ProbabilisticItemStack.from_row(_item) for _item in ((raw.get('extracted_item_stacks') if isinstance(raw, dict) else raw[34]) or [])],
            experience_per_damage_dealt=[ExperienceStackF32.from_row(_item) for _item in ((raw.get('experience_per_damage_dealt') if isinstance(raw, dict) else raw[35]) or [])],
            tier=(raw.get('tier') if isinstance(raw, dict) else raw[36]),
            tag=(raw.get('tag') if isinstance(raw, dict) else raw[37]),
            rarity=Rarity.from_row((raw.get('rarity') if isinstance(raw, dict) else raw[38])),
            huntable=(raw.get('huntable') if isinstance(raw, dict) else raw[39])
        )
