# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .equipment_slot import EquipmentSlot



@dataclass
class EquipmentPresetState:
    entity_id: int = 0
    player_entity_id: int = 0
    index: int = 0
    active: bool = False
    equipment_slots: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'EquipmentPresetState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[1]),
            index=(raw.get('index') if isinstance(raw, dict) else raw[2]),
            active=(raw.get('active') if isinstance(raw, dict) else raw[3]),
            equipment_slots=[EquipmentSlot.from_row(_item) for _item in ((raw.get('equipment_slots') if isinstance(raw, dict) else raw[4]) or [])]
        )
