# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ExperienceStack:
    skill_id: int = 0
    quantity: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ExperienceStack':
        if raw is None:
            return cls()
        return cls(
            skill_id=(raw.get('skill_id') if isinstance(raw, dict) else raw[0]),
            quantity=(raw.get('quantity') if isinstance(raw, dict) else raw[1])
        )
