# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ExplorationChunksStateV2:
    entity_id: int = 0
    bitmap: list = field(default_factory=list)
    explored_chunks_count: int = 0
    achievement_explored_chunks_count: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ExplorationChunksStateV2':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            bitmap=[_item for _item in ((raw.get('bitmap') if isinstance(raw, dict) else raw[1]) or [])],
            explored_chunks_count=(raw.get('explored_chunks_count') if isinstance(raw, dict) else raw[2]),
            achievement_explored_chunks_count=(raw.get('achievement_explored_chunks_count') if isinstance(raw, dict) else raw[3])
        )
