# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ExtractOutcomeState:
    entity_id: int = 0
    target_entity_id: int = 0
    last_timestamp: object = 0
    damage: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ExtractOutcomeState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            target_entity_id=(raw.get('target_entity_id') if isinstance(raw, dict) else raw[1]),
            last_timestamp=(raw.get('last_timestamp') if isinstance(raw, dict) else raw[2]),
            damage=(raw.get('damage') if isinstance(raw, dict) else raw[3])
        )
