# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .footprint_type import FootprintType



@dataclass
class FootprintTile:
    x: int = 0
    z: int = 0
    footprint_type: FootprintType = 0

    @classmethod
    def from_row(cls, raw) -> 'FootprintTile':
        if raw is None:
            return cls()
        return cls(
            x=(raw.get('x') if isinstance(raw, dict) else raw[0]),
            z=(raw.get('z') if isinstance(raw, dict) else raw[1]),
            footprint_type=FootprintType.from_row((raw.get('footprint_type') if isinstance(raw, dict) else raw[2]))
        )
