# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class FriendsState:
    entity_id: int = 0
    owner_entity_id: int = 0
    friend_entity_id: int = 0
    is_favorite: bool = False

    @classmethod
    def from_row(cls, raw) -> 'FriendsState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            owner_entity_id=(raw.get('owner_entity_id') if isinstance(raw, dict) else raw[1]),
            friend_entity_id=(raw.get('friend_entity_id') if isinstance(raw, dict) else raw[2]),
            is_favorite=(raw.get('is_favorite') if isinstance(raw, dict) else raw[3])
        )
