# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class GateDesc:
    building_id: int = 0
    small_post_asset_name: str = ''

    @classmethod
    def from_row(cls, raw) -> 'GateDesc':
        if raw is None:
            return cls()
        return cls(
            building_id=(raw.get('building_id') if isinstance(raw, dict) else raw[0]),
            small_post_asset_name=(raw.get('small_post_asset_name') if isinstance(raw, dict) else raw[1])
        )
