# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .hub_item_type import HubItemType



@dataclass
class GrantedHubItemState:
    entity_id: int = 0
    identity: object = 0
    item_type: HubItemType = 0
    item_id: int = 0
    balance: int = 0

    @classmethod
    def from_row(cls, raw) -> 'GrantedHubItemState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            identity=(raw.get('identity') if isinstance(raw, dict) else raw[1]),
            item_type=HubItemType.from_row((raw.get('item_type') if isinstance(raw, dict) else raw[2])),
            item_id=(raw.get('item_id') if isinstance(raw, dict) else raw[3]),
            balance=(raw.get('balance') if isinstance(raw, dict) else raw[4])
        )
