# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class HandEquipmentVisual:
    main_hand: bool = False
    prefab_names: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'HandEquipmentVisual':
        if raw is None:
            return cls()
        return cls(
            main_hand=(raw.get('main_hand') if isinstance(raw, dict) else raw[0]),
            prefab_names=[_item for _item in ((raw.get('prefab_names') if isinstance(raw, dict) else raw[1]) or [])]
        )
