# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class HerdState:
    entity_id: int = 0
    enemy_ai_params_desc_id: int = 0
    current_population: int = 0
    ignore_eagerness: bool = False
    population_variance: list = field(default_factory=list)
    crumb_trail_entity_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'HerdState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            enemy_ai_params_desc_id=(raw.get('enemy_ai_params_desc_id') if isinstance(raw, dict) else raw[1]),
            current_population=(raw.get('current_population') if isinstance(raw, dict) else raw[2]),
            ignore_eagerness=(raw.get('ignore_eagerness') if isinstance(raw, dict) else raw[3]),
            population_variance=[_item for _item in ((raw.get('population_variance') if isinstance(raw, dict) else raw[4]) or [])],
            crumb_trail_entity_id=(raw.get('crumb_trail_entity_id') if isinstance(raw, dict) else raw[5])
        )
