# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class HexDirection(IntEnum):
    NE = 0
    ENE = 1
    E = 2
    ESE = 3
    SE = 4
    S = 5
    SW = 6
    WSW = 7
    W = 8
    WNW = 9
    NW = 10
    N = 11


    @classmethod
    def from_row(cls, raw) -> 'HexDirection':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for NE
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse HexDirection from {raw!r}')
