# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class HubItemType(IntEnum):
    HEXITESHARDS = 0
    COLLECTIBLE = 1
    PREMIUMITEM = 2


    @classmethod
    def from_row(cls, raw) -> 'HubItemType':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for HexiteShards
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse HubItemType from {raw!r}')
