# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .role import Role



@dataclass
class IdentityRole:
    identity: str = 0
    role: Role = 0

    @classmethod
    def from_row(cls, raw) -> 'IdentityRole':
        if raw is None:
            return cls()
        return cls(
            identity=((raw.get('identity') if isinstance(raw, dict) else raw[0])['__identity__'] if isinstance((raw.get('identity') if isinstance(raw, dict) else raw[0]), dict) else ((raw.get('identity') if isinstance(raw, dict) else raw[0])[0] if isinstance((raw.get('identity') if isinstance(raw, dict) else raw[0]), list) else (raw.get('identity') if isinstance(raw, dict) else raw[0]))),
            role=Role.from_row((raw.get('role') if isinstance(raw, dict) else raw[1]))
        )
