# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_type import ItemType



@dataclass
class InputItemStack:
    item_id: int = 0
    quantity: int = 0
    item_type: ItemType = 0
    discovery_score: int = 0
    consumption_chance: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'InputItemStack':
        if raw is None:
            return cls()
        return cls(
            item_id=(raw.get('item_id') if isinstance(raw, dict) else raw[0]),
            quantity=(raw.get('quantity') if isinstance(raw, dict) else raw[1]),
            item_type=ItemType.from_row((raw.get('item_type') if isinstance(raw, dict) else raw[2])),
            discovery_score=(raw.get('discovery_score') if isinstance(raw, dict) else raw[3]),
            consumption_chance=(raw.get('consumption_chance') if isinstance(raw, dict) else raw[4])
        )
