# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .message_contents_v2 import MessageContentsV2



@dataclass
class InterModuleMessageV2:
    id: int = 0
    to: int = 0
    contents: MessageContentsV2 = 0

    @classmethod
    def from_row(cls, raw) -> 'InterModuleMessageV2':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            to=(raw.get('to') if isinstance(raw, dict) else raw[1]),
            contents=MessageContentsV2.from_row((raw.get('contents') if isinstance(raw, dict) else raw[2]))
        )
