# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class InteriorEnvironmentDesc:
    id: int = 0
    name: str = ''
    skybox_material: str = ''
    realtime_shadow_color: int = 0
    lighting_source: int = 0
    lighting_skybox_intensity: float = 0.0
    lighting_gradient_sky_color: int = 0
    lighting_gradient_equator_color: int = 0
    lighting_gradient_ground_color: int = 0
    lighting_color_ambient_color: int = 0
    fog_enable: bool = False
    fog_color: int = 0
    fog_mode: int = 0
    fog_density: float = 0.0
    fog_start_distance: float = 0.0
    fog_end_distance: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'InteriorEnvironmentDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            skybox_material=(raw.get('skybox_material') if isinstance(raw, dict) else raw[2]),
            realtime_shadow_color=(raw.get('realtime_shadow_color') if isinstance(raw, dict) else raw[3]),
            lighting_source=(raw.get('lighting_source') if isinstance(raw, dict) else raw[4]),
            lighting_skybox_intensity=(raw.get('lighting_skybox_intensity') if isinstance(raw, dict) else raw[5]),
            lighting_gradient_sky_color=(raw.get('lighting_gradient_sky_color') if isinstance(raw, dict) else raw[6]),
            lighting_gradient_equator_color=(raw.get('lighting_gradient_equator_color') if isinstance(raw, dict) else raw[7]),
            lighting_gradient_ground_color=(raw.get('lighting_gradient_ground_color') if isinstance(raw, dict) else raw[8]),
            lighting_color_ambient_color=(raw.get('lighting_color_ambient_color') if isinstance(raw, dict) else raw[9]),
            fog_enable=(raw.get('fog_enable') if isinstance(raw, dict) else raw[10]),
            fog_color=(raw.get('fog_color') if isinstance(raw, dict) else raw[11]),
            fog_mode=(raw.get('fog_mode') if isinstance(raw, dict) else raw[12]),
            fog_density=(raw.get('fog_density') if isinstance(raw, dict) else raw[13]),
            fog_start_distance=(raw.get('fog_start_distance') if isinstance(raw, dict) else raw[14]),
            fog_end_distance=(raw.get('fog_end_distance') if isinstance(raw, dict) else raw[15])
        )
