# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .enemy_type import EnemyType
from .interior_spawn_type import InteriorSpawnType
from .npc_type import NpcType



@dataclass
class InteriorSpawnDesc:
    id: int = 0
    name: str = ''
    interior_instance_id: int = 0
    spawn_x: int = 0
    spawn_z: int = 0
    direction: int = 0
    spawn_type: InteriorSpawnType = 0
    building_id: int = 0
    paving_id: int = 0
    loot_chests: list = field(default_factory=list)
    resource_clump_id: int = 0
    enemy_type: EnemyType = 0
    traveler_type: NpcType = 0
    traveler_ruin_entity_id: int = 0
    respawn: bool = False
    collapse_trigger: bool = False

    @classmethod
    def from_row(cls, raw) -> 'InteriorSpawnDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            interior_instance_id=(raw.get('interior_instance_id') if isinstance(raw, dict) else raw[2]),
            spawn_x=(raw.get('spawn_x') if isinstance(raw, dict) else raw[3]),
            spawn_z=(raw.get('spawn_z') if isinstance(raw, dict) else raw[4]),
            direction=(raw.get('direction') if isinstance(raw, dict) else raw[5]),
            spawn_type=InteriorSpawnType.from_row((raw.get('spawn_type') if isinstance(raw, dict) else raw[6])),
            building_id=(raw.get('building_id') if isinstance(raw, dict) else raw[7]),
            paving_id=(raw.get('paving_id') if isinstance(raw, dict) else raw[8]),
            loot_chests=[_item for _item in ((raw.get('loot_chests') if isinstance(raw, dict) else raw[9]) or [])],
            resource_clump_id=(raw.get('resource_clump_id') if isinstance(raw, dict) else raw[10]),
            enemy_type=EnemyType.from_row((raw.get('enemy_type') if isinstance(raw, dict) else raw[11])),
            traveler_type=NpcType.from_row((raw.get('traveler_type') if isinstance(raw, dict) else raw[12])),
            traveler_ruin_entity_id=(raw.get('traveler_ruin_entity_id') if isinstance(raw, dict) else raw[13]),
            respawn=(raw.get('respawn') if isinstance(raw, dict) else raw[14]),
            collapse_trigger=(raw.get('collapse_trigger') if isinstance(raw, dict) else raw[15])
        )
