# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .message_contents_v4 import MessageContentsV4



@dataclass
class InterModuleMessageV4:
    id: int = 0
    to: int = 0
    contents: MessageContentsV4 = 0

    @classmethod
    def from_row(cls, raw) -> 'InterModuleMessageV4':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            to=(raw.get('to') if isinstance(raw, dict) else raw[1]),
            contents=MessageContentsV4.from_row((raw.get('contents') if isinstance(raw, dict) else raw[2]))
        )
