# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class InteriorPlayerCountState:
    entity_id: int = 0
    dimension_network_entity_id: int = 0
    player_count: int = 0

    @classmethod
    def from_row(cls, raw) -> 'InteriorPlayerCountState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            dimension_network_entity_id=(raw.get('dimension_network_entity_id') if isinstance(raw, dict) else raw[1]),
            player_count=(raw.get('player_count') if isinstance(raw, dict) else raw[2])
        )
