# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class InteriorSpawnType(IntEnum):
    UNDEFINED = 0
    TRAVELER = 1
    CHEST = 2
    BUILDING = 3
    RESOURCE = 4
    ENEMY = 5
    PAVING = 6


    @classmethod
    def from_row(cls, raw) -> 'InteriorSpawnType':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for Undefined
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse InteriorSpawnType from {raw!r}')
