# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class InterModuleResponseMessageCounter:
    dst_module_id: int = 0
    last_processed_message_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'InterModuleResponseMessageCounter':
        if raw is None:
            return cls()
        return cls(
            dst_module_id=(raw.get('dst_module_id') if isinstance(raw, dict) else raw[0]),
            last_processed_message_id=(raw.get('last_processed_message_id') if isinstance(raw, dict) else raw[1])
        )
