# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_stack import ItemStack



@dataclass
class ItemConversionRecipeDesc:
    id: int = 0
    name: str = ''
    time_cost: int = 0
    stamina_cost: int = 0
    location_context: int = 0
    string_context: str = ''
    output_item: ItemStack | None = None
    input_items: list = field(default_factory=list)
    required_equipment_id: int = 0
    required_equipment_tier: int = 0
    allow_use_hands: bool = False
    recipe_performance_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ItemConversionRecipeDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            time_cost=(raw.get('time_cost') if isinstance(raw, dict) else raw[2]),
            stamina_cost=(raw.get('stamina_cost') if isinstance(raw, dict) else raw[3]),
            location_context=(raw.get('location_context') if isinstance(raw, dict) else raw[4]),
            string_context=(raw.get('string_context') if isinstance(raw, dict) else raw[5]),
            output_item=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (ItemStack.from_row(_v[1])))((raw.get('output_item') if isinstance(raw, dict) else raw[6])),
            input_items=[ItemStack.from_row(_item) for _item in ((raw.get('input_items') if isinstance(raw, dict) else raw[7]) or [])],
            required_equipment_id=(raw.get('required_equipment_id') if isinstance(raw, dict) else raw[8]),
            required_equipment_tier=(raw.get('required_equipment_tier') if isinstance(raw, dict) else raw[9]),
            allow_use_hands=(raw.get('allow_use_hands') if isinstance(raw, dict) else raw[10]),
            recipe_performance_id=(raw.get('recipe_performance_id') if isinstance(raw, dict) else raw[11])
        )
