# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_type import ItemType



@dataclass
class ItemStack:
    item_id: int = 0
    quantity: int = 0
    item_type: ItemType = 0
    durability: int | None = None

    @classmethod
    def from_row(cls, raw) -> 'ItemStack':
        if raw is None:
            return cls()
        return cls(
            item_id=(raw.get('item_id') if isinstance(raw, dict) else raw[0]),
            quantity=(raw.get('quantity') if isinstance(raw, dict) else raw[1]),
            item_type=ItemType.from_row((raw.get('item_type') if isinstance(raw, dict) else raw[2])),
            durability=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]))((raw.get('durability') if isinstance(raw, dict) else raw[3]))
        )
