# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class LootChestDesc:
    id: int = 0
    name: str = ''
    chest_rarity: int = 0
    prefab_address: str = ''
    loot_tables: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'LootChestDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            chest_rarity=(raw.get('chest_rarity') if isinstance(raw, dict) else raw[2]),
            prefab_address=(raw.get('prefab_address') if isinstance(raw, dict) else raw[3]),
            loot_tables=[_item for _item in ((raw.get('loot_tables') if isinstance(raw, dict) else raw[4]) or [])]
        )
