# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_small_message import OffsetCoordinatesSmallMessage



@dataclass
class LostItemsState:
    inventory_entity_id: int = 0
    owner_entity_id: int = 0
    location: OffsetCoordinatesSmallMessage = 0

    @classmethod
    def from_row(cls, raw) -> 'LostItemsState':
        if raw is None:
            return cls()
        return cls(
            inventory_entity_id=(raw.get('inventory_entity_id') if isinstance(raw, dict) else raw[0]),
            owner_entity_id=(raw.get('owner_entity_id') if isinstance(raw, dict) else raw[1]),
            location=OffsetCoordinatesSmallMessage.from_row((raw.get('location') if isinstance(raw, dict) else raw[2]))
        )
