# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ModViolationState:
    violation_type: int = 0
    point_value_min: int = 0
    point_value_max: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ModViolationState':
        if raw is None:
            return cls()
        return cls(
            violation_type=(raw.get('violation_type') if isinstance(raw, dict) else raw[0]),
            point_value_min=(raw.get('point_value_min') if isinstance(raw, dict) else raw[1]),
            point_value_max=(raw.get('point_value_max') if isinstance(raw, dict) else raw[2])
        )
