# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ModReportConfigState:
    id: int = 0
    model: str = ''
    model_double_check: str = ''
    model_translate: str = ''
    offense_count_window_minutes: float = 0.0
    min_minutes_between_offenses: float = 0.0
    reportable_message_max_age: int = 0
    count_admin_moderation_actions: bool = False
    discord_webhook_url_user_reports: str = ''

    @classmethod
    def from_row(cls, raw) -> 'ModReportConfigState':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            model=(raw.get('model') if isinstance(raw, dict) else raw[1]),
            model_double_check=(raw.get('model_double_check') if isinstance(raw, dict) else raw[2]),
            model_translate=(raw.get('model_translate') if isinstance(raw, dict) else raw[3]),
            offense_count_window_minutes=(raw.get('offense_count_window_minutes') if isinstance(raw, dict) else raw[4]),
            min_minutes_between_offenses=(raw.get('min_minutes_between_offenses') if isinstance(raw, dict) else raw[5]),
            reportable_message_max_age=(raw.get('reportable_message_max_age') if isinstance(raw, dict) else raw[6]),
            count_admin_moderation_actions=(raw.get('count_admin_moderation_actions') if isinstance(raw, dict) else raw[7]),
            discord_webhook_url_user_reports=(raw.get('discord_webhook_url_user_reports') if isinstance(raw, dict) else raw[8])
        )
