# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ModConsequenceState:
    id: int = 0
    point_threshold: int = 0
    consequence_type: int = 0
    duration: int = 0
    flag_level_code: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ModConsequenceState':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            point_threshold=(raw.get('point_threshold') if isinstance(raw, dict) else raw[1]),
            consequence_type=(raw.get('consequence_type') if isinstance(raw, dict) else raw[2]),
            duration=(raw.get('duration') if isinstance(raw, dict) else raw[3]),
            flag_level_code=(raw.get('flag_level_code') if isinstance(raw, dict) else raw[4])
        )
