# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ModFlagLevelThresholdState:
    flag_level: int = 0
    point_threshold: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ModFlagLevelThresholdState':
        if raw is None:
            return cls()
        return cls(
            flag_level=(raw.get('flag_level') if isinstance(raw, dict) else raw[0]),
            point_threshold=(raw.get('point_threshold') if isinstance(raw, dict) else raw[1])
        )
