# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ModThresholdState:
    id: int = 0
    threshold_type: int = 0
    category: str = ''
    threshold: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'ModThresholdState':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            threshold_type=(raw.get('threshold_type') if isinstance(raw, dict) else raw[1]),
            category=(raw.get('category') if isinstance(raw, dict) else raw[2]),
            threshold=(raw.get('threshold') if isinstance(raw, dict) else raw[3])
        )
