# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ModFlaggedWordState:
    id: int = 0
    word_type: int = 0
    word: str = ''

    @classmethod
    def from_row(cls, raw) -> 'ModFlaggedWordState':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            word_type=(raw.get('word_type') if isinstance(raw, dict) else raw[1]),
            word=(raw.get('word') if isinstance(raw, dict) else raw[2])
        )
