# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class MoveValidationStrikeCounterState:
    entity_id: int = 0
    validation_failure_timestamps: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'MoveValidationStrikeCounterState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            validation_failure_timestamps=[_item for _item in ((raw.get('validation_failure_timestamps') if isinstance(raw, dict) else raw[1]) or [])]
        )
