# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class MoveValidationParamsDesc:
    strike_count_before_move_validation_failure: int = 0
    strike_counter_time_window_sec: int = 0

    @classmethod
    def from_row(cls, raw) -> 'MoveValidationParamsDesc':
        if raw is None:
            return cls()
        return cls(
            strike_count_before_move_validation_failure=(raw.get('strike_count_before_move_validation_failure') if isinstance(raw, dict) else raw[0]),
            strike_counter_time_window_sec=(raw.get('strike_counter_time_window_sec') if isinstance(raw, dict) else raw[1])
        )
