# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .npc_type import NpcType



@dataclass
class NpcState:
    entity_id: int = 0
    npc_type: NpcType = 0
    direction: int = 0
    building_entity_id: int = 0
    next_action_timestamp: int = 0
    move_duration: float = 0.0
    started_moving: int = 0
    previous_buildings: list = field(default_factory=list)
    traveling: bool = False

    @classmethod
    def from_row(cls, raw) -> 'NpcState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            npc_type=NpcType.from_row((raw.get('npc_type') if isinstance(raw, dict) else raw[1])),
            direction=(raw.get('direction') if isinstance(raw, dict) else raw[2]),
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[3]),
            next_action_timestamp=((raw.get('next_action_timestamp') if isinstance(raw, dict) else raw[4])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('next_action_timestamp') if isinstance(raw, dict) else raw[4]), dict) else ((raw.get('next_action_timestamp') if isinstance(raw, dict) else raw[4])[0] if isinstance((raw.get('next_action_timestamp') if isinstance(raw, dict) else raw[4]), list) else (raw.get('next_action_timestamp') if isinstance(raw, dict) else raw[4]))),
            move_duration=(raw.get('move_duration') if isinstance(raw, dict) else raw[5]),
            started_moving=(raw.get('started_moving') if isinstance(raw, dict) else raw[6]),
            previous_buildings=[_item for _item in ((raw.get('previous_buildings') if isinstance(raw, dict) else raw[7]) or [])],
            traveling=(raw.get('traveling') if isinstance(raw, dict) else raw[8])
        )
