# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .deployable_state import DeployableState
from .trade_order_state import TradeOrderState



@dataclass
class OnDeployableRecoveredMsg:
    player_entity_id: int = 0
    deployable_entity_id: int = 0
    deployable_desc_id: int = 0
    deployable_state: DeployableState = 0
    trade_orders: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'OnDeployableRecoveredMsg':
        if raw is None:
            return cls()
        return cls(
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[0]),
            deployable_entity_id=(raw.get('deployable_entity_id') if isinstance(raw, dict) else raw[1]),
            deployable_desc_id=(raw.get('deployable_desc_id') if isinstance(raw, dict) else raw[2]),
            deployable_state=DeployableState.from_row((raw.get('deployable_state') if isinstance(raw, dict) else raw[3])),
            trade_orders=[TradeOrderState.from_row(_item) for _item in ((raw.get('trade_orders') if isinstance(raw, dict) else raw[4]) or [])]
        )
