# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class OnEmpireBuildingDeletedMsg:
    player_entity_id: int = 0
    building_entity_id: int = 0
    ignore_portals: bool = False
    drop_items: bool = False

    @classmethod
    def from_row(cls, raw) -> 'OnEmpireBuildingDeletedMsg':
        if raw is None:
            return cls()
        return cls(
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[0]),
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[1]),
            ignore_portals=(raw.get('ignore_portals') if isinstance(raw, dict) else raw[2]),
            drop_items=(raw.get('drop_items') if isinstance(raw, dict) else raw[3])
        )
