# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_stack import ItemStack



@dataclass
class OnboardingRewardDesc:
    state_id: int = 0
    item_stack_rewards: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'OnboardingRewardDesc':
        if raw is None:
            return cls()
        return cls(
            state_id=(raw.get('state_id') if isinstance(raw, dict) else raw[0]),
            item_stack_rewards=[ItemStack.from_row(_item) for _item in ((raw.get('item_stack_rewards') if isinstance(raw, dict) else raw[1]) or [])]
        )
