# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .movement_speed import MovementSpeed



@dataclass
class ParametersDesc:
    version: int = 0
    default_speed: list = field(default_factory=list)
    default_num_inventory_pockets: int = 0
    tech_time_power_exponent: float = 0.0
    tech_time_log_base: float = 0.0
    min_seconds_to_passive_regen_health: int = 0
    min_seconds_to_passive_regen_stamina: int = 0
    repair_building_duration: int = 0
    repair_building_max_repair_percent: float = 0.0
    repair_building_show_damage_percent: float = 0.0
    environment_debuff_tick_millis: int = 0
    discovery_range: int = 0
    max_build_range: int = 0
    deconstruct_default_time: float = 0.0
    respawn_seconds: int = 0
    daytime: int = 0
    nighttime: int = 0
    resources_regen_loops: int = 0
    selected_traveler_order_count: int = 0
    resources_regen_tick_millis: int = 0
    building_decay_tick_millis: int = 0
    max_traded_items: int = 0
    max_trade_distance_large_tiles: int = 0
    min_distance_between_claims: int = 0
    starting_supplies: int = 0
    show_shield_bar_percent: float = 0.0
    swim_sprint_speed_multiplier: float = 0.0
    loot_chest_despawn_time_seconds: float = 0.0
    deployable_disembark_max_elevation: int = 0
    default_num_toolbelt_pockets: int = 0
    resource_growth_tick_rate_milliseconds: int = 0
    rent_deposit_days: int = 0
    rent_collection_time_of_day: float = 0.0
    rent_eviction_compensation: float = 0.0
    max_rental_deposit_days: int = 0
    recommended_achievements: int = 0
    empire_decay_tick_millis: int = 0
    empire_siege_tick_millis: int = 0
    empire_siege_raise_pct: float = 0.0
    empire_default_nobility_threshold: int = 0
    empire_shard_cost: int = 0
    empire_starting_shards: int = 0
    empire_node_max_energy: int = 0
    empire_node_starting_energy: int = 0
    empire_min_siege_distance: int = 0
    empire_max_siege_distance: int = 0
    daily_shards: int = 0
    hexite_capsule_supply_cost: int = 0
    hexite_capsule_shard_cost: int = 0
    hexite_capsule_craft_time_seconds: int = 0
    crafting_lock_duration_secs: int = 0
    starving_tick_millis: int = 0
    starving_damage: float = 0.0
    claim_stability_param_m: float = 0.0
    claim_stability_param_b: float = 0.0
    player_regen_tick_millis: int = 0
    enemy_regen_tick_millis: int = 0
    teleportation_energy_regen_tick_millis: int = 0
    auto_respawn_attempts: int = 0
    player_pathfinding_id: int = 0
    nearby_flame_buff_id: int = 0
    floating_origin_distance_threshold: int = 0
    withdraw_from_deployables_range: int = 0
    deposit_to_deployables_range: int = 0
    sign_in_aggro_immunity: int = 0
    respawn_aggro_immunity: int = 0
    new_user_aggro_immunity: int = 0
    terraform_experience_per_progress: float = 0.0
    dropped_inventory_ownership_seconds: int = 0
    dropped_inventory_despawn_seconds: int = 0
    traveler_tasks_per_npc: int = 0
    traveler_tasks_times_of_day: list = field(default_factory=list)
    teleport_channel_time_home: float = 0.0
    teleport_channel_time_waystone: float = 0.0
    teleportation_home_energy_cost: float = 0.0
    teleportation_base_energy_cost: float = 0.0
    teleportation_cost_per_large_tile: float = 0.0
    teleportation_full_inventory_multiplier: float = 0.0
    region_crossover_distance_large_tiles: int = 0
    item_recovery_range: int = 0
    quick_board_range: float = 0.0
    duel_range: float = 0.0
    duel_out_of_range_grace_period_millis: int = 0
    player_housing_eviction_time_minutes: int = 0
    player_housing_income_time_of_day: float = 0.0
    co_owner_take_ownership_supply_time: int = 0
    officer_take_ownership_supply_time: int = 0
    member_take_ownership_supply_time: int = 0
    empire_starting_currency: int = 0
    empire_rename_currency_cost: int = 0
    empire_move_capital_currency_cost: int = 0
    hexite_capsule_currency_cost: int = 0
    prospecting_herd_immunity_secs: int = 0
    rp_walk_speed: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'ParametersDesc':
        if raw is None:
            return cls()
        return cls(
            version=(raw.get('version') if isinstance(raw, dict) else raw[0]),
            default_speed=[MovementSpeed.from_row(_item) for _item in ((raw.get('default_speed') if isinstance(raw, dict) else raw[1]) or [])],
            default_num_inventory_pockets=(raw.get('default_num_inventory_pockets') if isinstance(raw, dict) else raw[2]),
            tech_time_power_exponent=(raw.get('tech_time_power_exponent') if isinstance(raw, dict) else raw[3]),
            tech_time_log_base=(raw.get('tech_time_log_base') if isinstance(raw, dict) else raw[4]),
            min_seconds_to_passive_regen_health=(raw.get('min_seconds_to_passive_regen_health') if isinstance(raw, dict) else raw[5]),
            min_seconds_to_passive_regen_stamina=(raw.get('min_seconds_to_passive_regen_stamina') if isinstance(raw, dict) else raw[6]),
            repair_building_duration=(raw.get('repair_building_duration') if isinstance(raw, dict) else raw[7]),
            repair_building_max_repair_percent=(raw.get('repair_building_max_repair_percent') if isinstance(raw, dict) else raw[8]),
            repair_building_show_damage_percent=(raw.get('repair_building_show_damage_percent') if isinstance(raw, dict) else raw[9]),
            environment_debuff_tick_millis=(raw.get('environment_debuff_tick_millis') if isinstance(raw, dict) else raw[10]),
            discovery_range=(raw.get('discovery_range') if isinstance(raw, dict) else raw[11]),
            max_build_range=(raw.get('max_build_range') if isinstance(raw, dict) else raw[12]),
            deconstruct_default_time=(raw.get('deconstruct_default_time') if isinstance(raw, dict) else raw[13]),
            respawn_seconds=(raw.get('respawn_seconds') if isinstance(raw, dict) else raw[14]),
            daytime=(raw.get('daytime') if isinstance(raw, dict) else raw[15]),
            nighttime=(raw.get('nighttime') if isinstance(raw, dict) else raw[16]),
            resources_regen_loops=(raw.get('resources_regen_loops') if isinstance(raw, dict) else raw[17]),
            selected_traveler_order_count=(raw.get('selected_traveler_order_count') if isinstance(raw, dict) else raw[18]),
            resources_regen_tick_millis=(raw.get('resources_regen_tick_millis') if isinstance(raw, dict) else raw[19]),
            building_decay_tick_millis=(raw.get('building_decay_tick_millis') if isinstance(raw, dict) else raw[20]),
            max_traded_items=(raw.get('max_traded_items') if isinstance(raw, dict) else raw[21]),
            max_trade_distance_large_tiles=(raw.get('max_trade_distance_large_tiles') if isinstance(raw, dict) else raw[22]),
            min_distance_between_claims=(raw.get('min_distance_between_claims') if isinstance(raw, dict) else raw[23]),
            starting_supplies=(raw.get('starting_supplies') if isinstance(raw, dict) else raw[24]),
            show_shield_bar_percent=(raw.get('show_shield_bar_percent') if isinstance(raw, dict) else raw[25]),
            swim_sprint_speed_multiplier=(raw.get('swim_sprint_speed_multiplier') if isinstance(raw, dict) else raw[26]),
            loot_chest_despawn_time_seconds=(raw.get('loot_chest_despawn_time_seconds') if isinstance(raw, dict) else raw[27]),
            deployable_disembark_max_elevation=(raw.get('deployable_disembark_max_elevation') if isinstance(raw, dict) else raw[28]),
            default_num_toolbelt_pockets=(raw.get('default_num_toolbelt_pockets') if isinstance(raw, dict) else raw[29]),
            resource_growth_tick_rate_milliseconds=(raw.get('resource_growth_tick_rate_milliseconds') if isinstance(raw, dict) else raw[30]),
            rent_deposit_days=(raw.get('rent_deposit_days') if isinstance(raw, dict) else raw[31]),
            rent_collection_time_of_day=(raw.get('rent_collection_time_of_day') if isinstance(raw, dict) else raw[32]),
            rent_eviction_compensation=(raw.get('rent_eviction_compensation') if isinstance(raw, dict) else raw[33]),
            max_rental_deposit_days=(raw.get('max_rental_deposit_days') if isinstance(raw, dict) else raw[34]),
            recommended_achievements=(raw.get('recommended_achievements') if isinstance(raw, dict) else raw[35]),
            empire_decay_tick_millis=(raw.get('empire_decay_tick_millis') if isinstance(raw, dict) else raw[36]),
            empire_siege_tick_millis=(raw.get('empire_siege_tick_millis') if isinstance(raw, dict) else raw[37]),
            empire_siege_raise_pct=(raw.get('empire_siege_raise_pct') if isinstance(raw, dict) else raw[38]),
            empire_default_nobility_threshold=(raw.get('empire_default_nobility_threshold') if isinstance(raw, dict) else raw[39]),
            empire_shard_cost=(raw.get('empire_shard_cost') if isinstance(raw, dict) else raw[40]),
            empire_starting_shards=(raw.get('empire_starting_shards') if isinstance(raw, dict) else raw[41]),
            empire_node_max_energy=(raw.get('empire_node_max_energy') if isinstance(raw, dict) else raw[42]),
            empire_node_starting_energy=(raw.get('empire_node_starting_energy') if isinstance(raw, dict) else raw[43]),
            empire_min_siege_distance=(raw.get('empire_min_siege_distance') if isinstance(raw, dict) else raw[44]),
            empire_max_siege_distance=(raw.get('empire_max_siege_distance') if isinstance(raw, dict) else raw[45]),
            daily_shards=(raw.get('daily_shards') if isinstance(raw, dict) else raw[46]),
            hexite_capsule_supply_cost=(raw.get('hexite_capsule_supply_cost') if isinstance(raw, dict) else raw[47]),
            hexite_capsule_shard_cost=(raw.get('hexite_capsule_shard_cost') if isinstance(raw, dict) else raw[48]),
            hexite_capsule_craft_time_seconds=(raw.get('hexite_capsule_craft_time_seconds') if isinstance(raw, dict) else raw[49]),
            crafting_lock_duration_secs=(raw.get('crafting_lock_duration_secs') if isinstance(raw, dict) else raw[50]),
            starving_tick_millis=(raw.get('starving_tick_millis') if isinstance(raw, dict) else raw[51]),
            starving_damage=(raw.get('starving_damage') if isinstance(raw, dict) else raw[52]),
            claim_stability_param_m=(raw.get('claim_stability_param_m') if isinstance(raw, dict) else raw[53]),
            claim_stability_param_b=(raw.get('claim_stability_param_b') if isinstance(raw, dict) else raw[54]),
            player_regen_tick_millis=(raw.get('player_regen_tick_millis') if isinstance(raw, dict) else raw[55]),
            enemy_regen_tick_millis=(raw.get('enemy_regen_tick_millis') if isinstance(raw, dict) else raw[56]),
            teleportation_energy_regen_tick_millis=(raw.get('teleportation_energy_regen_tick_millis') if isinstance(raw, dict) else raw[57]),
            auto_respawn_attempts=(raw.get('auto_respawn_attempts') if isinstance(raw, dict) else raw[58]),
            player_pathfinding_id=(raw.get('player_pathfinding_id') if isinstance(raw, dict) else raw[59]),
            nearby_flame_buff_id=(raw.get('nearby_flame_buff_id') if isinstance(raw, dict) else raw[60]),
            floating_origin_distance_threshold=(raw.get('floating_origin_distance_threshold') if isinstance(raw, dict) else raw[61]),
            withdraw_from_deployables_range=(raw.get('withdraw_from_deployables_range') if isinstance(raw, dict) else raw[62]),
            deposit_to_deployables_range=(raw.get('deposit_to_deployables_range') if isinstance(raw, dict) else raw[63]),
            sign_in_aggro_immunity=(raw.get('sign_in_aggro_immunity') if isinstance(raw, dict) else raw[64]),
            respawn_aggro_immunity=(raw.get('respawn_aggro_immunity') if isinstance(raw, dict) else raw[65]),
            new_user_aggro_immunity=(raw.get('new_user_aggro_immunity') if isinstance(raw, dict) else raw[66]),
            terraform_experience_per_progress=(raw.get('terraform_experience_per_progress') if isinstance(raw, dict) else raw[67]),
            dropped_inventory_ownership_seconds=(raw.get('dropped_inventory_ownership_seconds') if isinstance(raw, dict) else raw[68]),
            dropped_inventory_despawn_seconds=(raw.get('dropped_inventory_despawn_seconds') if isinstance(raw, dict) else raw[69]),
            traveler_tasks_per_npc=(raw.get('traveler_tasks_per_npc') if isinstance(raw, dict) else raw[70]),
            traveler_tasks_times_of_day=[_item for _item in ((raw.get('traveler_tasks_times_of_day') if isinstance(raw, dict) else raw[71]) or [])],
            teleport_channel_time_home=(raw.get('teleport_channel_time_home') if isinstance(raw, dict) else raw[72]),
            teleport_channel_time_waystone=(raw.get('teleport_channel_time_waystone') if isinstance(raw, dict) else raw[73]),
            teleportation_home_energy_cost=(raw.get('teleportation_home_energy_cost') if isinstance(raw, dict) else raw[74]),
            teleportation_base_energy_cost=(raw.get('teleportation_base_energy_cost') if isinstance(raw, dict) else raw[75]),
            teleportation_cost_per_large_tile=(raw.get('teleportation_cost_per_large_tile') if isinstance(raw, dict) else raw[76]),
            teleportation_full_inventory_multiplier=(raw.get('teleportation_full_inventory_multiplier') if isinstance(raw, dict) else raw[77]),
            region_crossover_distance_large_tiles=(raw.get('region_crossover_distance_large_tiles') if isinstance(raw, dict) else raw[78]),
            item_recovery_range=(raw.get('item_recovery_range') if isinstance(raw, dict) else raw[79]),
            quick_board_range=(raw.get('quick_board_range') if isinstance(raw, dict) else raw[80]),
            duel_range=(raw.get('duel_range') if isinstance(raw, dict) else raw[81]),
            duel_out_of_range_grace_period_millis=(raw.get('duel_out_of_range_grace_period_millis') if isinstance(raw, dict) else raw[82]),
            player_housing_eviction_time_minutes=(raw.get('player_housing_eviction_time_minutes') if isinstance(raw, dict) else raw[83]),
            player_housing_income_time_of_day=(raw.get('player_housing_income_time_of_day') if isinstance(raw, dict) else raw[84]),
            co_owner_take_ownership_supply_time=(raw.get('co_owner_take_ownership_supply_time') if isinstance(raw, dict) else raw[85]),
            officer_take_ownership_supply_time=(raw.get('officer_take_ownership_supply_time') if isinstance(raw, dict) else raw[86]),
            member_take_ownership_supply_time=(raw.get('member_take_ownership_supply_time') if isinstance(raw, dict) else raw[87]),
            empire_starting_currency=(raw.get('empire_starting_currency') if isinstance(raw, dict) else raw[88]),
            empire_rename_currency_cost=(raw.get('empire_rename_currency_cost') if isinstance(raw, dict) else raw[89]),
            empire_move_capital_currency_cost=(raw.get('empire_move_capital_currency_cost') if isinstance(raw, dict) else raw[90]),
            hexite_capsule_currency_cost=(raw.get('hexite_capsule_currency_cost') if isinstance(raw, dict) else raw[91]),
            prospecting_herd_immunity_secs=(raw.get('prospecting_herd_immunity_secs') if isinstance(raw, dict) else raw[92]),
            rp_walk_speed=(raw.get('rp_walk_speed') if isinstance(raw, dict) else raw[93])
        )
