# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .pathfinding_traversal_option import PathfindingTraversalOption



@dataclass
class PathfindingDesc:
    id: int = 0
    can_walk_on_land: bool = False
    can_swim: bool = False
    requires_transitions: bool = False
    min_water_depth: int = 0
    max_water_depth: int = 0
    max_swim_height_delta: int = 0
    avoid_light: bool = False
    climb_up_options: list = field(default_factory=list)
    climb_down_options: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'PathfindingDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            can_walk_on_land=(raw.get('can_walk_on_land') if isinstance(raw, dict) else raw[1]),
            can_swim=(raw.get('can_swim') if isinstance(raw, dict) else raw[2]),
            requires_transitions=(raw.get('requires_transitions') if isinstance(raw, dict) else raw[3]),
            min_water_depth=(raw.get('min_water_depth') if isinstance(raw, dict) else raw[4]),
            max_water_depth=(raw.get('max_water_depth') if isinstance(raw, dict) else raw[5]),
            max_swim_height_delta=(raw.get('max_swim_height_delta') if isinstance(raw, dict) else raw[6]),
            avoid_light=(raw.get('avoid_light') if isinstance(raw, dict) else raw[7]),
            climb_up_options=[PathfindingTraversalOption.from_row(_item) for _item in ((raw.get('climb_up_options') if isinstance(raw, dict) else raw[8]) or [])],
            climb_down_options=[PathfindingTraversalOption.from_row(_item) for _item in ((raw.get('climb_down_options') if isinstance(raw, dict) else raw[9]) or [])]
        )
