# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .experience_stack_f32 import ExperienceStackF32
from .input_item_stack import InputItemStack



@dataclass
class PillarShapingDesc:
    id: int = 0
    name: str = ''
    consumed_item_stacks: list = field(default_factory=list)
    input_cargo_id: int = 0
    input_cargo_discovery_score: int = 0
    experience_per_progress: list = field(default_factory=list)
    discovery_triggers: list = field(default_factory=list)
    required_knowledges: list = field(default_factory=list)
    full_discovery_score: int = 0
    duration: float = 0.0
    prefab_address: str = ''
    tier: int = 0
    icon_address: str = ''
    description: str = ''

    @classmethod
    def from_row(cls, raw) -> 'PillarShapingDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            consumed_item_stacks=[InputItemStack.from_row(_item) for _item in ((raw.get('consumed_item_stacks') if isinstance(raw, dict) else raw[2]) or [])],
            input_cargo_id=(raw.get('input_cargo_id') if isinstance(raw, dict) else raw[3]),
            input_cargo_discovery_score=(raw.get('input_cargo_discovery_score') if isinstance(raw, dict) else raw[4]),
            experience_per_progress=[ExperienceStackF32.from_row(_item) for _item in ((raw.get('experience_per_progress') if isinstance(raw, dict) else raw[5]) or [])],
            discovery_triggers=[_item for _item in ((raw.get('discovery_triggers') if isinstance(raw, dict) else raw[6]) or [])],
            required_knowledges=[_item for _item in ((raw.get('required_knowledges') if isinstance(raw, dict) else raw[7]) or [])],
            full_discovery_score=(raw.get('full_discovery_score') if isinstance(raw, dict) else raw[8]),
            duration=(raw.get('duration') if isinstance(raw, dict) else raw[9]),
            prefab_address=(raw.get('prefab_address') if isinstance(raw, dict) else raw[10]),
            tier=(raw.get('tier') if isinstance(raw, dict) else raw[11]),
            icon_address=(raw.get('icon_address') if isinstance(raw, dict) else raw[12]),
            description=(raw.get('description') if isinstance(raw, dict) else raw[13])
        )
