# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .biome import Biome
from .item_stack import ItemStack
from .level_requirement import LevelRequirement
from .tool_requirement import ToolRequirement



@dataclass
class PlaceablePlacementDesc:
    id: int = 0
    placed_placeable_id: int = 0
    input_item: ItemStack = 0
    required_time: float = 0.0
    level_requirements: list = field(default_factory=list)
    tool_requirements: list = field(default_factory=list)
    required_knowledges: list = field(default_factory=list)
    blocking_knowledges: list = field(default_factory=list)
    required_biomes: list = field(default_factory=list)
    place_on_land: bool = False
    land_elevation_min: int = 0
    land_elevation_max: int = 0
    place_on_water: bool = False
    water_depth_min: int = 0
    water_depth_max: int = 0
    required_paving_tier: int = 0
    required_interior_tier: int = 0
    required_claim_tier: int = 0
    min_distance_to_player_claims: int = 0
    min_distance_to_group: int = 0
    min_distance_to_other_placeables: int = 0
    min_distance_to_existing_footprints: int = 0
    max_distance_to_buildings: int = 0
    buildings: list = field(default_factory=list)
    recipe_performance_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlaceablePlacementDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            placed_placeable_id=(raw.get('placed_placeable_id') if isinstance(raw, dict) else raw[1]),
            input_item=ItemStack.from_row((raw.get('input_item') if isinstance(raw, dict) else raw[2])),
            required_time=(raw.get('required_time') if isinstance(raw, dict) else raw[3]),
            level_requirements=[LevelRequirement.from_row(_item) for _item in ((raw.get('level_requirements') if isinstance(raw, dict) else raw[4]) or [])],
            tool_requirements=[ToolRequirement.from_row(_item) for _item in ((raw.get('tool_requirements') if isinstance(raw, dict) else raw[5]) or [])],
            required_knowledges=[_item for _item in ((raw.get('required_knowledges') if isinstance(raw, dict) else raw[6]) or [])],
            blocking_knowledges=[_item for _item in ((raw.get('blocking_knowledges') if isinstance(raw, dict) else raw[7]) or [])],
            required_biomes=[Biome.from_row(_item) for _item in ((raw.get('required_biomes') if isinstance(raw, dict) else raw[8]) or [])],
            place_on_land=(raw.get('place_on_land') if isinstance(raw, dict) else raw[9]),
            land_elevation_min=(raw.get('land_elevation_min') if isinstance(raw, dict) else raw[10]),
            land_elevation_max=(raw.get('land_elevation_max') if isinstance(raw, dict) else raw[11]),
            place_on_water=(raw.get('place_on_water') if isinstance(raw, dict) else raw[12]),
            water_depth_min=(raw.get('water_depth_min') if isinstance(raw, dict) else raw[13]),
            water_depth_max=(raw.get('water_depth_max') if isinstance(raw, dict) else raw[14]),
            required_paving_tier=(raw.get('required_paving_tier') if isinstance(raw, dict) else raw[15]),
            required_interior_tier=(raw.get('required_interior_tier') if isinstance(raw, dict) else raw[16]),
            required_claim_tier=(raw.get('required_claim_tier') if isinstance(raw, dict) else raw[17]),
            min_distance_to_player_claims=(raw.get('min_distance_to_player_claims') if isinstance(raw, dict) else raw[18]),
            min_distance_to_group=(raw.get('min_distance_to_group') if isinstance(raw, dict) else raw[19]),
            min_distance_to_other_placeables=(raw.get('min_distance_to_other_placeables') if isinstance(raw, dict) else raw[20]),
            min_distance_to_existing_footprints=(raw.get('min_distance_to_existing_footprints') if isinstance(raw, dict) else raw[21]),
            max_distance_to_buildings=(raw.get('max_distance_to_buildings') if isinstance(raw, dict) else raw[22]),
            buildings=[_item for _item in ((raw.get('buildings') if isinstance(raw, dict) else raw[23]) or [])],
            recipe_performance_id=(raw.get('recipe_performance_id') if isinstance(raw, dict) else raw[24])
        )
