# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlaceableState:
    entity_id: int = 0
    owner_entity_id: int = 0
    placeable_id: int = 0
    direction_index: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlaceableState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            owner_entity_id=(raw.get('owner_entity_id') if isinstance(raw, dict) else raw[1]),
            placeable_id=(raw.get('placeable_id') if isinstance(raw, dict) else raw[2]),
            direction_index=(raw.get('direction_index') if isinstance(raw, dict) else raw[3])
        )
