# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerHousingDesc:
    secondary_knowledge_id: int = 0
    rank: int = 0
    name: str = ''
    template_building_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerHousingDesc':
        if raw is None:
            return cls()
        return cls(
            secondary_knowledge_id=(raw.get('secondary_knowledge_id') if isinstance(raw, dict) else raw[0]),
            rank=(raw.get('rank') if isinstance(raw, dict) else raw[1]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[2]),
            template_building_id=(raw.get('template_building_id') if isinstance(raw, dict) else raw[3])
        )
