# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerHousingState:
    entity_id: int = 0
    entrance_building_entity_id: int = 0
    network_entity_id: int = 0
    exit_portal_entity_id: int = 0
    rank: int = 0
    locked_until: int = 0
    is_empty: bool = False
    region_index: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerHousingState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            entrance_building_entity_id=(raw.get('entrance_building_entity_id') if isinstance(raw, dict) else raw[1]),
            network_entity_id=(raw.get('network_entity_id') if isinstance(raw, dict) else raw[2]),
            exit_portal_entity_id=(raw.get('exit_portal_entity_id') if isinstance(raw, dict) else raw[3]),
            rank=(raw.get('rank') if isinstance(raw, dict) else raw[4]),
            locked_until=((raw.get('locked_until') if isinstance(raw, dict) else raw[5])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('locked_until') if isinstance(raw, dict) else raw[5]), dict) else ((raw.get('locked_until') if isinstance(raw, dict) else raw[5])[0] if isinstance((raw.get('locked_until') if isinstance(raw, dict) else raw[5]), list) else (raw.get('locked_until') if isinstance(raw, dict) else raw[5]))),
            is_empty=(raw.get('is_empty') if isinstance(raw, dict) else raw[6]),
            region_index=(raw.get('region_index') if isinstance(raw, dict) else raw[7])
        )
