# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .player_action_layer import PlayerActionLayer



@dataclass
class PlayerActionDesc:
    action_type_id: int = 0
    layer: PlayerActionLayer = 0
    allowed_concurrent_action_ids: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'PlayerActionDesc':
        if raw is None:
            return cls()
        return cls(
            action_type_id=(raw.get('action_type_id') if isinstance(raw, dict) else raw[0]),
            layer=PlayerActionLayer.from_row((raw.get('layer') if isinstance(raw, dict) else raw[1])),
            allowed_concurrent_action_ids=[_item for _item in ((raw.get('allowed_concurrent_action_ids') if isinstance(raw, dict) else raw[2]) or [])]
        )
