# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerTimestampState:
    entity_id: int = 0
    timestamp: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerTimestampState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            timestamp=((raw.get('timestamp') if isinstance(raw, dict) else raw[1])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('timestamp') if isinstance(raw, dict) else raw[1]), dict) else (raw.get('timestamp') if isinstance(raw, dict) else raw[1]))
        )
