# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .player_vote_answer import PlayerVoteAnswer
from .player_vote_type import PlayerVoteType



@dataclass
class PlayerVoteState:
    entity_id: int = 0
    vote_type: PlayerVoteType = 0
    initiator_entity_id: int = 0
    participants_entity_id: list = field(default_factory=list)
    answers: list = field(default_factory=list)
    initiator_name: str = ''
    pass_threshold: float = 0.0
    outcome: PlayerVoteAnswer = 0
    argument1: int = 0
    argument2: int = 0
    outcome_str: str = ''

    @classmethod
    def from_row(cls, raw) -> 'PlayerVoteState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            vote_type=PlayerVoteType.from_row((raw.get('vote_type') if isinstance(raw, dict) else raw[1])),
            initiator_entity_id=(raw.get('initiator_entity_id') if isinstance(raw, dict) else raw[2]),
            participants_entity_id=[_item for _item in ((raw.get('participants_entity_id') if isinstance(raw, dict) else raw[3]) or [])],
            answers=[PlayerVoteAnswer.from_row(_item) for _item in ((raw.get('answers') if isinstance(raw, dict) else raw[4]) or [])],
            initiator_name=(raw.get('initiator_name') if isinstance(raw, dict) else raw[5]),
            pass_threshold=(raw.get('pass_threshold') if isinstance(raw, dict) else raw[6]),
            outcome=PlayerVoteAnswer.from_row((raw.get('outcome') if isinstance(raw, dict) else raw[7])),
            argument1=(raw.get('argument1') if isinstance(raw, dict) else raw[8]),
            argument2=(raw.get('argument2') if isinstance(raw, dict) else raw[9]),
            outcome_str=(raw.get('outcome_str') if isinstance(raw, dict) else raw[10])
        )
