# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerShardState:
    entity_id: int = 0
    shards: int = 0
    last_shard_claim: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerShardState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            shards=(raw.get('shards') if isinstance(raw, dict) else raw[1]),
            last_shard_claim=(raw.get('last_shard_claim') if isinstance(raw, dict) else raw[2])
        )
