# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_stack import ItemStack



@dataclass
class Pocket:
    volume: int = 0
    contents: ItemStack | None = None
    locked: bool = False

    @classmethod
    def from_row(cls, raw) -> 'Pocket':
        if raw is None:
            return cls()
        return cls(
            volume=(raw.get('volume') if isinstance(raw, dict) else raw[0]),
            contents=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (ItemStack.from_row(_v[1])))((raw.get('contents') if isinstance(raw, dict) else raw[1])),
            locked=(raw.get('locked') if isinstance(raw, dict) else raw[2])
        )
