# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .premium_service_type import PremiumServiceType



@dataclass
class PremiumServiceDesc:
    id: int = 0
    name: str = ''
    description: str = ''
    image_address: str = ''
    service_type: PremiumServiceType = 0
    price: int = 0
    base_price: int = 0
    is_enabled: bool = False

    @classmethod
    def from_row(cls, raw) -> 'PremiumServiceDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            description=(raw.get('description') if isinstance(raw, dict) else raw[2]),
            image_address=(raw.get('image_address') if isinstance(raw, dict) else raw[3]),
            service_type=PremiumServiceType.from_row((raw.get('service_type') if isinstance(raw, dict) else raw[4])),
            price=(raw.get('price') if isinstance(raw, dict) else raw[5]),
            base_price=(raw.get('base_price') if isinstance(raw, dict) else raw[6]),
            is_enabled=(raw.get('is_enabled') if isinstance(raw, dict) else raw[7])
        )
