# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PreviousEmpireNameState:
    emperor_identity: str = 0
    empire_name: str = ''
    empire_lower_case_name: str = ''

    @classmethod
    def from_row(cls, raw) -> 'PreviousEmpireNameState':
        if raw is None:
            return cls()
        return cls(
            emperor_identity=((raw.get('emperor_identity') if isinstance(raw, dict) else raw[0])['__identity__'] if isinstance((raw.get('emperor_identity') if isinstance(raw, dict) else raw[0]), dict) else ((raw.get('emperor_identity') if isinstance(raw, dict) else raw[0])[0] if isinstance((raw.get('emperor_identity') if isinstance(raw, dict) else raw[0]), list) else (raw.get('emperor_identity') if isinstance(raw, dict) else raw[0]))),
            empire_name=(raw.get('empire_name') if isinstance(raw, dict) else raw[1]),
            empire_lower_case_name=(raw.get('empire_lower_case_name') if isinstance(raw, dict) else raw[2])
        )
