# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_stack import ItemStack



@dataclass
class ProjectSiteState:
    entity_id: int = 0
    construction_recipe_id: int = 0
    resource_placement_recipe_id: int = 0
    items: list = field(default_factory=list)
    cargos: list = field(default_factory=list)
    progress: int = 0
    last_crit_outcome: int = 0
    owner_id: int = 0
    direction: int = 0
    last_hit_timestamp: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ProjectSiteState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            construction_recipe_id=(raw.get('construction_recipe_id') if isinstance(raw, dict) else raw[1]),
            resource_placement_recipe_id=(raw.get('resource_placement_recipe_id') if isinstance(raw, dict) else raw[2]),
            items=[ItemStack.from_row(_item) for _item in ((raw.get('items') if isinstance(raw, dict) else raw[3]) or [])],
            cargos=[ItemStack.from_row(_item) for _item in ((raw.get('cargos') if isinstance(raw, dict) else raw[4]) or [])],
            progress=(raw.get('progress') if isinstance(raw, dict) else raw[5]),
            last_crit_outcome=(raw.get('last_crit_outcome') if isinstance(raw, dict) else raw[6]),
            owner_id=(raw.get('owner_id') if isinstance(raw, dict) else raw[7]),
            direction=(raw.get('direction') if isinstance(raw, dict) else raw[8]),
            last_hit_timestamp=((raw.get('last_hit_timestamp') if isinstance(raw, dict) else raw[9])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('last_hit_timestamp') if isinstance(raw, dict) else raw[9]), dict) else (raw.get('last_hit_timestamp') if isinstance(raw, dict) else raw[9]))
        )
