# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ProspectingState:
    entity_id: int = 0
    prospecting_id: int = 0
    crumb_trail_entity_id: int = 0
    completed_steps: int = 0
    ongoing_step: int = 0
    total_steps: int = 0
    next_crumb_angle: list = field(default_factory=list)
    last_prospection_timestamp: int = 0
    contribution: int = 0
    to_next_node: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'ProspectingState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            prospecting_id=(raw.get('prospecting_id') if isinstance(raw, dict) else raw[1]),
            crumb_trail_entity_id=(raw.get('crumb_trail_entity_id') if isinstance(raw, dict) else raw[2]),
            completed_steps=(raw.get('completed_steps') if isinstance(raw, dict) else raw[3]),
            ongoing_step=(raw.get('ongoing_step') if isinstance(raw, dict) else raw[4]),
            total_steps=(raw.get('total_steps') if isinstance(raw, dict) else raw[5]),
            next_crumb_angle=[_item for _item in ((raw.get('next_crumb_angle') if isinstance(raw, dict) else raw[6]) or [])],
            last_prospection_timestamp=((raw.get('last_prospection_timestamp') if isinstance(raw, dict) else raw[7])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('last_prospection_timestamp') if isinstance(raw, dict) else raw[7]), dict) else ((raw.get('last_prospection_timestamp') if isinstance(raw, dict) else raw[7])[0] if isinstance((raw.get('last_prospection_timestamp') if isinstance(raw, dict) else raw[7]), list) else (raw.get('last_prospection_timestamp') if isinstance(raw, dict) else raw[7]))),
            contribution=(raw.get('contribution') if isinstance(raw, dict) else raw[8]),
            to_next_node=(raw.get('to_next_node') if isinstance(raw, dict) else raw[9])
        )
