# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class RegionDestroySiegeEngineMsg:
    deployable_entity_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'RegionDestroySiegeEngineMsg':
        if raw is None:
            return cls()
        return cls(
            deployable_entity_id=(raw.get('deployable_entity_id') if isinstance(raw, dict) else raw[0])
        )
