# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ReplaceIdentityMsg:
    old_identity: str = 0
    new_identity: str = 0

    @classmethod
    def from_row(cls, raw) -> 'ReplaceIdentityMsg':
        if raw is None:
            return cls()
        return cls(
            old_identity=((raw.get('old_identity') if isinstance(raw, dict) else raw[0])['__identity__'] if isinstance((raw.get('old_identity') if isinstance(raw, dict) else raw[0]), dict) else ((raw.get('old_identity') if isinstance(raw, dict) else raw[0])[0] if isinstance((raw.get('old_identity') if isinstance(raw, dict) else raw[0]), list) else (raw.get('old_identity') if isinstance(raw, dict) else raw[0]))),
            new_identity=((raw.get('new_identity') if isinstance(raw, dict) else raw[1])['__identity__'] if isinstance((raw.get('new_identity') if isinstance(raw, dict) else raw[1]), dict) else ((raw.get('new_identity') if isinstance(raw, dict) else raw[1])[0] if isinstance((raw.get('new_identity') if isinstance(raw, dict) else raw[1]), list) else (raw.get('new_identity') if isinstance(raw, dict) else raw[1])))
        )
