# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ResourceCount:
    resource_id: int = 0
    num_in_world: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ResourceCount':
        if raw is None:
            return cls()
        return cls(
            resource_id=(raw.get('resource_id') if isinstance(raw, dict) else raw[0]),
            num_in_world=(raw.get('num_in_world') if isinstance(raw, dict) else raw[1])
        )
