# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class SingleResourceToClumpDesc:
    resource_id: int = 0
    clump_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'SingleResourceToClumpDesc':
        if raw is None:
            return cls()
        return cls(
            resource_id=(raw.get('resource_id') if isinstance(raw, dict) else raw[0]),
            clump_id=(raw.get('clump_id') if isinstance(raw, dict) else raw[1])
        )
