# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_stack import ItemStack



@dataclass
class StageRewardsDesc:
    id: int = 0
    chain_desc_id: int = 0
    rewards: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'StageRewardsDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            chain_desc_id=(raw.get('chain_desc_id') if isinstance(raw, dict) else raw[1]),
            rewards=[ItemStack.from_row(_item) for _item in ((raw.get('rewards') if isinstance(raw, dict) else raw[2]) or [])]
        )
