# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class StaminaState:
    entity_id: int = 0
    last_stamina_decrease_timestamp: int = 0
    stamina: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'StaminaState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            last_stamina_decrease_timestamp=((raw.get('last_stamina_decrease_timestamp') if isinstance(raw, dict) else raw[1])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('last_stamina_decrease_timestamp') if isinstance(raw, dict) else raw[1]), dict) else ((raw.get('last_stamina_decrease_timestamp') if isinstance(raw, dict) else raw[1])[0] if isinstance((raw.get('last_stamina_decrease_timestamp') if isinstance(raw, dict) else raw[1]), list) else (raw.get('last_stamina_decrease_timestamp') if isinstance(raw, dict) else raw[1]))),
            stamina=(raw.get('stamina') if isinstance(raw, dict) else raw[2])
        )
