# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class TargetingMatrixDesc:
    id: int = 0
    interact: bool = False
    categories_attacked: list = field(default_factory=list)
    categories_weights: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'TargetingMatrixDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            interact=(raw.get('interact') if isinstance(raw, dict) else raw[1]),
            categories_attacked=[_item for _item in ((raw.get('categories_attacked') if isinstance(raw, dict) else raw[2]) or [])],
            categories_weights=[_item for _item in ((raw.get('categories_weights') if isinstance(raw, dict) else raw[3]) or [])]
        )
