# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class TeleportLocationType(IntEnum):
    BIRTHLOCATION = 0
    TRADINGPOST = 1
    HOMELOCATION = 2
    CUSTOMLOCATION = 3
    WAYSTONE = 4


    @classmethod
    def from_row(cls, raw) -> 'TeleportLocationType':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for BirthLocation
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse TeleportLocationType from {raw!r}')
