# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .ability_type_enum import AbilityTypeEnum
from .buff_category import BuffCategory
from .chat_channel import ChatChannel
from .permission import Permission
from .permission_group import PermissionGroup
from .progressive_action_status import ProgressiveActionStatus
from .skill_type import SkillType
from .surface_type import SurfaceType



@dataclass
class TheGreatPlaceHolderTable:
    placeholder_id: int = 0
    placeholder_skill_type: SkillType = 0
    placeholder_buff_category: BuffCategory = 0
    placeholder: ProgressiveActionStatus = 0
    placeholder_water_body_type: SurfaceType = 0
    chat_channel: ChatChannel = 0
    permission: Permission = 0
    permission_group: PermissionGroup = 0
    ability_type: AbilityTypeEnum = 0

    @classmethod
    def from_row(cls, raw) -> 'TheGreatPlaceHolderTable':
        if raw is None:
            return cls()
        return cls(
            placeholder_id=(raw.get('placeholder_id') if isinstance(raw, dict) else raw[0]),
            placeholder_skill_type=SkillType.from_row((raw.get('placeholder_skill_type') if isinstance(raw, dict) else raw[1])),
            placeholder_buff_category=BuffCategory.from_row((raw.get('placeholder_buff_category') if isinstance(raw, dict) else raw[2])),
            placeholder=ProgressiveActionStatus.from_row((raw.get('placeholder') if isinstance(raw, dict) else raw[3])),
            placeholder_water_body_type=SurfaceType.from_row((raw.get('placeholder_water_body_type') if isinstance(raw, dict) else raw[4])),
            chat_channel=ChatChannel.from_row((raw.get('chat_channel') if isinstance(raw, dict) else raw[5])),
            permission=Permission.from_row((raw.get('permission') if isinstance(raw, dict) else raw[6])),
            permission_group=PermissionGroup.from_row((raw.get('permission_group') if isinstance(raw, dict) else raw[7])),
            ability_type=AbilityTypeEnum.from_row((raw.get('ability_type') if isinstance(raw, dict) else raw[8]))
        )
