# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ToolRequirement:
    tool_type: int = 0
    level: int = 0
    power: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ToolRequirement':
        if raw is None:
            return cls()
        return cls(
            tool_type=(raw.get('tool_type') if isinstance(raw, dict) else raw[0]),
            level=(raw.get('level') if isinstance(raw, dict) else raw[1]),
            power=(raw.get('power') if isinstance(raw, dict) else raw[2])
        )
