# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_stack import ItemStack



@dataclass
class TradePocket:
    inventory_pocket_index: int = 0
    inventory_index: int = 0
    contents: ItemStack = 0

    @classmethod
    def from_row(cls, raw) -> 'TradePocket':
        if raw is None:
            return cls()
        return cls(
            inventory_pocket_index=(raw.get('inventory_pocket_index') if isinstance(raw, dict) else raw[0]),
            inventory_index=(raw.get('inventory_index') if isinstance(raw, dict) else raw[1]),
            contents=ItemStack.from_row((raw.get('contents') if isinstance(raw, dict) else raw[2]))
        )
