# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class TranslationCorrections:
    id: int = 0
    string_index: int = 0
    player_entity_id: int = 0
    lang: str = ''
    translation: str = ''

    @classmethod
    def from_row(cls, raw) -> 'TranslationCorrections':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            string_index=(raw.get('string_index') if isinstance(raw, dict) else raw[1]),
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[2]),
            lang=(raw.get('lang') if isinstance(raw, dict) else raw[3]),
            translation=(raw.get('translation') if isinstance(raw, dict) else raw[4])
        )
