# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_stack import ItemStack
from .level_requirement import LevelRequirement
from .npc_type import NpcType



@dataclass
class TravelerTradeOrderDesc:
    id: int = 0
    starting_stock: int = 0
    always_offered: bool = False
    traveler: NpcType = 0
    offer_items: list = field(default_factory=list)
    offer_cargo_id: list = field(default_factory=list)
    required_items: list = field(default_factory=list)
    required_cargo_id: list = field(default_factory=list)
    level_requirements: list = field(default_factory=list)
    achievement_requirements: list = field(default_factory=list)
    hide_if_requirements_are_not_met: bool = False
    required_knowledges: list = field(default_factory=list)
    hide_without_required_knowledge: bool = False
    blocking_knowledges: list = field(default_factory=list)
    hide_with_blocking_knowledges: bool = False

    @classmethod
    def from_row(cls, raw) -> 'TravelerTradeOrderDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            starting_stock=(raw.get('starting_stock') if isinstance(raw, dict) else raw[1]),
            always_offered=(raw.get('always_offered') if isinstance(raw, dict) else raw[2]),
            traveler=NpcType.from_row((raw.get('traveler') if isinstance(raw, dict) else raw[3])),
            offer_items=[ItemStack.from_row(_item) for _item in ((raw.get('offer_items') if isinstance(raw, dict) else raw[4]) or [])],
            offer_cargo_id=[_item for _item in ((raw.get('offer_cargo_id') if isinstance(raw, dict) else raw[5]) or [])],
            required_items=[ItemStack.from_row(_item) for _item in ((raw.get('required_items') if isinstance(raw, dict) else raw[6]) or [])],
            required_cargo_id=[_item for _item in ((raw.get('required_cargo_id') if isinstance(raw, dict) else raw[7]) or [])],
            level_requirements=[LevelRequirement.from_row(_item) for _item in ((raw.get('level_requirements') if isinstance(raw, dict) else raw[8]) or [])],
            achievement_requirements=[_item for _item in ((raw.get('achievement_requirements') if isinstance(raw, dict) else raw[9]) or [])],
            hide_if_requirements_are_not_met=(raw.get('hide_if_requirements_are_not_met') if isinstance(raw, dict) else raw[10]),
            required_knowledges=[_item for _item in ((raw.get('required_knowledges') if isinstance(raw, dict) else raw[11]) or [])],
            hide_without_required_knowledge=(raw.get('hide_without_required_knowledge') if isinstance(raw, dict) else raw[12]),
            blocking_knowledges=[_item for _item in ((raw.get('blocking_knowledges') if isinstance(raw, dict) else raw[13]) or [])],
            hide_with_blocking_knowledges=(raw.get('hide_with_blocking_knowledges') if isinstance(raw, dict) else raw[14])
        )
