# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .capped_level_requirement import CappedLevelRequirement
from .experience_stack_f32 import ExperienceStackF32
from .item_stack import ItemStack



@dataclass
class TravelerTaskDesc:
    id: int = 0
    level_requirement: CappedLevelRequirement = 0
    required_items: list = field(default_factory=list)
    rewarded_items: list = field(default_factory=list)
    rewarded_experience: ExperienceStackF32 = 0
    description: str = ''

    @classmethod
    def from_row(cls, raw) -> 'TravelerTaskDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            level_requirement=CappedLevelRequirement.from_row((raw.get('level_requirement') if isinstance(raw, dict) else raw[1])),
            required_items=[ItemStack.from_row(_item) for _item in ((raw.get('required_items') if isinstance(raw, dict) else raw[2]) or [])],
            rewarded_items=[ItemStack.from_row(_item) for _item in ((raw.get('rewarded_items') if isinstance(raw, dict) else raw[3]) or [])],
            rewarded_experience=ExperienceStackF32.from_row((raw.get('rewarded_experience') if isinstance(raw, dict) else raw[4])),
            description=(raw.get('description') if isinstance(raw, dict) else raw[5])
        )
