# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class TraversalSettings(IntEnum):
    NONE = 0
    FINISHMOVE = 1
    WALK = 2
    STEPUP = 3
    HOIST1 = 4
    DOWN1 = 5
    WALKSWIMTRANSITION = 6
    SWIMHOIST = 7
    DOWN1SWIM = 8


    @classmethod
    def from_row(cls, raw) -> 'TraversalSettings':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for None
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse TraversalSettings from {raw!r}')
