# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .user_moderation_policy import UserModerationPolicy



@dataclass
class UserModerationState:
    entity_id: int = 0
    target_identity: object = 0
    created_by_identity: object = 0
    user_moderation_policy: UserModerationPolicy = 0
    created_time: object = 0
    expiration_time: object = 0

    @classmethod
    def from_row(cls, raw) -> 'UserModerationState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            target_identity=(raw.get('target_identity') if isinstance(raw, dict) else raw[1]),
            created_by_identity=(raw.get('created_by_identity') if isinstance(raw, dict) else raw[2]),
            user_moderation_policy=UserModerationPolicy.from_row((raw.get('user_moderation_policy') if isinstance(raw, dict) else raw[3])),
            created_time=(raw.get('created_time') if isinstance(raw, dict) else raw[4]),
            expiration_time=(raw.get('expiration_time') if isinstance(raw, dict) else raw[5])
        )
