# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .user_moderation_policy import UserModerationPolicy



@dataclass
class UserModerationCreateUserPolicyRequest:
    target_identity: str = 0
    user_moderation_policy: UserModerationPolicy = 0
    duration_ms: int = 0

    @classmethod
    def from_row(cls, raw) -> 'UserModerationCreateUserPolicyRequest':
        if raw is None:
            return cls()
        return cls(
            target_identity=((raw.get('target_identity') if isinstance(raw, dict) else raw[0])['__identity__'] if isinstance((raw.get('target_identity') if isinstance(raw, dict) else raw[0]), dict) else ((raw.get('target_identity') if isinstance(raw, dict) else raw[0])[0] if isinstance((raw.get('target_identity') if isinstance(raw, dict) else raw[0]), list) else (raw.get('target_identity') if isinstance(raw, dict) else raw[0]))),
            user_moderation_policy=UserModerationPolicy.from_row((raw.get('user_moderation_policy') if isinstance(raw, dict) else raw[1])),
            duration_ms=(raw.get('duration_ms') if isinstance(raw, dict) else raw[2])
        )
