# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class VaultCollectible:
    id: int = 0
    activated: bool = False
    count: int = 0

    @classmethod
    def from_row(cls, raw) -> 'VaultCollectible':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            activated=(raw.get('activated') if isinstance(raw, dict) else raw[1]),
            count=(raw.get('count') if isinstance(raw, dict) else raw[2])
        )
