# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class VfxAttachmentPoint(IntEnum):
    ORIGIN = 0
    OVERHEAD = 1
    HEAD = 2
    CHEST = 3
    MAINHAND = 4
    OFFHAND = 5
    BOTHHANDS = 6
    FEET = 7


    @classmethod
    def from_row(cls, raw) -> 'VfxAttachmentPoint':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for Origin
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse VfxAttachmentPoint from {raw!r}')
