# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .visibility_type import VisibilityType



@dataclass
class VisibilityState:
    entity_id: int = 0
    visibility: VisibilityType = 0

    @classmethod
    def from_row(cls, raw) -> 'VisibilityState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            visibility=VisibilityType.from_row((raw.get('visibility') if isinstance(raw, dict) else raw[1]))
        )
