# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class WallDesc:
    building_id: int = 0
    large_post_asset_name: str = ''
    small_post_asset_name: str = ''
    wall_asset_names: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'WallDesc':
        if raw is None:
            return cls()
        return cls(
            building_id=(raw.get('building_id') if isinstance(raw, dict) else raw[0]),
            large_post_asset_name=(raw.get('large_post_asset_name') if isinstance(raw, dict) else raw[1]),
            small_post_asset_name=(raw.get('small_post_asset_name') if isinstance(raw, dict) else raw[2]),
            wall_asset_names=[_item for _item in ((raw.get('wall_asset_names') if isinstance(raw, dict) else raw[3]) or [])]
        )
