# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class WeaponDesc:
    item_id: int = 0
    tier: int = 0
    weapon_type: int = 0
    min_damage: int = 0
    max_damage: int = 0
    cooldown: float = 0.0
    stamina_use_multiplier: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'WeaponDesc':
        if raw is None:
            return cls()
        return cls(
            item_id=(raw.get('item_id') if isinstance(raw, dict) else raw[0]),
            tier=(raw.get('tier') if isinstance(raw, dict) else raw[1]),
            weapon_type=(raw.get('weapon_type') if isinstance(raw, dict) else raw[2]),
            min_damage=(raw.get('min_damage') if isinstance(raw, dict) else raw[3]),
            max_damage=(raw.get('max_damage') if isinstance(raw, dict) else raw[4]),
            cooldown=(raw.get('cooldown') if isinstance(raw, dict) else raw[5]),
            stamina_use_multiplier=(raw.get('stamina_use_multiplier') if isinstance(raw, dict) else raw[6])
        )
