# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class WeaponTypeDesc:
    id: int = 0
    name: str = ''
    hunting: bool = False

    @classmethod
    def from_row(cls, raw) -> 'WeaponTypeDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            hunting=(raw.get('hunting') if isinstance(raw, dict) else raw[2])
        )
