# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .action_log_data import ActionLogData
from .action_log_subject_type import ActionLogSubjectType



@dataclass
class ActionLogState:
    id: int = 0
    object_entity_id: int = 0
    subject_entity_id: int = 0
    subject_name: str = ''
    subject_type: ActionLogSubjectType = 0
    data: ActionLogData = 0
    timestamp: int = 0
    days_since_epoch: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ActionLogState':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            object_entity_id=(raw.get('object_entity_id') if isinstance(raw, dict) else raw[1]),
            subject_entity_id=(raw.get('subject_entity_id') if isinstance(raw, dict) else raw[2]),
            subject_name=(raw.get('subject_name') if isinstance(raw, dict) else raw[3]),
            subject_type=ActionLogSubjectType.from_row((raw.get('subject_type') if isinstance(raw, dict) else raw[4])),
            data=ActionLogData.from_row((raw.get('data') if isinstance(raw, dict) else raw[5])),
            timestamp=((raw.get('timestamp') if isinstance(raw, dict) else raw[6])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('timestamp') if isinstance(raw, dict) else raw[6]), dict) else ((raw.get('timestamp') if isinstance(raw, dict) else raw[6])[0] if isinstance((raw.get('timestamp') if isinstance(raw, dict) else raw[6]), list) else (raw.get('timestamp') if isinstance(raw, dict) else raw[6]))),
            days_since_epoch=(raw.get('days_since_epoch') if isinstance(raw, dict) else raw[7])
        )
