# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .online_timestamp import OnlineTimestamp



@dataclass
class ActiveBuff:
    buff_id: int = 0
    buff_start_timestamp: OnlineTimestamp = 0
    buff_duration: int = 0
    values: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'ActiveBuff':
        if raw is None:
            return cls()
        return cls(
            buff_id=(raw.get('buff_id') if isinstance(raw, dict) else raw[0]),
            buff_start_timestamp=OnlineTimestamp.from_row((raw.get('buff_start_timestamp') if isinstance(raw, dict) else raw[1])),
            buff_duration=(raw.get('buff_duration') if isinstance(raw, dict) else raw[2]),
            values=[_item for _item in ((raw.get('values') if isinstance(raw, dict) else raw[3]) or [])]
        )
