# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .action_cooldown import ActionCooldown



@dataclass
class ActionState:
    entity_id: int = 0
    owner_entity_id: int = 0
    action_id: int = 0
    cooldown: ActionCooldown = 0

    @classmethod
    def from_row(cls, raw) -> 'ActionState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            owner_entity_id=(raw.get('owner_entity_id') if isinstance(raw, dict) else raw[1]),
            action_id=(raw.get('action_id') if isinstance(raw, dict) else raw[2]),
            cooldown=ActionCooldown.from_row((raw.get('cooldown') if isinstance(raw, dict) else raw[3]))
        )
