# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_stack import ItemStack



@dataclass
class ActionLogDataSpaceAllocator:
    item1: ItemStack = 0
    item2: ItemStack = 0
    val1: int = 0
    val2: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ActionLogDataSpaceAllocator':
        if raw is None:
            return cls()
        return cls(
            item1=ItemStack.from_row((raw.get('item1') if isinstance(raw, dict) else raw[0])),
            item2=ItemStack.from_row((raw.get('item2') if isinstance(raw, dict) else raw[1])),
            val1=(raw.get('val1') if isinstance(raw, dict) else raw[2]),
            val2=(raw.get('val2') if isinstance(raw, dict) else raw[3])
        )
