# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class AdminBroadcastMessageMsg:
    title: str = ''
    message: str = ''
    sign_out: bool = False

    @classmethod
    def from_row(cls, raw) -> 'AdminBroadcastMessageMsg':
        if raw is None:
            return cls()
        return cls(
            title=(raw.get('title') if isinstance(raw, dict) else raw[0]),
            message=(raw.get('message') if isinstance(raw, dict) else raw[1]),
            sign_out=(raw.get('sign_out') if isinstance(raw, dict) else raw[2])
        )
