# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_float import OffsetCoordinatesFloat



@dataclass
class AIDebugState:
    entity_id: int = 0
    target_entity_id: int = 0
    current_destination: OffsetCoordinatesFloat = 0
    current_position: OffsetCoordinatesFloat = 0
    target_position: OffsetCoordinatesFloat = 0
    dp: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'AIDebugState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            target_entity_id=(raw.get('target_entity_id') if isinstance(raw, dict) else raw[1]),
            current_destination=OffsetCoordinatesFloat.from_row((raw.get('current_destination') if isinstance(raw, dict) else raw[2])),
            current_position=OffsetCoordinatesFloat.from_row((raw.get('current_position') if isinstance(raw, dict) else raw[3])),
            target_position=OffsetCoordinatesFloat.from_row((raw.get('target_position') if isinstance(raw, dict) else raw[4])),
            dp=(raw.get('dp') if isinstance(raw, dict) else raw[5])
        )
