# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .alert_type import AlertType



@dataclass
class AlertState:
    entity_id: int = 0
    player_entity_id: int = 0
    target_entity_id: int = 0
    end_timestamp: int = 0
    alert_type: AlertType = 0

    @classmethod
    def from_row(cls, raw) -> 'AlertState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[1]),
            target_entity_id=(raw.get('target_entity_id') if isinstance(raw, dict) else raw[2]),
            end_timestamp=((raw.get('end_timestamp') if isinstance(raw, dict) else raw[3])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('end_timestamp') if isinstance(raw, dict) else raw[3]), dict) else ((raw.get('end_timestamp') if isinstance(raw, dict) else raw[3])[0] if isinstance((raw.get('end_timestamp') if isinstance(raw, dict) else raw[3]), list) else (raw.get('end_timestamp') if isinstance(raw, dict) else raw[3]))),
            alert_type=AlertType.from_row((raw.get('alert_type') if isinstance(raw, dict) else raw[4]))
        )
