# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class AlertType(IntEnum):
    NONE = 0
    EVICTIONWARNING = 1
    EVICTIONSTATEMENT = 2
    DISMISSABLETEST = 3
    OUTOFSUPPLIES = 4
    OUTOFSUPPLIESINONETICK = 5
    OUTOFSUPPLIESINTWELVETICKS = 6
    NEWLOSTITEMS = 7
    COOWNERCLAIMOWNERSHIPTRANSFERIN24H = 8
    COOWNERCLAIMOWNERSHIPTRANSFER = 9
    OFFICERCLAIMOWNERSHIPTRANSFER = 10
    MEMBERCLAIMOWNERSHIPTRANSFER = 11


    @classmethod
    def from_row(cls, raw) -> 'AlertType':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for None
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse AlertType from {raw!r}')
