# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class AlertDesc:
    alert_type: int = 0
    show_timer: bool = False
    duration: float = 0.0
    header: str = ''
    body: str = ''

    @classmethod
    def from_row(cls, raw) -> 'AlertDesc':
        if raw is None:
            return cls()
        return cls(
            alert_type=(raw.get('alert_type') if isinstance(raw, dict) else raw[0]),
            show_timer=(raw.get('show_timer') if isinstance(raw, dict) else raw[1]),
            duration=(raw.get('duration') if isinstance(raw, dict) else raw[2]),
            header=(raw.get('header') if isinstance(raw, dict) else raw[3]),
            body=(raw.get('body') if isinstance(raw, dict) else raw[4])
        )
