# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class AttackEvent:
    attacker_entity_id: int = 0
    defender_entity_id: int = 0
    combat_action_id: int = 0
    damage: int = 0
    is_crit: bool = False
    is_dodge: bool = False

    @classmethod
    def from_row(cls, raw) -> 'AttackEvent':
        if raw is None:
            return cls()
        return cls(
            attacker_entity_id=(raw.get('attacker_entity_id') if isinstance(raw, dict) else raw[0]),
            defender_entity_id=(raw.get('defender_entity_id') if isinstance(raw, dict) else raw[1]),
            combat_action_id=(raw.get('combat_action_id') if isinstance(raw, dict) else raw[2]),
            damage=(raw.get('damage') if isinstance(raw, dict) else raw[3]),
            is_crit=(raw.get('is_crit') if isinstance(raw, dict) else raw[4]),
            is_dodge=(raw.get('is_dodge') if isinstance(raw, dict) else raw[5])
        )
