# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class AuctionListingState:
    entity_id: int = 0
    owner_entity_id: int = 0
    claim_entity_id: int = 0
    item_id: int = 0
    item_type: int = 0
    price_threshold: int = 0
    quantity: int = 0
    timestamp: int = 0
    stored_coins: int = 0

    @classmethod
    def from_row(cls, raw) -> 'AuctionListingState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            owner_entity_id=(raw.get('owner_entity_id') if isinstance(raw, dict) else raw[1]),
            claim_entity_id=(raw.get('claim_entity_id') if isinstance(raw, dict) else raw[2]),
            item_id=(raw.get('item_id') if isinstance(raw, dict) else raw[3]),
            item_type=(raw.get('item_type') if isinstance(raw, dict) else raw[4]),
            price_threshold=(raw.get('price_threshold') if isinstance(raw, dict) else raw[5]),
            quantity=(raw.get('quantity') if isinstance(raw, dict) else raw[6]),
            timestamp=((raw.get('timestamp') if isinstance(raw, dict) else raw[7])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('timestamp') if isinstance(raw, dict) else raw[7]), dict) else ((raw.get('timestamp') if isinstance(raw, dict) else raw[7])[0] if isinstance((raw.get('timestamp') if isinstance(raw, dict) else raw[7]), list) else (raw.get('timestamp') if isinstance(raw, dict) else raw[7]))),
            stored_coins=(raw.get('stored_coins') if isinstance(raw, dict) else raw[8])
        )
