# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .small_hex_tile_message import SmallHexTileMessage



@dataclass
class BankState:
    building_entity_id: int = 0
    claim_entity_id: int = 0
    coordinates: SmallHexTileMessage = 0

    @classmethod
    def from_row(cls, raw) -> 'BankState':
        if raw is None:
            return cls()
        return cls(
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[0]),
            claim_entity_id=(raw.get('claim_entity_id') if isinstance(raw, dict) else raw[1]),
            coordinates=SmallHexTileMessage.from_row((raw.get('coordinates') if isinstance(raw, dict) else raw[2]))
        )
