# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class Biome(IntEnum):
    DEV = 0
    CALMFOREST = 1
    PINEWOODS = 2
    SNOWYPEAKS = 3
    BREEZYPLAINS = 4
    AUTUMNFOREST = 5
    TUNDRA = 6
    DESERT = 7
    SWAMP = 8
    CANYON = 9
    OCEAN = 10
    SAFEMEADOWS = 11
    CAVE = 12
    JUNGLE = 13
    SAPWOODS = 14


    @classmethod
    def from_row(cls, raw) -> 'Biome':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for Dev
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse Biome from {raw!r}')
