# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class BuffCategory(IntEnum):
    NONE = 0
    GENERIC = 1
    RESTED = 2
    REZSICKNESSSHORTTERM = 3
    REZSICKNESSLONGTERM = 4
    INNERLIGHT = 5
    DARKNESS = 6
    CARRYCARGO = 7
    FREEZING = 8
    OVERHEATING = 9
    FRIENDWARPDEBUFF = 10
    STARVING = 11
    ELEVATORSICKNESS = 12
    NEARBYFLAME = 13
    SPRINT = 14


    @classmethod
    def from_row(cls, raw) -> 'BuffCategory':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for None
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse BuffCategory from {raw!r}')
