# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .claim_type import ClaimType



@dataclass
class BuildingClaimDesc:
    building_id: int = 0
    claim_type: ClaimType = 0
    radius: int = 0
    tier: int = 0

    @classmethod
    def from_row(cls, raw) -> 'BuildingClaimDesc':
        if raw is None:
            return cls()
        return cls(
            building_id=(raw.get('building_id') if isinstance(raw, dict) else raw[0]),
            claim_type=ClaimType.from_row((raw.get('claim_type') if isinstance(raw, dict) else raw[1])),
            radius=(raw.get('radius') if isinstance(raw, dict) else raw[2]),
            tier=(raw.get('tier') if isinstance(raw, dict) else raw[3])
        )
