# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class CappedLevelRequirement:
    skill_id: int = 0
    min_level: int = 0
    max_level: int = 0

    @classmethod
    def from_row(cls, raw) -> 'CappedLevelRequirement':
        if raw is None:
            return cls()
        return cls(
            skill_id=(raw.get('skill_id') if isinstance(raw, dict) else raw[0]),
            min_level=(raw.get('min_level') if isinstance(raw, dict) else raw[1]),
            max_level=(raw.get('max_level') if isinstance(raw, dict) else raw[2])
        )
