# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ChatMessageState:
    entity_id: int = 0
    username: str = ''
    title_id: int = 0
    channel_id: int = 0
    target_id: int = 0
    text: str = ''
    timestamp: int = 0
    owner_entity_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ChatMessageState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            username=(raw.get('username') if isinstance(raw, dict) else raw[1]),
            title_id=(raw.get('title_id') if isinstance(raw, dict) else raw[2]),
            channel_id=(raw.get('channel_id') if isinstance(raw, dict) else raw[3]),
            target_id=(raw.get('target_id') if isinstance(raw, dict) else raw[4]),
            text=(raw.get('text') if isinstance(raw, dict) else raw[5]),
            timestamp=(raw.get('timestamp') if isinstance(raw, dict) else raw[6]),
            owner_entity_id=(raw.get('owner_entity_id') if isinstance(raw, dict) else raw[7])
        )
