# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class CheatGrantKnowledgeRequest:
    target_entity_id: int = 0
    also_learn: bool = False

    @classmethod
    def from_row(cls, raw) -> 'CheatGrantKnowledgeRequest':
        if raw is None:
            return cls()
        return cls(
            target_entity_id=(raw.get('target_entity_id') if isinstance(raw, dict) else raw[0]),
            also_learn=(raw.get('also_learn') if isinstance(raw, dict) else raw[1])
        )
