# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_large_message import OffsetCoordinatesLargeMessage



@dataclass
class CheatWarpRequest:
    location: OffsetCoordinatesLargeMessage = 0
    owner_entity_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'CheatWarpRequest':
        if raw is None:
            return cls()
        return cls(
            location=OffsetCoordinatesLargeMessage.from_row((raw.get('location') if isinstance(raw, dict) else raw[0])),
            owner_entity_id=(raw.get('owner_entity_id') if isinstance(raw, dict) else raw[1])
        )
