# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_float import OffsetCoordinatesFloat



@dataclass
class CheatTeleportFloatRequest:
    player_entity_id: int = 0
    destination: OffsetCoordinatesFloat | None = None

    @classmethod
    def from_row(cls, raw) -> 'CheatTeleportFloatRequest':
        if raw is None:
            return cls()
        return cls(
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[0]),
            destination=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (OffsetCoordinatesFloat.from_row(_v[1])))((raw.get('destination') if isinstance(raw, dict) else raw[1]))
        )
