# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ClaimSetPurchaseSupplyPriceRequest:
    building_entity_id: int = 0
    purchase_price: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'ClaimSetPurchaseSupplyPriceRequest':
        if raw is None:
            return cls()
        return cls(
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[0]),
            purchase_price=(raw.get('purchase_price') if isinstance(raw, dict) else raw[1])
        )
