# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class ClaimTreasuryChangeReason(IntEnum):
    DEPOSIT = 0
    WITHDRAW = 1


    @classmethod
    def from_row(cls, raw) -> 'ClaimTreasuryChangeReason':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for Deposit
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse ClaimTreasuryChangeReason from {raw!r}')
