# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ClaimTileCost:
    tile_count: int = 0
    cost_per_tile: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'ClaimTileCost':
        if raw is None:
            return cls()
        return cls(
            tile_count=(raw.get('tile_count') if isinstance(raw, dict) else raw[0]),
            cost_per_tile=(raw.get('cost_per_tile') if isinstance(raw, dict) else raw[1])
        )
