# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .claim_treasury_change_reason import ClaimTreasuryChangeReason



@dataclass
class ClaimTreasuryEvent:
    claim_entity_id: int = 0
    actor_entity_id: int = 0
    reason: ClaimTreasuryChangeReason = 0
    amount: int = 0
    treasury_after: int = 0
    timestamp: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ClaimTreasuryEvent':
        if raw is None:
            return cls()
        return cls(
            claim_entity_id=(raw.get('claim_entity_id') if isinstance(raw, dict) else raw[0]),
            actor_entity_id=(raw.get('actor_entity_id') if isinstance(raw, dict) else raw[1]),
            reason=ClaimTreasuryChangeReason.from_row((raw.get('reason') if isinstance(raw, dict) else raw[2])),
            amount=(raw.get('amount') if isinstance(raw, dict) else raw[3]),
            treasury_after=(raw.get('treasury_after') if isinstance(raw, dict) else raw[4]),
            timestamp=((raw.get('timestamp') if isinstance(raw, dict) else raw[5])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('timestamp') if isinstance(raw, dict) else raw[5]), dict) else ((raw.get('timestamp') if isinstance(raw, dict) else raw[5])[0] if isinstance((raw.get('timestamp') if isinstance(raw, dict) else raw[5]), list) else (raw.get('timestamp') if isinstance(raw, dict) else raw[5])))
        )
