# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ClimbRequirementDesc:
    id: int = 0
    min_elevation: int = 0
    max_elevation: int = 0
    stamina_cost: int = 0
    min_climb_proficiency: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'ClimbRequirementDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            min_elevation=(raw.get('min_elevation') if isinstance(raw, dict) else raw[1]),
            max_elevation=(raw.get('max_elevation') if isinstance(raw, dict) else raw[2]),
            stamina_cost=(raw.get('stamina_cost') if isinstance(raw, dict) else raw[3]),
            min_climb_proficiency=(raw.get('min_climb_proficiency') if isinstance(raw, dict) else raw[4])
        )
