# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class CollectibleType(IntEnum):
    DEFAULT = 0
    HAIR = 1
    MASK = 2
    MASKPATTERN = 3
    HAIRCOLOR = 4
    NAMEPLATE = 5
    BODYCOLOR = 6
    EMBLEM = 7
    CLOTHESHEAD = 8
    CLOTHESBELT = 9
    CLOTHESTORSO = 10
    CLOTHESARMS = 11
    CLOTHESLEGS = 12
    CLOTHESFEET = 13
    DEPLOYABLE = 14
    TITLE = 15
    CROWN = 16
    PET = 17
    CLOTHESCAPE = 18
    PREMIUMITEM = 19
    EMOTE = 20
    HOUSINGWALLS = 21
    HOUSINGFLOOR = 22
    DEPLOYABLEAPPEARANCEOVERRIDE = 23


    @classmethod
    def from_row(cls, raw) -> 'CollectibleType':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for Default
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse CollectibleType from {raw!r}')
