# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .action_cooldown import ActionCooldown



@dataclass
class CombatState:
    entity_id: int = 0
    last_attacked_timestamp: int = 0
    last_performed_action_entity_id: int = 0
    global_cooldown: ActionCooldown | None = None

    @classmethod
    def from_row(cls, raw) -> 'CombatState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            last_attacked_timestamp=(raw.get('last_attacked_timestamp') if isinstance(raw, dict) else raw[1]),
            last_performed_action_entity_id=(raw.get('last_performed_action_entity_id') if isinstance(raw, dict) else raw[2]),
            global_cooldown=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (ActionCooldown.from_row(_v[1])))((raw.get('global_cooldown') if isinstance(raw, dict) else raw[3]))
        )
