# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .footprint_tile import FootprintTile



@dataclass
class CombatActionMultiHitDesc:
    id: int = 0
    area_footprint: list = field(default_factory=list)
    max_secondary_targets: int = 0
    secondary_target_multiplier: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'CombatActionMultiHitDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            area_footprint=[FootprintTile.from_row(_item) for _item in ((raw.get('area_footprint') if isinstance(raw, dict) else raw[1]) or [])],
            max_secondary_targets=(raw.get('max_secondary_targets') if isinstance(raw, dict) else raw[2]),
            secondary_target_multiplier=(raw.get('secondary_target_multiplier') if isinstance(raw, dict) else raw[3])
        )
