# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class CommonRng:
    seed: int = 0
    x: int = 0
    y: int = 0

    @classmethod
    def from_row(cls, raw) -> 'CommonRng':
        if raw is None:
            return cls()
        return cls(
            seed=(raw.get('seed') if isinstance(raw, dict) else raw[0]),
            x=(raw.get('x') if isinstance(raw, dict) else raw[1]),
            y=(raw.get('y') if isinstance(raw, dict) else raw[2])
        )
