# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class CompletionCondition(IntEnum):
    PADDINGNONE = 0
    ITEMSTACK = 1
    ACHIEVEMENT = 2
    COLLECTIBLE = 3
    LEVEL = 4
    SECONDARYKNOWLEDGE = 5
    EQUIPPEDITEM = 6


    @classmethod
    def from_row(cls, raw) -> 'CompletionCondition':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for PaddingNone
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse CompletionCondition from {raw!r}')
