# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class CraftCompletedEvent:
    actor_entity_id: int = 0
    progressive_action_entity_id: int = 0
    building_entity_id: int = 0
    recipe_id: int = 0
    craft_count: int = 0

    @classmethod
    def from_row(cls, raw) -> 'CraftCompletedEvent':
        if raw is None:
            return cls()
        return cls(
            actor_entity_id=(raw.get('actor_entity_id') if isinstance(raw, dict) else raw[0]),
            progressive_action_entity_id=(raw.get('progressive_action_entity_id') if isinstance(raw, dict) else raw[1]),
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[2]),
            recipe_id=(raw.get('recipe_id') if isinstance(raw, dict) else raw[3]),
            craft_count=(raw.get('craft_count') if isinstance(raw, dict) else raw[4])
        )
