# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class CreatePlayerReportRequest:
    reported_player_entity_id: int = 0
    reporter_entity_id: int = 0
    chat_message_id: int = 0
    report_type: str = ''
    message: str = ''

    @classmethod
    def from_row(cls, raw) -> 'CreatePlayerReportRequest':
        if raw is None:
            return cls()
        return cls(
            reported_player_entity_id=(raw.get('reported_player_entity_id') if isinstance(raw, dict) else raw[0]),
            reporter_entity_id=(raw.get('reporter_entity_id') if isinstance(raw, dict) else raw[1]),
            chat_message_id=(raw.get('chat_message_id') if isinstance(raw, dict) else raw[2]),
            report_type=(raw.get('report_type') if isinstance(raw, dict) else raw[3]),
            message=(raw.get('message') if isinstance(raw, dict) else raw[4])
        )
