# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_small_message import OffsetCoordinatesSmallMessage



@dataclass
class CrumbTrailExposedState:
    crumb_trail_entity_id: int = 0
    exposed_locations: list = field(default_factory=list)
    exposed_herd_entity_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'CrumbTrailExposedState':
        if raw is None:
            return cls()
        return cls(
            crumb_trail_entity_id=(raw.get('crumb_trail_entity_id') if isinstance(raw, dict) else raw[0]),
            exposed_locations=[OffsetCoordinatesSmallMessage.from_row(_item) for _item in ((raw.get('exposed_locations') if isinstance(raw, dict) else raw[1]) or [])],
            exposed_herd_entity_id=(raw.get('exposed_herd_entity_id') if isinstance(raw, dict) else raw[2])
        )
