# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .experience_stack_f32 import ExperienceStackF32
from .item_stack import ItemStack
from .level_requirement import LevelRequirement
from .tool_requirement import ToolRequirement



@dataclass
class DeconstructionRecipeDesc:
    id: int = 0
    time_requirement: float = 0.0
    consumed_building: int = 0
    level_requirements: list = field(default_factory=list)
    tool_requirements: list = field(default_factory=list)
    output_item_stacks: list = field(default_factory=list)
    output_cargo_id: int = 0
    experience_per_progress: list = field(default_factory=list)
    tool_mesh_index: int = 0
    recipe_performance_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'DeconstructionRecipeDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            time_requirement=(raw.get('time_requirement') if isinstance(raw, dict) else raw[1]),
            consumed_building=(raw.get('consumed_building') if isinstance(raw, dict) else raw[2]),
            level_requirements=[LevelRequirement.from_row(_item) for _item in ((raw.get('level_requirements') if isinstance(raw, dict) else raw[3]) or [])],
            tool_requirements=[ToolRequirement.from_row(_item) for _item in ((raw.get('tool_requirements') if isinstance(raw, dict) else raw[4]) or [])],
            output_item_stacks=[ItemStack.from_row(_item) for _item in ((raw.get('output_item_stacks') if isinstance(raw, dict) else raw[5]) or [])],
            output_cargo_id=(raw.get('output_cargo_id') if isinstance(raw, dict) else raw[6]),
            experience_per_progress=[ExperienceStackF32.from_row(_item) for _item in ((raw.get('experience_per_progress') if isinstance(raw, dict) else raw[7]) or [])],
            tool_mesh_index=(raw.get('tool_mesh_index') if isinstance(raw, dict) else raw[8]),
            recipe_performance_id=(raw.get('recipe_performance_id') if isinstance(raw, dict) else raw[9])
        )
