# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .deployable_deploy_request import DeployableDeployRequest



@dataclass
class DeployableDeployStartEvent:
    actor_id: int = 0
    request: DeployableDeployRequest = 0

    @classmethod
    def from_row(cls, raw) -> 'DeployableDeployStartEvent':
        if raw is None:
            return cls()
        return cls(
            actor_id=(raw.get('actor_id') if isinstance(raw, dict) else raw[0]),
            request=DeployableDeployRequest.from_row((raw.get('request') if isinstance(raw, dict) else raw[1]))
        )
