# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_small_message import OffsetCoordinatesSmallMessage



@dataclass
class DeployableCollectibleState:
    deployable_entity_id: int = 0
    owner_entity_id: int = 0
    collectible_id: int = 0
    deployable_desc_id: int = 0
    location: OffsetCoordinatesSmallMessage | None = None
    auto_follow: bool = False

    @classmethod
    def from_row(cls, raw) -> 'DeployableCollectibleState':
        if raw is None:
            return cls()
        return cls(
            deployable_entity_id=(raw.get('deployable_entity_id') if isinstance(raw, dict) else raw[0]),
            owner_entity_id=(raw.get('owner_entity_id') if isinstance(raw, dict) else raw[1]),
            collectible_id=(raw.get('collectible_id') if isinstance(raw, dict) else raw[2]),
            deployable_desc_id=(raw.get('deployable_desc_id') if isinstance(raw, dict) else raw[3]),
            location=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (OffsetCoordinatesSmallMessage.from_row(_v[1])))((raw.get('location') if isinstance(raw, dict) else raw[4])),
            auto_follow=(raw.get('auto_follow') if isinstance(raw, dict) else raw[5])
        )
