# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_small_message import OffsetCoordinatesSmallMessage



@dataclass
class DeployableDeployRequest:
    vault_index: int = 0
    coord: OffsetCoordinatesSmallMessage = 0
    direction: int = 0

    @classmethod
    def from_row(cls, raw) -> 'DeployableDeployRequest':
        if raw is None:
            return cls()
        return cls(
            vault_index=(raw.get('vault_index') if isinstance(raw, dict) else raw[0]),
            coord=OffsetCoordinatesSmallMessage.from_row((raw.get('coord') if isinstance(raw, dict) else raw[1])),
            direction=(raw.get('direction') if isinstance(raw, dict) else raw[2])
        )
