# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_float import OffsetCoordinatesFloat



@dataclass
class DestroyDimensionNetworkTimer:
    scheduled_id: int = 0
    scheduled_at: object = 0
    player_teleport_location: OffsetCoordinatesFloat = 0
    dimension_network_entity_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'DestroyDimensionNetworkTimer':
        if raw is None:
            return cls()
        return cls(
            scheduled_id=(raw.get('scheduled_id') if isinstance(raw, dict) else raw[0]),
            scheduled_at=(raw.get('scheduled_at') if isinstance(raw, dict) else raw[1]),
            player_teleport_location=OffsetCoordinatesFloat.from_row((raw.get('player_teleport_location') if isinstance(raw, dict) else raw[2])),
            dimension_network_entity_id=(raw.get('dimension_network_entity_id') if isinstance(raw, dict) else raw[3])
        )
