# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class Developer:
    identity: str = 0
    developer_name: str = ''
    service_name: str = ''
    email: str = ''
    is_external: bool = False

    @classmethod
    def from_row(cls, raw) -> 'Developer':
        if raw is None:
            return cls()
        return cls(
            identity=((raw.get('identity') if isinstance(raw, dict) else raw[0])['__identity__'] if isinstance((raw.get('identity') if isinstance(raw, dict) else raw[0]), dict) else ((raw.get('identity') if isinstance(raw, dict) else raw[0])[0] if isinstance((raw.get('identity') if isinstance(raw, dict) else raw[0]), list) else (raw.get('identity') if isinstance(raw, dict) else raw[0]))),
            developer_name=(raw.get('developer_name') if isinstance(raw, dict) else raw[1]),
            service_name=(raw.get('service_name') if isinstance(raw, dict) else raw[2]),
            email=(raw.get('email') if isinstance(raw, dict) else raw[3]),
            is_external=(raw.get('is_external') if isinstance(raw, dict) else raw[4])
        )
