# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class DroppedInventoryOwnershipTimer:
    scheduled_id: int = 0
    scheduled_at: object = 0
    entity_id: int = 0
    started_at: int = 0

    @classmethod
    def from_row(cls, raw) -> 'DroppedInventoryOwnershipTimer':
        if raw is None:
            return cls()
        return cls(
            scheduled_id=(raw.get('scheduled_id') if isinstance(raw, dict) else raw[0]),
            scheduled_at=(raw.get('scheduled_at') if isinstance(raw, dict) else raw[1]),
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[2]),
            started_at=((raw.get('started_at') if isinstance(raw, dict) else raw[3])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('started_at') if isinstance(raw, dict) else raw[3]), dict) else (raw.get('started_at') if isinstance(raw, dict) else raw[3]))
        )
