# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmoteDesc:
    id: int = 0
    name: str = ''
    animation: str = ''
    duration: float = 0.0
    key_code: str = ''
    command_line: str = ''
    allow_while_mounted: bool = False
    allow_while_moving: bool = False
    enabled_by_collectible_id: int = 0
    tool_type: int = 0
    tool_mesh_index: int = 0

    @classmethod
    def from_row(cls, raw) -> 'EmoteDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            animation=(raw.get('animation') if isinstance(raw, dict) else raw[2]),
            duration=(raw.get('duration') if isinstance(raw, dict) else raw[3]),
            key_code=(raw.get('key_code') if isinstance(raw, dict) else raw[4]),
            command_line=(raw.get('command_line') if isinstance(raw, dict) else raw[5]),
            allow_while_mounted=(raw.get('allow_while_mounted') if isinstance(raw, dict) else raw[6]),
            allow_while_moving=(raw.get('allow_while_moving') if isinstance(raw, dict) else raw[7]),
            enabled_by_collectible_id=(raw.get('enabled_by_collectible_id') if isinstance(raw, dict) else raw[8]),
            tool_type=(raw.get('tool_type') if isinstance(raw, dict) else raw[9]),
            tool_mesh_index=(raw.get('tool_mesh_index') if isinstance(raw, dict) else raw[10])
        )
