# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireClaimJoinMsg:
    player_entity_id: int = 0
    claim_entity_id: int = 0
    claim_building_entity_id: int = 0
    empire_entity_id: int = 0
    claim_name: str = ''

    @classmethod
    def from_row(cls, raw) -> 'EmpireClaimJoinMsg':
        if raw is None:
            return cls()
        return cls(
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[0]),
            claim_entity_id=(raw.get('claim_entity_id') if isinstance(raw, dict) else raw[1]),
            claim_building_entity_id=(raw.get('claim_building_entity_id') if isinstance(raw, dict) else raw[2]),
            empire_entity_id=(raw.get('empire_entity_id') if isinstance(raw, dict) else raw[3]),
            claim_name=(raw.get('claim_name') if isinstance(raw, dict) else raw[4])
        )
