# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireSuppliesDesc:
    cargo_id: int = 0
    energy: int = 0

    @classmethod
    def from_row(cls, raw) -> 'EmpireSuppliesDesc':
        if raw is None:
            return cls()
        return cls(
            cargo_id=(raw.get('cargo_id') if isinstance(raw, dict) else raw[0]),
            energy=(raw.get('energy') if isinstance(raw, dict) else raw[1])
        )
