# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .pocket_key import PocketKey



@dataclass
class EmpireResupplyNodeRequest:
    building_entity_id: int = 0
    from_pocket: PocketKey = 0

    @classmethod
    def from_row(cls, raw) -> 'EmpireResupplyNodeRequest':
        if raw is None:
            return cls()
        return cls(
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[0]),
            from_pocket=PocketKey.from_row((raw.get('from_pocket') if isinstance(raw, dict) else raw[1]))
        )
