# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireRankState:
    entity_id: int = 0
    empire_entity_id: int = 0
    rank: int = 0
    title: str = ''
    permissions: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'EmpireRankState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            empire_entity_id=(raw.get('empire_entity_id') if isinstance(raw, dict) else raw[1]),
            rank=(raw.get('rank') if isinstance(raw, dict) else raw[2]),
            title=(raw.get('title') if isinstance(raw, dict) else raw[3]),
            permissions=[_item for _item in ((raw.get('permissions') if isinstance(raw, dict) else raw[4]) or [])]
        )
