# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireRankDesc:
    rank: int = 0
    title: str = ''
    max_count: int | None = None
    permissions: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'EmpireRankDesc':
        if raw is None:
            return cls()
        return cls(
            rank=(raw.get('rank') if isinstance(raw, dict) else raw[0]),
            title=(raw.get('title') if isinstance(raw, dict) else raw[1]),
            max_count=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]))((raw.get('max_count') if isinstance(raw, dict) else raw[2])),
            permissions=[_item for _item in ((raw.get('permissions') if isinstance(raw, dict) else raw[3]) or [])]
        )
