# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireAddSiegeSuppliesRequest:
    building_entity_id: int = 0
    proxy_empire_entity_id: int | None = None

    @classmethod
    def from_row(cls, raw) -> 'EmpireAddSiegeSuppliesRequest':
        if raw is None:
            return cls()
        return cls(
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[0]),
            proxy_empire_entity_id=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]))((raw.get('proxy_empire_entity_id') if isinstance(raw, dict) else raw[1]))
        )
