# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireTerritoryDesc:
    id: int = 0
    chunks: int = 0
    ranks: bytes = b''
    crown_collectible_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'EmpireTerritoryDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            chunks=(raw.get('chunks') if isinstance(raw, dict) else raw[1]),
            ranks=(raw.get('ranks') if isinstance(raw, dict) else raw[2]),
            crown_collectible_id=(raw.get('crown_collectible_id') if isinstance(raw, dict) else raw[3])
        )
