# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_small_message import OffsetCoordinatesSmallMessage



@dataclass
class EmpireNodeState:
    entity_id: int = 0
    empire_entity_id: int = 0
    chunk_index: int = 0
    energy: int = 0
    active: bool = False
    upkeep: int = 0
    location: OffsetCoordinatesSmallMessage = 0

    @classmethod
    def from_row(cls, raw) -> 'EmpireNodeState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            empire_entity_id=(raw.get('empire_entity_id') if isinstance(raw, dict) else raw[1]),
            chunk_index=(raw.get('chunk_index') if isinstance(raw, dict) else raw[2]),
            energy=(raw.get('energy') if isinstance(raw, dict) else raw[3]),
            active=(raw.get('active') if isinstance(raw, dict) else raw[4]),
            upkeep=(raw.get('upkeep') if isinstance(raw, dict) else raw[5]),
            location=OffsetCoordinatesSmallMessage.from_row((raw.get('location') if isinstance(raw, dict) else raw[6]))
        )
