# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EmpireSiegeAddSuppliesMsg:
    siege_entity_id: int = 0
    player_entity_id: int = 0
    supplies: int = 0
    supply_cargo_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'EmpireSiegeAddSuppliesMsg':
        if raw is None:
            return cls()
        return cls(
            siege_entity_id=(raw.get('siege_entity_id') if isinstance(raw, dict) else raw[0]),
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[1]),
            supplies=(raw.get('supplies') if isinstance(raw, dict) else raw[2]),
            supply_cargo_id=(raw.get('supply_cargo_id') if isinstance(raw, dict) else raw[3])
        )
