# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_small_message import OffsetCoordinatesSmallMessage



@dataclass
class EmpireCreateBuildingMsg:
    location: OffsetCoordinatesSmallMessage = 0
    player_entity_id: int = 0
    building_entity_id: int = 0
    building_desc_id: int = 0
    construction_recipe_id: int | None = None

    @classmethod
    def from_row(cls, raw) -> 'EmpireCreateBuildingMsg':
        if raw is None:
            return cls()
        return cls(
            location=OffsetCoordinatesSmallMessage.from_row((raw.get('location') if isinstance(raw, dict) else raw[0])),
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[1]),
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[2]),
            building_desc_id=(raw.get('building_desc_id') if isinstance(raw, dict) else raw[3]),
            construction_recipe_id=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]))((raw.get('construction_recipe_id') if isinstance(raw, dict) else raw[4]))
        )
