# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .small_hex_tile_message import SmallHexTileMessage



@dataclass
class EnemySpawnLootRequest:
    enemy_type: int = 0
    player_entity_id: int = 0
    loot_coordinates: SmallHexTileMessage = 0

    @classmethod
    def from_row(cls, raw) -> 'EnemySpawnLootRequest':
        if raw is None:
            return cls()
        return cls(
            enemy_type=(raw.get('enemy_type') if isinstance(raw, dict) else raw[0]),
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[1]),
            loot_coordinates=SmallHexTileMessage.from_row((raw.get('loot_coordinates') if isinstance(raw, dict) else raw[2]))
        )
