# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_float import OffsetCoordinatesFloat



@dataclass
class EnemyMoveRequest:
    entity_id: int = 0
    chunk_index: int = 0
    origin: OffsetCoordinatesFloat = 0
    destination: OffsetCoordinatesFloat = 0
    duration: float = 0.0
    overlap_prevention: bool = False

    @classmethod
    def from_row(cls, raw) -> 'EnemyMoveRequest':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            chunk_index=(raw.get('chunk_index') if isinstance(raw, dict) else raw[1]),
            origin=OffsetCoordinatesFloat.from_row((raw.get('origin') if isinstance(raw, dict) else raw[2])),
            destination=OffsetCoordinatesFloat.from_row((raw.get('destination') if isinstance(raw, dict) else raw[3])),
            duration=(raw.get('duration') if isinstance(raw, dict) else raw[4]),
            overlap_prevention=(raw.get('overlap_prevention') if isinstance(raw, dict) else raw[5])
        )
