# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class EnemyType(IntEnum):
    NONE = 0
    PRACTICEDUMMY = 1
    GRASSBIRD = 2
    DESERTBIRD = 3
    SWAMPBIRD = 4
    GOAT = 5
    MOUNTAINGOAT = 6
    DEERFEMALE = 7
    DEERMALE = 8
    ELK = 9
    BOARFEMALE = 10
    BOARMALE = 11
    BOARELDER = 12
    PLAINSOX = 13
    TUNDRAOX = 14
    JUNGLELARGEBIRD = 15
    DESERTLARGEBIRD = 16
    JAKYL = 17
    ALPHAJAKYL = 18
    KINGJAKYL = 19
    ROCKCRAB = 20
    DESERTCRAB = 21
    FROSTCRAB = 22
    FORESTTOAD = 23
    SWAMPTOAD = 24
    FROSTTOAD = 25
    UMBURA = 26
    ALPHAUMBURA = 27
    KINGUMBURA = 28
    DRONE = 29
    SOLDIER = 30
    QUEEN = 31
    SENTINEL = 32
    SENTINELDUNGEONJAKYL = 33
    SENTINELDUNGEONSKITCH = 34
    SENTINELDUNGEONLARGEJAKYL = 35
    CRABDUNGEONCRABBOSS = 36
    CRABDUNGEONCRABTRASH = 37
    SPIDERDUNGEONELITESPIDER = 38
    SPIDERDUNGEONSMALLSPIDER = 39
    SPIDERDUNGEONSPIDERNEST = 40
    ENRAGEDALPHAJAKYL = 41
    DEERSWIFT = 42


    @classmethod
    def from_row(cls, raw) -> 'EnemyType':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for None
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse EnemyType from {raw!r}')
