# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .enemy_type import EnemyType
from .offset_coordinates_float import OffsetCoordinatesFloat



@dataclass
class EnemyDespawnEvent:
    entity_id: int = 0
    enemy_type: EnemyType = 0
    despawn_timestamp: int = 0
    location: OffsetCoordinatesFloat = 0
    destination: OffsetCoordinatesFloat = 0
    movement_timestamp: int = 0

    @classmethod
    def from_row(cls, raw) -> 'EnemyDespawnEvent':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            enemy_type=EnemyType.from_row((raw.get('enemy_type') if isinstance(raw, dict) else raw[1])),
            despawn_timestamp=(raw.get('despawn_timestamp') if isinstance(raw, dict) else raw[2]),
            location=OffsetCoordinatesFloat.from_row((raw.get('location') if isinstance(raw, dict) else raw[3])),
            destination=OffsetCoordinatesFloat.from_row((raw.get('destination') if isinstance(raw, dict) else raw[4])),
            movement_timestamp=(raw.get('movement_timestamp') if isinstance(raw, dict) else raw[5])
        )
