# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class EnemyClearAggroRequest:
    entity_id: int = 0
    aggro_entity_id: object | None = None

    @classmethod
    def from_row(cls, raw) -> 'EnemyClearAggroRequest':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            aggro_entity_id=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]))((raw.get('aggro_entity_id') if isinstance(raw, dict) else raw[1]))
        )
