# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .enemy_type import EnemyType
from .offset_coordinates_small_message import OffsetCoordinatesSmallMessage



@dataclass
class EnemySpawnRequest:
    enemy_type: EnemyType = 0
    herd_entity_id: int = 0
    coord: OffsetCoordinatesSmallMessage = 0

    @classmethod
    def from_row(cls, raw) -> 'EnemySpawnRequest':
        if raw is None:
            return cls()
        return cls(
            enemy_type=EnemyType.from_row((raw.get('enemy_type') if isinstance(raw, dict) else raw[0])),
            herd_entity_id=(raw.get('herd_entity_id') if isinstance(raw, dict) else raw[1]),
            coord=OffsetCoordinatesSmallMessage.from_row((raw.get('coord') if isinstance(raw, dict) else raw[2]))
        )
