# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .entity_attack_request import EntityAttackRequest



@dataclass
class EntityAttackStartEvent:
    request: EntityAttackRequest = 0

    @classmethod
    def from_row(cls, raw) -> 'EntityAttackStartEvent':
        if raw is None:
            return cls()
        return cls(
            request=EntityAttackRequest.from_row((raw.get('request') if isinstance(raw, dict) else raw[0]))
        )
