# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .entity_type import EntityType



@dataclass
class EntityAttackRequest:
    attacker_entity_id: int = 0
    defender_entity_id: int = 0
    combat_action_id: int = 0
    attacker_type: EntityType = 0
    defender_type: EntityType = 0

    @classmethod
    def from_row(cls, raw) -> 'EntityAttackRequest':
        if raw is None:
            return cls()
        return cls(
            attacker_entity_id=(raw.get('attacker_entity_id') if isinstance(raw, dict) else raw[0]),
            defender_entity_id=(raw.get('defender_entity_id') if isinstance(raw, dict) else raw[1]),
            combat_action_id=(raw.get('combat_action_id') if isinstance(raw, dict) else raw[2]),
            attacker_type=EntityType.from_row((raw.get('attacker_type') if isinstance(raw, dict) else raw[3])),
            defender_type=EntityType.from_row((raw.get('defender_type') if isinstance(raw, dict) else raw[4]))
        )
