# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .environment_resistance_type import EnvironmentResistanceType



@dataclass
class EnvironmentDebuffDesc:
    buff_id: int = 0
    resistance_type: EnvironmentResistanceType = 0
    resistance_level: int = 0
    ground_damage: int = 0
    water_damage: int = 0
    resistance_unmet_text: str = ''
    resistance_met_text: str = ''

    @classmethod
    def from_row(cls, raw) -> 'EnvironmentDebuffDesc':
        if raw is None:
            return cls()
        return cls(
            buff_id=(raw.get('buff_id') if isinstance(raw, dict) else raw[0]),
            resistance_type=EnvironmentResistanceType.from_row((raw.get('resistance_type') if isinstance(raw, dict) else raw[1])),
            resistance_level=(raw.get('resistance_level') if isinstance(raw, dict) else raw[2]),
            ground_damage=(raw.get('ground_damage') if isinstance(raw, dict) else raw[3]),
            water_damage=(raw.get('water_damage') if isinstance(raw, dict) else raw[4]),
            resistance_unmet_text=(raw.get('resistance_unmet_text') if isinstance(raw, dict) else raw[5]),
            resistance_met_text=(raw.get('resistance_met_text') if isinstance(raw, dict) else raw[6])
        )
