# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class EquipmentSlotType(IntEnum):
    MAINHAND = 0
    OFFHAND = 1
    HEADARTIFACT = 2
    TORSOARTIFACT = 3
    HANDARTIFACT = 4
    FEETARTIFACT = 5
    HEADCLOTHING = 6
    TORSOCLOTHING = 7
    HANDCLOTHING = 8
    BELTCLOTHING = 9
    LEGCLOTHING = 10
    FEETCLOTHING = 11
    NONE = 12
    FORESTRYCHARM = 13
    FORESTRYINSTRUMENT = 14
    CARPENTRYCHARM = 15
    CARPENTRYINSTRUMENT = 16
    MASONRYCHARM = 17
    MASONRYINSTRUMENT = 18
    MININGCHARM = 19
    MININGINSTRUMENT = 20
    SMITHINGCHARM = 21
    SMITHINGINSTRUMENT = 22
    LEATHERWORKINGCHARM = 23
    LEATHERWORKINGINSTRUMENT = 24
    HUNTINGCHARM = 25
    HUNTINGINSTRUMENT = 26
    TAILORINGCHARM = 27
    TAILORINGINSTRUMENT = 28
    FARMINGCHARM = 29
    FARMINGINSTRUMENT = 30
    FISHINGCHARM = 31
    FISHINGINSTRUMENT = 32
    FORAGINGCHARM = 33
    FORAGINGINSTRUMENT = 34
    SCHOLARCHARM = 35
    SCHOLARINSTRUMENT = 36


    @classmethod
    def from_row(cls, raw) -> 'EquipmentSlotType':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for MainHand
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse EquipmentSlotType from {raw!r}')
