# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .equipment_slot_type import EquipmentSlotType
from .item_stack import ItemStack



@dataclass
class EquipmentSlot:
    item: ItemStack | None = None
    primary: EquipmentSlotType = 0

    @classmethod
    def from_row(cls, raw) -> 'EquipmentSlot':
        if raw is None:
            return cls()
        return cls(
            item=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (ItemStack.from_row(_v[1])))((raw.get('item') if isinstance(raw, dict) else raw[0])),
            primary=EquipmentSlotType.from_row((raw.get('primary') if isinstance(raw, dict) else raw[1]))
        )
