# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ExtractOutcomeStateV2:
    entity_id: int = 0
    target_entity_id: int = 0
    last_timestamp: int = 0
    damage: int = 0
    is_crit: bool = False

    @classmethod
    def from_row(cls, raw) -> 'ExtractOutcomeStateV2':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            target_entity_id=(raw.get('target_entity_id') if isinstance(raw, dict) else raw[1]),
            last_timestamp=((raw.get('last_timestamp') if isinstance(raw, dict) else raw[2])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('last_timestamp') if isinstance(raw, dict) else raw[2]), dict) else ((raw.get('last_timestamp') if isinstance(raw, dict) else raw[2])[0] if isinstance((raw.get('last_timestamp') if isinstance(raw, dict) else raw[2]), list) else (raw.get('last_timestamp') if isinstance(raw, dict) else raw[2]))),
            damage=(raw.get('damage') if isinstance(raw, dict) else raw[3]),
            is_crit=(raw.get('is_crit') if isinstance(raw, dict) else raw[4])
        )
