# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .empire_permission import EmpirePermission
from .experience_stack_f32 import ExperienceStackF32
from .input_item_stack import InputItemStack
from .level_requirement import LevelRequirement
from .probabilistic_item_stack import ProbabilisticItemStack
from .tool_requirement import ToolRequirement



@dataclass
class ExtractionRecipeDesc:
    id: int = 0
    resource_id: int = 0
    cargo_id: int = 0
    discovery_triggers: list = field(default_factory=list)
    required_knowledges: list = field(default_factory=list)
    blocking_knowledges: list = field(default_factory=list)
    time_requirement: float = 0.0
    stamina_requirement: float = 0.0
    tool_durability_lost: int = 0
    extracted_item_stacks: list = field(default_factory=list)
    consumed_item_stacks: list = field(default_factory=list)
    range: int = 0
    tool_requirements: list = field(default_factory=list)
    allow_use_hands: bool = False
    level_requirements: list = field(default_factory=list)
    experience_per_progress: list = field(default_factory=list)
    verb_phrase: str = ''
    tool_mesh_index: int = 0
    recipe_performance_id: int = 0
    empire_rank_requirement: int | None = None
    show_in_progression: bool = False
    empire_permission_required: EmpirePermission | None = None

    @classmethod
    def from_row(cls, raw) -> 'ExtractionRecipeDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            resource_id=(raw.get('resource_id') if isinstance(raw, dict) else raw[1]),
            cargo_id=(raw.get('cargo_id') if isinstance(raw, dict) else raw[2]),
            discovery_triggers=[_item for _item in ((raw.get('discovery_triggers') if isinstance(raw, dict) else raw[3]) or [])],
            required_knowledges=[_item for _item in ((raw.get('required_knowledges') if isinstance(raw, dict) else raw[4]) or [])],
            blocking_knowledges=[_item for _item in ((raw.get('blocking_knowledges') if isinstance(raw, dict) else raw[5]) or [])],
            time_requirement=(raw.get('time_requirement') if isinstance(raw, dict) else raw[6]),
            stamina_requirement=(raw.get('stamina_requirement') if isinstance(raw, dict) else raw[7]),
            tool_durability_lost=(raw.get('tool_durability_lost') if isinstance(raw, dict) else raw[8]),
            extracted_item_stacks=[ProbabilisticItemStack.from_row(_item) for _item in ((raw.get('extracted_item_stacks') if isinstance(raw, dict) else raw[9]) or [])],
            consumed_item_stacks=[InputItemStack.from_row(_item) for _item in ((raw.get('consumed_item_stacks') if isinstance(raw, dict) else raw[10]) or [])],
            range=(raw.get('range') if isinstance(raw, dict) else raw[11]),
            tool_requirements=[ToolRequirement.from_row(_item) for _item in ((raw.get('tool_requirements') if isinstance(raw, dict) else raw[12]) or [])],
            allow_use_hands=(raw.get('allow_use_hands') if isinstance(raw, dict) else raw[13]),
            level_requirements=[LevelRequirement.from_row(_item) for _item in ((raw.get('level_requirements') if isinstance(raw, dict) else raw[14]) or [])],
            experience_per_progress=[ExperienceStackF32.from_row(_item) for _item in ((raw.get('experience_per_progress') if isinstance(raw, dict) else raw[15]) or [])],
            verb_phrase=(raw.get('verb_phrase') if isinstance(raw, dict) else raw[16]),
            tool_mesh_index=(raw.get('tool_mesh_index') if isinstance(raw, dict) else raw[17]),
            recipe_performance_id=(raw.get('recipe_performance_id') if isinstance(raw, dict) else raw[18]),
            empire_rank_requirement=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]))((raw.get('empire_rank_requirement') if isinstance(raw, dict) else raw[19])),
            show_in_progression=(raw.get('show_in_progression') if isinstance(raw, dict) else raw[20]),
            empire_permission_required=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (EmpirePermission.from_row(_v[1])))((raw.get('empire_permission_required') if isinstance(raw, dict) else raw[21]))
        )
