# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class GatedFeature:
    feature: str = ''

    @classmethod
    def from_row(cls, raw) -> 'GatedFeature':
        if raw is None:
            return cls()
        return cls(
            feature=(raw.get('feature') if isinstance(raw, dict) else raw[0])
        )
