# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class HexiteExchangeEntryDesc:
    id: int = 0
    image_address: str = ''
    shard_amount: int = 0
    base_shard_amount: int = 0
    name: str = ''
    price: float = 0.0
    event_name: str = ''

    @classmethod
    def from_row(cls, raw) -> 'HexiteExchangeEntryDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            image_address=(raw.get('image_address') if isinstance(raw, dict) else raw[1]),
            shard_amount=(raw.get('shard_amount') if isinstance(raw, dict) else raw[2]),
            base_shard_amount=(raw.get('base_shard_amount') if isinstance(raw, dict) else raw[3]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[4]),
            price=(raw.get('price') if isinstance(raw, dict) else raw[5]),
            event_name=(raw.get('event_name') if isinstance(raw, dict) else raw[6])
        )
