# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class InterModuleMessageErrors:
    sender_module_id: int = 0
    message_id: int = 0
    error: str = ''

    @classmethod
    def from_row(cls, raw) -> 'InterModuleMessageErrors':
        if raw is None:
            return cls()
        return cls(
            sender_module_id=(raw.get('sender_module_id') if isinstance(raw, dict) else raw[0]),
            message_id=(raw.get('message_id') if isinstance(raw, dict) else raw[1]),
            error=(raw.get('error') if isinstance(raw, dict) else raw[2])
        )
