# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class InteriorPortalConnectionsDesc:
    id: int = 0
    entrance_spawn_id: int = 0
    entrance_portal_id: int = 0
    exit_spawn_id: int = 0
    exit_portal_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'InteriorPortalConnectionsDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            entrance_spawn_id=(raw.get('entrance_spawn_id') if isinstance(raw, dict) else raw[1]),
            entrance_portal_id=(raw.get('entrance_portal_id') if isinstance(raw, dict) else raw[2]),
            exit_spawn_id=(raw.get('exit_spawn_id') if isinstance(raw, dict) else raw[3]),
            exit_portal_id=(raw.get('exit_portal_id') if isinstance(raw, dict) else raw[4])
        )
