# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class InteriorInstanceDesc:
    id: int = 0
    interior_shape_id: int = 0
    tier: int = 0
    biome: int = 0
    rentable: bool = False
    generate_walls_mesh: bool = False
    generate_floor_mesh: bool = False
    default_lighting: bool = False
    interior_model: str = ''
    wall_material: str = ''
    floor_material: str = ''
    min_zoom: float = 0.0
    max_zoom: float = 0.0
    min_angle: float = 0.0
    max_angle: float = 0.0
    intertior_environment_id: object | None = None

    @classmethod
    def from_row(cls, raw) -> 'InteriorInstanceDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            interior_shape_id=(raw.get('interior_shape_id') if isinstance(raw, dict) else raw[1]),
            tier=(raw.get('tier') if isinstance(raw, dict) else raw[2]),
            biome=(raw.get('biome') if isinstance(raw, dict) else raw[3]),
            rentable=(raw.get('rentable') if isinstance(raw, dict) else raw[4]),
            generate_walls_mesh=(raw.get('generate_walls_mesh') if isinstance(raw, dict) else raw[5]),
            generate_floor_mesh=(raw.get('generate_floor_mesh') if isinstance(raw, dict) else raw[6]),
            default_lighting=(raw.get('default_lighting') if isinstance(raw, dict) else raw[7]),
            interior_model=(raw.get('interior_model') if isinstance(raw, dict) else raw[8]),
            wall_material=(raw.get('wall_material') if isinstance(raw, dict) else raw[9]),
            floor_material=(raw.get('floor_material') if isinstance(raw, dict) else raw[10]),
            min_zoom=(raw.get('min_zoom') if isinstance(raw, dict) else raw[11]),
            max_zoom=(raw.get('max_zoom') if isinstance(raw, dict) else raw[12]),
            min_angle=(raw.get('min_angle') if isinstance(raw, dict) else raw[13]),
            max_angle=(raw.get('max_angle') if isinstance(raw, dict) else raw[14]),
            intertior_environment_id=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]))((raw.get('intertior_environment_id') if isinstance(raw, dict) else raw[15]))
        )
