# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .footprint_tile import FootprintTile



@dataclass
class InteriorShapeDesc:
    id: int = 0
    footprint: list = field(default_factory=list)
    min_x: int = 0
    min_z: int = 0
    size_x: int = 0
    size_z: int = 0

    @classmethod
    def from_row(cls, raw) -> 'InteriorShapeDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            footprint=[FootprintTile.from_row(_item) for _item in ((raw.get('footprint') if isinstance(raw, dict) else raw[1]) or [])],
            min_x=(raw.get('min_x') if isinstance(raw, dict) else raw[2]),
            min_z=(raw.get('min_z') if isinstance(raw, dict) else raw[3]),
            size_x=(raw.get('size_x') if isinstance(raw, dict) else raw[4]),
            size_z=(raw.get('size_z') if isinstance(raw, dict) else raw[5])
        )
