# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .rarity import Rarity



@dataclass
class ItemDesc:
    id: int = 0
    name: str = ''
    description: str = ''
    volume: int = 0
    durability: int = 0
    convert_to_on_durability_zero: int = 0
    secondary_knowledge_id: int = 0
    model_asset_name: str = ''
    icon_asset_name: str = ''
    tier: int = 0
    tag: str = ''
    rarity: Rarity = 0
    compendium_entry: bool = False
    item_list_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ItemDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            description=(raw.get('description') if isinstance(raw, dict) else raw[2]),
            volume=(raw.get('volume') if isinstance(raw, dict) else raw[3]),
            durability=(raw.get('durability') if isinstance(raw, dict) else raw[4]),
            convert_to_on_durability_zero=(raw.get('convert_to_on_durability_zero') if isinstance(raw, dict) else raw[5]),
            secondary_knowledge_id=(raw.get('secondary_knowledge_id') if isinstance(raw, dict) else raw[6]),
            model_asset_name=(raw.get('model_asset_name') if isinstance(raw, dict) else raw[7]),
            icon_asset_name=(raw.get('icon_asset_name') if isinstance(raw, dict) else raw[8]),
            tier=(raw.get('tier') if isinstance(raw, dict) else raw[9]),
            tag=(raw.get('tag') if isinstance(raw, dict) else raw[10]),
            rarity=Rarity.from_row((raw.get('rarity') if isinstance(raw, dict) else raw[11])),
            compendium_entry=(raw.get('compendium_entry') if isinstance(raw, dict) else raw[12]),
            item_list_id=(raw.get('item_list_id') if isinstance(raw, dict) else raw[13])
        )
