# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_stack import ItemStack



@dataclass
class ItemStackCompletionCondition:
    item_stack: ItemStack = 0
    is_consumed: bool = False

    @classmethod
    def from_row(cls, raw) -> 'ItemStackCompletionCondition':
        if raw is None:
            return cls()
        return cls(
            item_stack=ItemStack.from_row((raw.get('item_stack') if isinstance(raw, dict) else raw[0])),
            is_consumed=(raw.get('is_consumed') if isinstance(raw, dict) else raw[1])
        )
