# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_stack import ItemStack



@dataclass
class ItemListPossibility:
    probability: float = 0.0
    items: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'ItemListPossibility':
        if raw is None:
            return cls()
        return cls(
            probability=(raw.get('probability') if isinstance(raw, dict) else raw[0]),
            items=[ItemStack.from_row(_item) for _item in ((raw.get('items') if isinstance(raw, dict) else raw[1]) or [])]
        )
