# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_list_possibility import ItemListPossibility



@dataclass
class ItemListDesc:
    id: int = 0
    name: str = ''
    possibilities: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'ItemListDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            possibilities=[ItemListPossibility.from_row(_item) for _item in ((raw.get('possibilities') if isinstance(raw, dict) else raw[2]) or [])]
        )
