# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .knowledge_state import KnowledgeState



@dataclass
class KnowledgeEntry:
    id: int = 0
    state: KnowledgeState = 0

    @classmethod
    def from_row(cls, raw) -> 'KnowledgeEntry':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            state=KnowledgeState.from_row((raw.get('state') if isinstance(raw, dict) else raw[1]))
        )
