# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class KnowledgeScrollDesc:
    item_id: int = 0
    scroll_type: int = 0
    secondary_knowledge_id: int = 0
    known_by_default: bool = False
    auto_collect: bool = False
    title: str = ''
    tag: str = ''
    content: str = ''

    @classmethod
    def from_row(cls, raw) -> 'KnowledgeScrollDesc':
        if raw is None:
            return cls()
        return cls(
            item_id=(raw.get('item_id') if isinstance(raw, dict) else raw[0]),
            scroll_type=(raw.get('scroll_type') if isinstance(raw, dict) else raw[1]),
            secondary_knowledge_id=(raw.get('secondary_knowledge_id') if isinstance(raw, dict) else raw[2]),
            known_by_default=(raw.get('known_by_default') if isinstance(raw, dict) else raw[3]),
            auto_collect=(raw.get('auto_collect') if isinstance(raw, dict) else raw[4]),
            title=(raw.get('title') if isinstance(raw, dict) else raw[5]),
            tag=(raw.get('tag') if isinstance(raw, dict) else raw[6]),
            content=(raw.get('content') if isinstance(raw, dict) else raw[7])
        )
