# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class LocationState:
    entity_id: int = 0
    chunk_index: int = 0
    x: int = 0
    z: int = 0
    dimension: int = 0

    @classmethod
    def from_row(cls, raw) -> 'LocationState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            chunk_index=(raw.get('chunk_index') if isinstance(raw, dict) else raw[1]),
            x=(raw.get('x') if isinstance(raw, dict) else raw[2]),
            z=(raw.get('z') if isinstance(raw, dict) else raw[3]),
            dimension=(raw.get('dimension') if isinstance(raw, dict) else raw[4])
        )
