# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .probabilistic_item_stack import ProbabilisticItemStack



@dataclass
class LootTableDesc:
    id: int = 0
    loot_rarity: int = 0
    loot_item_stacks: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'LootTableDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            loot_rarity=(raw.get('loot_rarity') if isinstance(raw, dict) else raw[1]),
            loot_item_stacks=[ProbabilisticItemStack.from_row(_item) for _item in ((raw.get('loot_item_stacks') if isinstance(raw, dict) else raw[2]) or [])]
        )
