# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class LootChestDespawnTimer:
    scheduled_id: int = 0
    scheduled_at: object = 0
    loot_chest_entity_id: int = 0
    should_respawn: bool = False

    @classmethod
    def from_row(cls, raw) -> 'LootChestDespawnTimer':
        if raw is None:
            return cls()
        return cls(
            scheduled_id=(raw.get('scheduled_id') if isinstance(raw, dict) else raw[0]),
            scheduled_at=(raw.get('scheduled_at') if isinstance(raw, dict) else raw[1]),
            loot_chest_entity_id=(raw.get('loot_chest_entity_id') if isinstance(raw, dict) else raw[2]),
            should_respawn=(raw.get('should_respawn') if isinstance(raw, dict) else raw[3])
        )
