# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_type import ItemType
from .market_order_type import MarketOrderType



@dataclass
class MarketTradeEvent:
    claim_entity_id: int = 0
    listing_entity_id: int = 0
    listing_type: MarketOrderType = 0
    buyer_entity_id: int = 0
    seller_entity_id: int = 0
    item_id: int = 0
    item_type: ItemType = 0
    quantity: int = 0
    unit_price: int = 0
    listing_remaining_quantity: int = 0
    timestamp: int = 0

    @classmethod
    def from_row(cls, raw) -> 'MarketTradeEvent':
        if raw is None:
            return cls()
        return cls(
            claim_entity_id=(raw.get('claim_entity_id') if isinstance(raw, dict) else raw[0]),
            listing_entity_id=(raw.get('listing_entity_id') if isinstance(raw, dict) else raw[1]),
            listing_type=MarketOrderType.from_row((raw.get('listing_type') if isinstance(raw, dict) else raw[2])),
            buyer_entity_id=(raw.get('buyer_entity_id') if isinstance(raw, dict) else raw[3]),
            seller_entity_id=(raw.get('seller_entity_id') if isinstance(raw, dict) else raw[4]),
            item_id=(raw.get('item_id') if isinstance(raw, dict) else raw[5]),
            item_type=ItemType.from_row((raw.get('item_type') if isinstance(raw, dict) else raw[6])),
            quantity=(raw.get('quantity') if isinstance(raw, dict) else raw[7]),
            unit_price=(raw.get('unit_price') if isinstance(raw, dict) else raw[8]),
            listing_remaining_quantity=(raw.get('listing_remaining_quantity') if isinstance(raw, dict) else raw[9]),
            timestamp=((raw.get('timestamp') if isinstance(raw, dict) else raw[10])['__timestamp_micros_since_unix_epoch__'] if isinstance((raw.get('timestamp') if isinstance(raw, dict) else raw[10]), dict) else ((raw.get('timestamp') if isinstance(raw, dict) else raw[10])[0] if isinstance((raw.get('timestamp') if isinstance(raw, dict) else raw[10]), list) else (raw.get('timestamp') if isinstance(raw, dict) else raw[10])))
        )
