# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class MigrationAchievementsParams:
    id: int = 0
    allow_destructive: bool = False
    grant_if_already_owned: bool = False

    @classmethod
    def from_row(cls, raw) -> 'MigrationAchievementsParams':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            allow_destructive=(raw.get('allow_destructive') if isinstance(raw, dict) else raw[1]),
            grant_if_already_owned=(raw.get('grant_if_already_owned') if isinstance(raw, dict) else raw[2])
        )
