# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class MigrationBuildingDescParams:
    id: int = 0
    allow_building_health_change: bool = False

    @classmethod
    def from_row(cls, raw) -> 'MigrationBuildingDescParams':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            allow_building_health_change=(raw.get('allow_building_health_change') if isinstance(raw, dict) else raw[1])
        )
