# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ModerationActionLogEntry:
    entity_id: int = 0
    report_entity_id: int = 0
    reported_player_entity_id: int = 0
    admin_name: str = ''
    reported_player_username: str = ''
    action_type: str = ''
    moderation_notice: str = ''
    details: str = ''
    timestamp: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ModerationActionLogEntry':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            report_entity_id=(raw.get('report_entity_id') if isinstance(raw, dict) else raw[1]),
            reported_player_entity_id=(raw.get('reported_player_entity_id') if isinstance(raw, dict) else raw[2]),
            admin_name=(raw.get('admin_name') if isinstance(raw, dict) else raw[3]),
            reported_player_username=(raw.get('reported_player_username') if isinstance(raw, dict) else raw[4]),
            action_type=(raw.get('action_type') if isinstance(raw, dict) else raw[5]),
            moderation_notice=(raw.get('moderation_notice') if isinstance(raw, dict) else raw[6]),
            details=(raw.get('details') if isinstance(raw, dict) else raw[7]),
            timestamp=(raw.get('timestamp') if isinstance(raw, dict) else raw[8])
        )
