# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .surface_type import SurfaceType



@dataclass
class MovementSpeed:
    surface_type: SurfaceType = 0
    speed: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'MovementSpeed':
        if raw is None:
            return cls()
        return cls(
            surface_type=SurfaceType.from_row((raw.get('surface_type') if isinstance(raw, dict) else raw[0])),
            speed=(raw.get('speed') if isinstance(raw, dict) else raw[1])
        )
