# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .npc_watchtower_placement import NpcWatchtowerPlacement



@dataclass
class NpcPlaceWatchtowersMsg:
    watchtowers: list = field(default_factory=list)
    energy: int = 0
    upkeep: int = 0

    @classmethod
    def from_row(cls, raw) -> 'NpcPlaceWatchtowersMsg':
        if raw is None:
            return cls()
        return cls(
            watchtowers=[NpcWatchtowerPlacement.from_row(_item) for _item in ((raw.get('watchtowers') if isinstance(raw, dict) else raw[0]) or [])],
            energy=(raw.get('energy') if isinstance(raw, dict) else raw[1]),
            upkeep=(raw.get('upkeep') if isinstance(raw, dict) else raw[2])
        )
