# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .player_paving_place_tile_request import PlayerPavingPlaceTileRequest



@dataclass
class PavingPlaceTileStartEvent:
    actor_id: int = 0
    request: PlayerPavingPlaceTileRequest = 0

    @classmethod
    def from_row(cls, raw) -> 'PavingPlaceTileStartEvent':
        if raw is None:
            return cls()
        return cls(
            actor_id=(raw.get('actor_id') if isinstance(raw, dict) else raw[0]),
            request=PlayerPavingPlaceTileRequest.from_row((raw.get('request') if isinstance(raw, dict) else raw[1]))
        )
