# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class PermissionGroup(IntEnum):
    PLAYER = 0
    CLAIM = 1
    EMPIRE = 2
    EVERYONE = 3


    @classmethod
    def from_row(cls, raw) -> 'PermissionGroup':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for Player
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse PermissionGroup from {raw!r}')
