# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PermissionState:
    entity_id: int = 0
    ordained_entity_id: int = 0
    allowed_entity_id: int = 0
    group: int = 0
    rank: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PermissionState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            ordained_entity_id=(raw.get('ordained_entity_id') if isinstance(raw, dict) else raw[1]),
            allowed_entity_id=(raw.get('allowed_entity_id') if isinstance(raw, dict) else raw[2]),
            group=(raw.get('group') if isinstance(raw, dict) else raw[3]),
            rank=(raw.get('rank') if isinstance(raw, dict) else raw[4])
        )
