# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class Permission(IntEnum):
    PENDINGVISITOR = 0
    VISITOR = 1
    USAGE = 2
    INVENTORY = 3
    BUILD = 4
    COOWNER = 5
    OVERRIDENOACCESS = 6
    OWNER = 7


    @classmethod
    def from_row(cls, raw) -> 'Permission':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for PendingVisitor
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse Permission from {raw!r}')
