# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .placeable_growth_outcome import PlaceableGrowthOutcome



@dataclass
class PlaceableGrowthDesc:
    id: int = 0
    placeable_id: int = 0
    time: list = field(default_factory=list)
    outcomes: list = field(default_factory=list)
    show_time_left: bool = False

    @classmethod
    def from_row(cls, raw) -> 'PlaceableGrowthDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            placeable_id=(raw.get('placeable_id') if isinstance(raw, dict) else raw[1]),
            time=[_item for _item in ((raw.get('time') if isinstance(raw, dict) else raw[2]) or [])],
            outcomes=[PlaceableGrowthOutcome.from_row(_item) for _item in ((raw.get('outcomes') if isinstance(raw, dict) else raw[3]) or [])],
            show_time_left=(raw.get('show_time_left') if isinstance(raw, dict) else raw[4])
        )
