# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .rarity import Rarity



@dataclass
class PlaceableDesc:
    id: int = 0
    name: str = ''
    tag: str = ''
    tier: int = 0
    description: str = ''
    rarity: Rarity = 0
    model_asset_name: str = ''
    icon_asset_name: str = ''
    max_health: int = 0
    visible_to_others: bool = False
    spawns_on_land: bool = False
    land_elevation_min: int = 0
    land_elevation_max: int = 0
    spawns_in_water: bool = False
    water_depth_min: int = 0
    water_depth_max: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlaceableDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            tag=(raw.get('tag') if isinstance(raw, dict) else raw[2]),
            tier=(raw.get('tier') if isinstance(raw, dict) else raw[3]),
            description=(raw.get('description') if isinstance(raw, dict) else raw[4]),
            rarity=Rarity.from_row((raw.get('rarity') if isinstance(raw, dict) else raw[5])),
            model_asset_name=(raw.get('model_asset_name') if isinstance(raw, dict) else raw[6]),
            icon_asset_name=(raw.get('icon_asset_name') if isinstance(raw, dict) else raw[7]),
            max_health=(raw.get('max_health') if isinstance(raw, dict) else raw[8]),
            visible_to_others=(raw.get('visible_to_others') if isinstance(raw, dict) else raw[9]),
            spawns_on_land=(raw.get('spawns_on_land') if isinstance(raw, dict) else raw[10]),
            land_elevation_min=(raw.get('land_elevation_min') if isinstance(raw, dict) else raw[11]),
            land_elevation_max=(raw.get('land_elevation_max') if isinstance(raw, dict) else raw[12]),
            spawns_in_water=(raw.get('spawns_in_water') if isinstance(raw, dict) else raw[13]),
            water_depth_min=(raw.get('water_depth_min') if isinstance(raw, dict) else raw[14]),
            water_depth_max=(raw.get('water_depth_max') if isinstance(raw, dict) else raw[15])
        )
