# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .player_placeable_place_request import PlayerPlaceablePlaceRequest



@dataclass
class PlaceablePlaceStartEvent:
    actor_id: int = 0
    request: PlayerPlaceablePlaceRequest = 0

    @classmethod
    def from_row(cls, raw) -> 'PlaceablePlaceStartEvent':
        if raw is None:
            return cls()
        return cls(
            actor_id=(raw.get('actor_id') if isinstance(raw, dict) else raw[0]),
            request=PlayerPlaceablePlaceRequest.from_row((raw.get('request') if isinstance(raw, dict) else raw[1]))
        )
