# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlaceableGroupDesc:
    id: int = 0
    name: str = ''
    placement_limit: int = 0
    placeable_ids: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'PlaceableGroupDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            placement_limit=(raw.get('placement_limit') if isinstance(raw, dict) else raw[2]),
            placeable_ids=[_item for _item in ((raw.get('placeable_ids') if isinstance(raw, dict) else raw[3]) or [])]
        )
