# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerItemUseRequest:
    pocket_index: int = 0
    arg_entity_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerItemUseRequest':
        if raw is None:
            return cls()
        return cls(
            pocket_index=(raw.get('pocket_index') if isinstance(raw, dict) else raw[0]),
            arg_entity_id=(raw.get('arg_entity_id') if isinstance(raw, dict) else raw[1])
        )
