# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerUsernameState:
    entity_id: int = 0
    username: str = ''

    @classmethod
    def from_row(cls, raw) -> 'PlayerUsernameState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            username=(raw.get('username') if isinstance(raw, dict) else raw[1])
        )
