# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .pocket_key import PocketKey



@dataclass
class PlayerItemDropRequest:
    pocket: PocketKey = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerItemDropRequest':
        if raw is None:
            return cls()
        return cls(
            pocket=PocketKey.from_row((raw.get('pocket') if isinstance(raw, dict) else raw[0]))
        )
