# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_large_message import OffsetCoordinatesLargeMessage



@dataclass
class PlayerTerraformSetFinalTargetRequest:
    coordinates: OffsetCoordinatesLargeMessage = 0
    final_height_target: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerTerraformSetFinalTargetRequest':
        if raw is None:
            return cls()
        return cls(
            coordinates=OffsetCoordinatesLargeMessage.from_row((raw.get('coordinates') if isinstance(raw, dict) else raw[0])),
            final_height_target=(raw.get('final_height_target') if isinstance(raw, dict) else raw[1])
        )
