# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerPausePlayTimerRequest:
    player_entity_id: int = 0
    paused: bool = False

    @classmethod
    def from_row(cls, raw) -> 'PlayerPausePlayTimerRequest':
        if raw is None:
            return cls()
        return cls(
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[0]),
            paused=(raw.get('paused') if isinstance(raw, dict) else raw[1])
        )
