# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_float import OffsetCoordinatesFloat



@dataclass
class PlayerMoveRequest:
    timestamp: int = 0
    destination: OffsetCoordinatesFloat | None = None
    origin: OffsetCoordinatesFloat | None = None
    duration: float = 0.0
    move_type: int = 0
    is_rp_walk: bool = False

    @classmethod
    def from_row(cls, raw) -> 'PlayerMoveRequest':
        if raw is None:
            return cls()
        return cls(
            timestamp=(raw.get('timestamp') if isinstance(raw, dict) else raw[0]),
            destination=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (OffsetCoordinatesFloat.from_row(_v[1])))((raw.get('destination') if isinstance(raw, dict) else raw[1])),
            origin=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (OffsetCoordinatesFloat.from_row(_v[1])))((raw.get('origin') if isinstance(raw, dict) else raw[2])),
            duration=(raw.get('duration') if isinstance(raw, dict) else raw[3]),
            move_type=(raw.get('move_type') if isinstance(raw, dict) else raw[4]),
            is_rp_walk=(raw.get('is_rp_walk') if isinstance(raw, dict) else raw[5])
        )
