# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerBuildingSetNicknameRequest:
    building_entity_id: int = 0
    nickname: str = ''

    @classmethod
    def from_row(cls, raw) -> 'PlayerBuildingSetNicknameRequest':
        if raw is None:
            return cls()
        return cls(
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[0]),
            nickname=(raw.get('nickname') if isinstance(raw, dict) else raw[1])
        )
