# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerHousingCustomizationState:
    entity_id: int = 0
    wall_collectible_id: int = 0
    floor_collectible_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerHousingCustomizationState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            wall_collectible_id=(raw.get('wall_collectible_id') if isinstance(raw, dict) else raw[1]),
            floor_collectible_id=(raw.get('floor_collectible_id') if isinstance(raw, dict) else raw[2])
        )
