# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_stack import ItemStack



@dataclass
class PlayerBarterStallOrderCreateRequest:
    shop_entity_id: int = 0
    remaining_stock: int = 0
    offer_items: list = field(default_factory=list)
    required_items: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'PlayerBarterStallOrderCreateRequest':
        if raw is None:
            return cls()
        return cls(
            shop_entity_id=(raw.get('shop_entity_id') if isinstance(raw, dict) else raw[0]),
            remaining_stock=(raw.get('remaining_stock') if isinstance(raw, dict) else raw[1]),
            offer_items=[ItemStack.from_row(_item) for _item in ((raw.get('offer_items') if isinstance(raw, dict) else raw[2]) or [])],
            required_items=[ItemStack.from_row(_item) for _item in ((raw.get('required_items') if isinstance(raw, dict) else raw[3]) or [])]
        )
