# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class PlayerActionType(IntEnum):
    NONE = 0
    ATTACK = 1
    DESTROYPAVING = 2
    STATIONARYEMOTE = 3
    EXTRACT = 4
    PAVETILE = 5
    SPAWNCARGO = 6
    BUILD = 7
    DECONSTRUCT = 8
    REPAIRBUILDING = 9
    RESUPPLYCLAIM = 10
    CARGOPICKUP = 11
    TERRAFORM = 12
    DEPLOYDEPLOYABLE = 13
    STOREDEPLOYABLE = 14
    SLEEP = 15
    TELEPORT = 16
    DEATH = 17
    CLIMB = 18
    USEITEM = 19
    CRAFT = 20
    CONVERTITEMS = 21
    PLAYERMOVE = 22
    DEPLOYABLEMOVE = 23
    RESUPPLYEMPIRENODE = 24
    SETHOME = 25
    USEELEVATOR = 26
    MOBILEEMOTE = 27
    PLACEPILLARSHAPING = 28
    DESTROYPILLARSHAPING = 29
    ABILITYCUSTOM = 30
    PROSPECT = 31
    PLACEPLACEABLE = 32
    INTERACTPLACEABLE = 33


    @classmethod
    def from_row(cls, raw) -> 'PlayerActionType':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for None
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse PlayerActionType from {raw!r}')
