# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerRetrieveLostItemRequest:
    building_entity_id: int = 0
    item_id: int = 0
    is_cargo: bool = False
    durability: int = 0
    target_inventory_entity_id: int = 0
    target_inventory_index: object | None = None

    @classmethod
    def from_row(cls, raw) -> 'PlayerRetrieveLostItemRequest':
        if raw is None:
            return cls()
        return cls(
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[0]),
            item_id=(raw.get('item_id') if isinstance(raw, dict) else raw[1]),
            is_cargo=(raw.get('is_cargo') if isinstance(raw, dict) else raw[2]),
            durability=(raw.get('durability') if isinstance(raw, dict) else raw[3]),
            target_inventory_entity_id=(raw.get('target_inventory_entity_id') if isinstance(raw, dict) else raw[4]),
            target_inventory_index=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]))((raw.get('target_inventory_index') if isinstance(raw, dict) else raw[5]))
        )
