# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .pocket_key import PocketKey



@dataclass
class PlayerItemStackSplitRequest:
    from_pocket: PocketKey = 0
    item_id: int = 0
    new_stack_count: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerItemStackSplitRequest':
        if raw is None:
            return cls()
        return cls(
            from_pocket=PocketKey.from_row((raw.get('from_pocket') if isinstance(raw, dict) else raw[0])),
            item_id=(raw.get('item_id') if isinstance(raw, dict) else raw[1]),
            new_stack_count=(raw.get('new_stack_count') if isinstance(raw, dict) else raw[2])
        )
