# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .item_type import ItemType



@dataclass
class PlayerPostOrderRequest:
    building_entity_id: int = 0
    item_id: int = 0
    item_type: ItemType = 0
    max_unit_price: int = 0
    quantity: int = 0
    persist_order: bool = False
    coins_spent: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerPostOrderRequest':
        if raw is None:
            return cls()
        return cls(
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[0]),
            item_id=(raw.get('item_id') if isinstance(raw, dict) else raw[1]),
            item_type=ItemType.from_row((raw.get('item_type') if isinstance(raw, dict) else raw[2])),
            max_unit_price=(raw.get('max_unit_price') if isinstance(raw, dict) else raw[3]),
            quantity=(raw.get('quantity') if isinstance(raw, dict) else raw[4]),
            persist_order=(raw.get('persist_order') if isinstance(raw, dict) else raw[5]),
            coins_spent=(raw.get('coins_spent') if isinstance(raw, dict) else raw[6])
        )
