# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerClaimAddMemberRequest:
    player_name: str = ''
    claim_entity_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerClaimAddMemberRequest':
        if raw is None:
            return cls()
        return cls(
            player_name=(raw.get('player_name') if isinstance(raw, dict) else raw[0]),
            claim_entity_id=(raw.get('claim_entity_id') if isinstance(raw, dict) else raw[1])
        )
