# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_large_message import OffsetCoordinatesLargeMessage



@dataclass
class PlayerTerraformRequest:
    coordinates: OffsetCoordinatesLargeMessage = 0
    start_new: bool = False
    timestamp: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerTerraformRequest':
        if raw is None:
            return cls()
        return cls(
            coordinates=OffsetCoordinatesLargeMessage.from_row((raw.get('coordinates') if isinstance(raw, dict) else raw[0])),
            start_new=(raw.get('start_new') if isinstance(raw, dict) else raw[1]),
            timestamp=(raw.get('timestamp') if isinstance(raw, dict) else raw[2])
        )
