# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .player_death_timer import PlayerDeathTimer



@dataclass
class PlayerDeathStartEvent:
    actor_id: int = 0
    timer: PlayerDeathTimer = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerDeathStartEvent':
        if raw is None:
            return cls()
        return cls(
            actor_id=(raw.get('actor_id') if isinstance(raw, dict) else raw[0]),
            timer=PlayerDeathTimer.from_row((raw.get('timer') if isinstance(raw, dict) else raw[1]))
        )
