# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_large_message import OffsetCoordinatesLargeMessage



@dataclass
class PlayerPillarShapingPlaceRequest:
    coordinates: OffsetCoordinatesLargeMessage = 0
    pillar_type_id: int = 0
    timestamp: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerPillarShapingPlaceRequest':
        if raw is None:
            return cls()
        return cls(
            coordinates=OffsetCoordinatesLargeMessage.from_row((raw.get('coordinates') if isinstance(raw, dict) else raw[0])),
            pillar_type_id=(raw.get('pillar_type_id') if isinstance(raw, dict) else raw[1]),
            timestamp=(raw.get('timestamp') if isinstance(raw, dict) else raw[2])
        )
