# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerHousingEvictPlayerTimer:
    scheduled_id: int = 0
    scheduled_at: object = 0
    building_entity_id: int = 0
    player_entity_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerHousingEvictPlayerTimer':
        if raw is None:
            return cls()
        return cls(
            scheduled_id=(raw.get('scheduled_id') if isinstance(raw, dict) else raw[0]),
            scheduled_at=(raw.get('scheduled_at') if isinstance(raw, dict) else raw[1]),
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[2]),
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[3])
        )
