# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerDiscoverEntitiesRequest:
    discovered_entities_id: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'PlayerDiscoverEntitiesRequest':
        if raw is None:
            return cls()
        return cls(
            discovered_entities_id=[_item for _item in ((raw.get('discovered_entities_id') if isinstance(raw, dict) else raw[0]) or [])]
        )
