# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerCraftCollectRequest:
    pocket_id: int = 0
    recipe_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerCraftCollectRequest':
        if raw is None:
            return cls()
        return cls(
            pocket_id=(raw.get('pocket_id') if isinstance(raw, dict) else raw[0]),
            recipe_id=(raw.get('recipe_id') if isinstance(raw, dict) else raw[1])
        )
