# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerCraftContinueRequest:
    progressive_action_entity_id: int = 0
    timestamp: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerCraftContinueRequest':
        if raw is None:
            return cls()
        return cls(
            progressive_action_entity_id=(raw.get('progressive_action_entity_id') if isinstance(raw, dict) else raw[0]),
            timestamp=(raw.get('timestamp') if isinstance(raw, dict) else raw[1])
        )
