# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerItemConvertRequest:
    conversion_recipe_id: int = 0
    location_context: int = 0
    count: int = 0
    timestamp: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerItemConvertRequest':
        if raw is None:
            return cls()
        return cls(
            conversion_recipe_id=(raw.get('conversion_recipe_id') if isinstance(raw, dict) else raw[0]),
            location_context=(raw.get('location_context') if isinstance(raw, dict) else raw[1]),
            count=(raw.get('count') if isinstance(raw, dict) else raw[2]),
            timestamp=(raw.get('timestamp') if isinstance(raw, dict) else raw[3])
        )
