# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerDroppedInventoryPickUpRequest:
    dropped_inventory_entity_id: int = 0
    item_id: int = 0
    pocket_index: int = 0
    to_deployable: bool = False

    @classmethod
    def from_row(cls, raw) -> 'PlayerDroppedInventoryPickUpRequest':
        if raw is None:
            return cls()
        return cls(
            dropped_inventory_entity_id=(raw.get('dropped_inventory_entity_id') if isinstance(raw, dict) else raw[0]),
            item_id=(raw.get('item_id') if isinstance(raw, dict) else raw[1]),
            pocket_index=(raw.get('pocket_index') if isinstance(raw, dict) else raw[2]),
            to_deployable=(raw.get('to_deployable') if isinstance(raw, dict) else raw[3])
        )
