# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_small_message import OffsetCoordinatesSmallMessage



@dataclass
class PlayerProjectSitePlaceRequest:
    coordinates: OffsetCoordinatesSmallMessage = 0
    construction_recipe_id: int = 0
    resource_placement_recipe_id: int = 0
    facing_direction: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerProjectSitePlaceRequest':
        if raw is None:
            return cls()
        return cls(
            coordinates=OffsetCoordinatesSmallMessage.from_row((raw.get('coordinates') if isinstance(raw, dict) else raw[0])),
            construction_recipe_id=(raw.get('construction_recipe_id') if isinstance(raw, dict) else raw[1]),
            resource_placement_recipe_id=(raw.get('resource_placement_recipe_id') if isinstance(raw, dict) else raw[2]),
            facing_direction=(raw.get('facing_direction') if isinstance(raw, dict) else raw[3])
        )
