# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerSettingsState:
    entity_id: int = 0
    fill_player_inventory: bool = False
    fill_deployable_inventory_first: bool = False

    @classmethod
    def from_row(cls, raw) -> 'PlayerSettingsState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            fill_player_inventory=(raw.get('fill_player_inventory') if isinstance(raw, dict) else raw[1]),
            fill_deployable_inventory_first=(raw.get('fill_deployable_inventory_first') if isinstance(raw, dict) else raw[2])
        )
