# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerEditOrderRequest:
    building_entity_id: int = 0
    order_entity_id: int = 0
    coins: int = 0
    quantity: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerEditOrderRequest':
        if raw is None:
            return cls()
        return cls(
            building_entity_id=(raw.get('building_entity_id') if isinstance(raw, dict) else raw[0]),
            order_entity_id=(raw.get('order_entity_id') if isinstance(raw, dict) else raw[1]),
            coins=(raw.get('coins') if isinstance(raw, dict) else raw[2]),
            quantity=(raw.get('quantity') if isinstance(raw, dict) else raw[3])
        )
