# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class PlayerSignedOutReason(IntEnum):
    INACTIVITY = 0
    ADMINACTION = 1
    SERVERACTION = 2


    @classmethod
    def from_row(cls, raw) -> 'PlayerSignedOutReason':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for Inactivity
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse PlayerSignedOutReason from {raw!r}')
