# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerClaimSetMemberPermissionsRequest:
    player_entity_id: int = 0
    claim_entity_id: int = 0
    inventory: bool = False
    build: bool = False
    officer: bool = False
    co_owner: bool = False

    @classmethod
    def from_row(cls, raw) -> 'PlayerClaimSetMemberPermissionsRequest':
        if raw is None:
            return cls()
        return cls(
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[0]),
            claim_entity_id=(raw.get('claim_entity_id') if isinstance(raw, dict) else raw[1]),
            inventory=(raw.get('inventory') if isinstance(raw, dict) else raw[2]),
            build=(raw.get('build') if isinstance(raw, dict) else raw[3]),
            officer=(raw.get('officer') if isinstance(raw, dict) else raw[4]),
            co_owner=(raw.get('co_owner') if isinstance(raw, dict) else raw[5])
        )
