# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerConvertCollectibleToDeedRequest:
    vault_index: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerConvertCollectibleToDeedRequest':
        if raw is None:
            return cls()
        return cls(
            vault_index=(raw.get('vault_index') if isinstance(raw, dict) else raw[0])
        )
