# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_small_message import OffsetCoordinatesSmallMessage



@dataclass
class PlayerPavingDestroyTileRequest:
    coordinates: OffsetCoordinatesSmallMessage = 0
    timestamp: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerPavingDestroyTileRequest':
        if raw is None:
            return cls()
        return cls(
            coordinates=OffsetCoordinatesSmallMessage.from_row((raw.get('coordinates') if isinstance(raw, dict) else raw[0])),
            timestamp=(raw.get('timestamp') if isinstance(raw, dict) else raw[1])
        )
