# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerSkipQueueMsg:
    player_identity: object = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerSkipQueueMsg':
        if raw is None:
            return cls()
        return cls(
            player_identity=(raw.get('player_identity') if isinstance(raw, dict) else raw[0])
        )
