# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_small_message import OffsetCoordinatesSmallMessage



@dataclass
class PlayerEmoteRequest:
    emote_id: int = 0
    face: OffsetCoordinatesSmallMessage | None = None

    @classmethod
    def from_row(cls, raw) -> 'PlayerEmoteRequest':
        if raw is None:
            return cls()
        return cls(
            emote_id=(raw.get('emote_id') if isinstance(raw, dict) else raw[0]),
            face=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (OffsetCoordinatesSmallMessage.from_row(_v[1])))((raw.get('face') if isinstance(raw, dict) else raw[1]))
        )
