# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerVoteAnswerRequest:
    vote_entity_id: int = 0
    accept: bool = False

    @classmethod
    def from_row(cls, raw) -> 'PlayerVoteAnswerRequest':
        if raw is None:
            return cls()
        return cls(
            vote_entity_id=(raw.get('vote_entity_id') if isinstance(raw, dict) else raw[0]),
            accept=(raw.get('accept') if isinstance(raw, dict) else raw[1])
        )
