# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .permission import Permission
from .permission_group import PermissionGroup



@dataclass
class PlayerPermissionEditRequest:
    ordained_entity_id: int = 0
    allowed_entity_id: int = 0
    permission: Permission | None = None
    group: PermissionGroup = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerPermissionEditRequest':
        if raw is None:
            return cls()
        return cls(
            ordained_entity_id=(raw.get('ordained_entity_id') if isinstance(raw, dict) else raw[0]),
            allowed_entity_id=(raw.get('allowed_entity_id') if isinstance(raw, dict) else raw[1]),
            permission=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (Permission.from_row(_v[1])))((raw.get('permission') if isinstance(raw, dict) else raw[2])),
            group=PermissionGroup.from_row((raw.get('group') if isinstance(raw, dict) else raw[3]))
        )
