# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_float import OffsetCoordinatesFloat



@dataclass
class PlayerClimbRequest:
    destination: OffsetCoordinatesFloat = 0
    origin: OffsetCoordinatesFloat = 0
    timestamp: int = 0
    climb_type: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerClimbRequest':
        if raw is None:
            return cls()
        return cls(
            destination=OffsetCoordinatesFloat.from_row((raw.get('destination') if isinstance(raw, dict) else raw[0])),
            origin=OffsetCoordinatesFloat.from_row((raw.get('origin') if isinstance(raw, dict) else raw[1])),
            timestamp=(raw.get('timestamp') if isinstance(raw, dict) else raw[2]),
            climb_type=(raw.get('climb_type') if isinstance(raw, dict) else raw[3])
        )
