# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PlayerBarterStallOrderAccept:
    trade_order_entity_id: int = 0
    shop_entity_id: int = 0
    amount: int = 0

    @classmethod
    def from_row(cls, raw) -> 'PlayerBarterStallOrderAccept':
        if raw is None:
            return cls()
        return cls(
            trade_order_entity_id=(raw.get('trade_order_entity_id') if isinstance(raw, dict) else raw[0]),
            shop_entity_id=(raw.get('shop_entity_id') if isinstance(raw, dict) else raw[1]),
            amount=(raw.get('amount') if isinstance(raw, dict) else raw[2])
        )
