# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PremiumItemDesc:
    id: int = 0
    name: str = ''
    description: str = ''
    image_address: str = ''
    collectible_ids: list = field(default_factory=list)
    price: int = 0
    base_price: int = 0
    quantity: int = 0
    sorting_priority: int = 0
    is_enabled: bool = False

    @classmethod
    def from_row(cls, raw) -> 'PremiumItemDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            description=(raw.get('description') if isinstance(raw, dict) else raw[2]),
            image_address=(raw.get('image_address') if isinstance(raw, dict) else raw[3]),
            collectible_ids=[_item for _item in ((raw.get('collectible_ids') if isinstance(raw, dict) else raw[4]) or [])],
            price=(raw.get('price') if isinstance(raw, dict) else raw[5]),
            base_price=(raw.get('base_price') if isinstance(raw, dict) else raw[6]),
            quantity=(raw.get('quantity') if isinstance(raw, dict) else raw[7]),
            sorting_priority=(raw.get('sorting_priority') if isinstance(raw, dict) else raw[8]),
            is_enabled=(raw.get('is_enabled') if isinstance(raw, dict) else raw[9])
        )
