# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class PreviousPlayerUsernameState:
    identity: str = 0
    name: str = ''
    lower_case_name: str = ''

    @classmethod
    def from_row(cls, raw) -> 'PreviousPlayerUsernameState':
        if raw is None:
            return cls()
        return cls(
            identity=((raw.get('identity') if isinstance(raw, dict) else raw[0])['__identity__'] if isinstance((raw.get('identity') if isinstance(raw, dict) else raw[0]), dict) else (raw.get('identity') if isinstance(raw, dict) else raw[0])),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            lower_case_name=(raw.get('lower_case_name') if isinstance(raw, dict) else raw[2])
        )
