# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .move_validation_params_desc import MoveValidationParamsDesc



@dataclass
class PrivateParametersDesc:
    version: int = 0
    move_validation: MoveValidationParamsDesc = 0

    @classmethod
    def from_row(cls, raw) -> 'PrivateParametersDesc':
        if raw is None:
            return cls()
        return cls(
            version=(raw.get('version') if isinstance(raw, dict) else raw[0]),
            move_validation=MoveValidationParamsDesc.from_row((raw.get('move_validation') if isinstance(raw, dict) else raw[1]))
        )
