# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .player_project_site_advance_project_request import PlayerProjectSiteAdvanceProjectRequest



@dataclass
class ProjectSiteAdvanceProjectStartEvent:
    actor_id: int = 0
    request: PlayerProjectSiteAdvanceProjectRequest = 0

    @classmethod
    def from_row(cls, raw) -> 'ProjectSiteAdvanceProjectStartEvent':
        if raw is None:
            return cls()
        return cls(
            actor_id=(raw.get('actor_id') if isinstance(raw, dict) else raw[0]),
            request=PlayerProjectSiteAdvanceProjectRequest.from_row((raw.get('request') if isinstance(raw, dict) else raw[1]))
        )
