# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .quest_requirement import QuestRequirement
from .quest_reward import QuestReward



@dataclass
class QuestChainDesc:
    id: int = 0
    name: str = ''
    is_hint: bool = False
    stages: list = field(default_factory=list)
    requirements: list = field(default_factory=list)
    rewards: list = field(default_factory=list)
    implicit_rewards: list = field(default_factory=list)
    unstartable: bool = False
    is_secret: bool = False

    @classmethod
    def from_row(cls, raw) -> 'QuestChainDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            is_hint=(raw.get('is_hint') if isinstance(raw, dict) else raw[2]),
            stages=[_item for _item in ((raw.get('stages') if isinstance(raw, dict) else raw[3]) or [])],
            requirements=[QuestRequirement.from_row(_item) for _item in ((raw.get('requirements') if isinstance(raw, dict) else raw[4]) or [])],
            rewards=[QuestReward.from_row(_item) for _item in ((raw.get('rewards') if isinstance(raw, dict) else raw[5]) or [])],
            implicit_rewards=[QuestReward.from_row(_item) for _item in ((raw.get('implicit_rewards') if isinstance(raw, dict) else raw[6]) or [])],
            unstartable=(raw.get('unstartable') if isinstance(raw, dict) else raw[7]),
            is_secret=(raw.get('is_secret') if isinstance(raw, dict) else raw[8])
        )
