# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class RecoverDeployableMsg:
    player_entity_id: int = 0
    deployable_entity_id: int = 0
    deployable_desc_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'RecoverDeployableMsg':
        if raw is None:
            return cls()
        return cls(
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[0]),
            deployable_entity_id=(raw.get('deployable_entity_id') if isinstance(raw, dict) else raw[1]),
            deployable_desc_id=(raw.get('deployable_desc_id') if isinstance(raw, dict) else raw[2])
        )
