# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class RegionSignInParameters:
    region_id: int = 0
    is_signing_in_blocked: bool = False
    max_signed_in_players: int = 0
    max_queue_length: int = 0
    queue_length_tolerance: int = 0
    grace_period_seconds: int = 0

    @classmethod
    def from_row(cls, raw) -> 'RegionSignInParameters':
        if raw is None:
            return cls()
        return cls(
            region_id=(raw.get('region_id') if isinstance(raw, dict) else raw[0]),
            is_signing_in_blocked=(raw.get('is_signing_in_blocked') if isinstance(raw, dict) else raw[1]),
            max_signed_in_players=(raw.get('max_signed_in_players') if isinstance(raw, dict) else raw[2]),
            max_queue_length=(raw.get('max_queue_length') if isinstance(raw, dict) else raw[3]),
            queue_length_tolerance=(raw.get('queue_length_tolerance') if isinstance(raw, dict) else raw[4]),
            grace_period_seconds=(raw.get('grace_period_seconds') if isinstance(raw, dict) else raw[5])
        )
