# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class RegionControlInfo:
    region_id: int = 0
    initialized: bool = False
    allow_players: bool = False
    allow_player_spawns: bool = False

    @classmethod
    def from_row(cls, raw) -> 'RegionControlInfo':
        if raw is None:
            return cls()
        return cls(
            region_id=(raw.get('region_id') if isinstance(raw, dict) else raw[0]),
            initialized=(raw.get('initialized') if isinstance(raw, dict) else raw[1]),
            allow_players=(raw.get('allow_players') if isinstance(raw, dict) else raw[2]),
            allow_player_spawns=(raw.get('allow_player_spawns') if isinstance(raw, dict) else raw[3])
        )
