# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class RegionPopulationInfo:
    region_id: int = 0
    signed_in_players: int = 0
    players_in_queue: int = 0

    @classmethod
    def from_row(cls, raw) -> 'RegionPopulationInfo':
        if raw is None:
            return cls()
        return cls(
            region_id=(raw.get('region_id') if isinstance(raw, dict) else raw[0]),
            signed_in_players=(raw.get('signed_in_players') if isinstance(raw, dict) else raw[1]),
            players_in_queue=(raw.get('players_in_queue') if isinstance(raw, dict) else raw[2])
        )
