# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class RegionExplorationInfo:
    region_id: int = 0
    counts_toward_achievements: bool = False

    @classmethod
    def from_row(cls, raw) -> 'RegionExplorationInfo':
        if raw is None:
            return cls()
        return cls(
            region_id=(raw.get('region_id') if isinstance(raw, dict) else raw[0]),
            counts_toward_achievements=(raw.get('counts_toward_achievements') if isinstance(raw, dict) else raw[1])
        )
