# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ReportEntityMessage:
    entity_id: int = 0
    report_type: str = ''
    message: str = ''

    @classmethod
    def from_row(cls, raw) -> 'ReportEntityMessage':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            report_type=(raw.get('report_type') if isinstance(raw, dict) else raw[1]),
            message=(raw.get('message') if isinstance(raw, dict) else raw[2])
        )
