# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .move_validation_strike_counter_state import MoveValidationStrikeCounterState
from .offset_coordinates_float import OffsetCoordinatesFloat



@dataclass
class ResetMobileEntityTimer:
    scheduled_id: int = 0
    scheduled_at: object = 0
    owner_entity_id: int = 0
    position: int = 0
    strike_counter_to_update: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ResetMobileEntityTimer':
        if raw is None:
            return cls()
        return cls(
            scheduled_id=(raw.get('scheduled_id') if isinstance(raw, dict) else raw[0]),
            scheduled_at=(raw.get('scheduled_at') if isinstance(raw, dict) else raw[1]),
            owner_entity_id=(raw.get('owner_entity_id') if isinstance(raw, dict) else raw[2]),
            position=(raw.get('position') if isinstance(raw, dict) else raw[3]),
            strike_counter_to_update=(raw.get('strike_counter_to_update') if isinstance(raw, dict) else raw[4])
        )
