# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .biome import Biome
from .experience_stack_f32 import ExperienceStackF32
from .input_item_stack import InputItemStack
from .level_requirement import LevelRequirement
from .tool_requirement import ToolRequirement



@dataclass
class ResourcePlacementRecipeDesc:
    id: int = 0
    name: str = ''
    time_requirement: float = 0.0
    stamina_requirement: float = 0.0
    consumed_resource: int = 0
    required_interior_tier: int = 0
    level_requirements: list = field(default_factory=list)
    tool_requirements: list = field(default_factory=list)
    consumed_item_stacks: list = field(default_factory=list)
    consumed_cargo_stacks: list = field(default_factory=list)
    experience_per_progress: list = field(default_factory=list)
    discovery_triggers: list = field(default_factory=list)
    required_knowledges: list = field(default_factory=list)
    required_claim_tech_ids: list = field(default_factory=list)
    required_biomes: list = field(default_factory=list)
    full_discovery_score: int = 0
    tool_mesh_index: int = 0
    resource_description_id: int = 0
    required_paving_tier: int = 0
    actions_required: int = 0
    recipe_performance_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ResourcePlacementRecipeDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            time_requirement=(raw.get('time_requirement') if isinstance(raw, dict) else raw[2]),
            stamina_requirement=(raw.get('stamina_requirement') if isinstance(raw, dict) else raw[3]),
            consumed_resource=(raw.get('consumed_resource') if isinstance(raw, dict) else raw[4]),
            required_interior_tier=(raw.get('required_interior_tier') if isinstance(raw, dict) else raw[5]),
            level_requirements=[LevelRequirement.from_row(_item) for _item in ((raw.get('level_requirements') if isinstance(raw, dict) else raw[6]) or [])],
            tool_requirements=[ToolRequirement.from_row(_item) for _item in ((raw.get('tool_requirements') if isinstance(raw, dict) else raw[7]) or [])],
            consumed_item_stacks=[InputItemStack.from_row(_item) for _item in ((raw.get('consumed_item_stacks') if isinstance(raw, dict) else raw[8]) or [])],
            consumed_cargo_stacks=[InputItemStack.from_row(_item) for _item in ((raw.get('consumed_cargo_stacks') if isinstance(raw, dict) else raw[9]) or [])],
            experience_per_progress=[ExperienceStackF32.from_row(_item) for _item in ((raw.get('experience_per_progress') if isinstance(raw, dict) else raw[10]) or [])],
            discovery_triggers=[_item for _item in ((raw.get('discovery_triggers') if isinstance(raw, dict) else raw[11]) or [])],
            required_knowledges=[_item for _item in ((raw.get('required_knowledges') if isinstance(raw, dict) else raw[12]) or [])],
            required_claim_tech_ids=[_item for _item in ((raw.get('required_claim_tech_ids') if isinstance(raw, dict) else raw[13]) or [])],
            required_biomes=[Biome.from_row(_item) for _item in ((raw.get('required_biomes') if isinstance(raw, dict) else raw[14]) or [])],
            full_discovery_score=(raw.get('full_discovery_score') if isinstance(raw, dict) else raw[15]),
            tool_mesh_index=(raw.get('tool_mesh_index') if isinstance(raw, dict) else raw[16]),
            resource_description_id=(raw.get('resource_description_id') if isinstance(raw, dict) else raw[17]),
            required_paving_tier=(raw.get('required_paving_tier') if isinstance(raw, dict) else raw[18]),
            actions_required=(raw.get('actions_required') if isinstance(raw, dict) else raw[19]),
            recipe_performance_id=(raw.get('recipe_performance_id') if isinstance(raw, dict) else raw[20])
        )
