# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .small_hex_tile_message import SmallHexTileMessage



@dataclass
class ResourceSpawnTimer:
    scheduled_id: int = 0
    scheduled_at: object = 0
    entity_id: object | None = None
    resource_id: int = 0
    coordinates: SmallHexTileMessage = 0
    direction_index: int = 0
    health: int = 0
    check_buildings: bool = False
    check_resources: bool = False

    @classmethod
    def from_row(cls, raw) -> 'ResourceSpawnTimer':
        if raw is None:
            return cls()
        return cls(
            scheduled_id=(raw.get('scheduled_id') if isinstance(raw, dict) else raw[0]),
            scheduled_at=(raw.get('scheduled_at') if isinstance(raw, dict) else raw[1]),
            entity_id=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (_v[1]))((raw.get('entity_id') if isinstance(raw, dict) else raw[2])),
            resource_id=(raw.get('resource_id') if isinstance(raw, dict) else raw[3]),
            coordinates=SmallHexTileMessage.from_row((raw.get('coordinates') if isinstance(raw, dict) else raw[4])),
            direction_index=(raw.get('direction_index') if isinstance(raw, dict) else raw[5]),
            health=(raw.get('health') if isinstance(raw, dict) else raw[6]),
            check_buildings=(raw.get('check_buildings') if isinstance(raw, dict) else raw[7]),
            check_resources=(raw.get('check_resources') if isinstance(raw, dict) else raw[8])
        )
