# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ResourceDestroyBuildingOutcome:
    probability: float = 0.0
    building_id: int = 0
    radius_min: int = 0
    radius_max: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ResourceDestroyBuildingOutcome':
        if raw is None:
            return cls()
        return cls(
            probability=(raw.get('probability') if isinstance(raw, dict) else raw[0]),
            building_id=(raw.get('building_id') if isinstance(raw, dict) else raw[1]),
            radius_min=(raw.get('radius_min') if isinstance(raw, dict) else raw[2]),
            radius_max=(raw.get('radius_max') if isinstance(raw, dict) else raw[3])
        )
