# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ResourceState:
    entity_id: int = 0
    resource_id: int = 0
    direction_index: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ResourceState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            resource_id=(raw.get('resource_id') if isinstance(raw, dict) else raw[1]),
            direction_index=(raw.get('direction_index') if isinstance(raw, dict) else raw[2])
        )
