# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ResourceInfo:
    resource_id: int = 0
    world_target: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ResourceInfo':
        if raw is None:
            return cls()
        return cls(
            resource_id=(raw.get('resource_id') if isinstance(raw, dict) else raw[0]),
            world_target=(raw.get('world_target') if isinstance(raw, dict) else raw[1])
        )
