# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .common_rng import CommonRng
from .resource_clump_info import ResourceClumpInfo
from .resource_info import ResourceInfo



@dataclass
class ResourcesLog:
    version: int = 0
    world_width: int = 0
    world_height: int = 0
    resource_clumps: list = field(default_factory=list)
    resources: list = field(default_factory=list)
    random: CommonRng = 0

    @classmethod
    def from_row(cls, raw) -> 'ResourcesLog':
        if raw is None:
            return cls()
        return cls(
            version=(raw.get('version') if isinstance(raw, dict) else raw[0]),
            world_width=(raw.get('world_width') if isinstance(raw, dict) else raw[1]),
            world_height=(raw.get('world_height') if isinstance(raw, dict) else raw[2]),
            resource_clumps=[ResourceClumpInfo.from_row(_item) for _item in ((raw.get('resource_clumps') if isinstance(raw, dict) else raw[3]) or [])],
            resources=[ResourceInfo.from_row(_item) for _item in ((raw.get('resources') if isinstance(raw, dict) else raw[4]) or [])],
            random=CommonRng.from_row((raw.get('random') if isinstance(raw, dict) else raw[5]))
        )
