# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .small_hex_tile_message import SmallHexTileMessage



@dataclass
class ResourceDepletedEvent:
    player_entity_id: int = 0
    resource_entity_id: int = 0
    location: SmallHexTileMessage = 0
    show_time_left: bool = False

    @classmethod
    def from_row(cls, raw) -> 'ResourceDepletedEvent':
        if raw is None:
            return cls()
        return cls(
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[0]),
            resource_entity_id=(raw.get('resource_entity_id') if isinstance(raw, dict) else raw[1]),
            location=SmallHexTileMessage.from_row((raw.get('location') if isinstance(raw, dict) else raw[2])),
            show_time_left=(raw.get('show_time_left') if isinstance(raw, dict) else raw[3])
        )
