# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ResourceGrowthRecipeDesc:
    id: int = 0
    resource_id: int = 0
    time: list = field(default_factory=list)
    grown_resource_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ResourceGrowthRecipeDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            resource_id=(raw.get('resource_id') if isinstance(raw, dict) else raw[1]),
            time=[_item for _item in ((raw.get('time') if isinstance(raw, dict) else raw[2]) or [])],
            grown_resource_id=(raw.get('grown_resource_id') if isinstance(raw, dict) else raw[3])
        )
