# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .spawn_info import SpawnInfo



@dataclass
class ResourceClumpInfo:
    clump_id: int = 0
    spawn_info: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'ResourceClumpInfo':
        if raw is None:
            return cls()
        return cls(
            clump_id=(raw.get('clump_id') if isinstance(raw, dict) else raw[0]),
            spawn_info=[SpawnInfo.from_row(_item) for _item in ((raw.get('spawn_info') if isinstance(raw, dict) else raw[1]) or [])]
        )
