# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .small_hex_tile_message import SmallHexTileMessage



@dataclass
class RespawnResourceInChunkTimer:
    scheduled_id: int = 0
    scheduled_at: object = 0
    chunk_index: int = 0
    resource_clump_id: int = 0
    coord: int = 0

    @classmethod
    def from_row(cls, raw) -> 'RespawnResourceInChunkTimer':
        if raw is None:
            return cls()
        return cls(
            scheduled_id=(raw.get('scheduled_id') if isinstance(raw, dict) else raw[0]),
            scheduled_at=(raw.get('scheduled_at') if isinstance(raw, dict) else raw[1]),
            chunk_index=(raw.get('chunk_index') if isinstance(raw, dict) else raw[2]),
            resource_clump_id=(raw.get('resource_clump_id') if isinstance(raw, dict) else raw[3]),
            coord=(raw.get('coord') if isinstance(raw, dict) else raw[4])
        )
