# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ServerIdentity:
    version: int = 0
    identity: str = 0

    @classmethod
    def from_row(cls, raw) -> 'ServerIdentity':
        if raw is None:
            return cls()
        return cls(
            version=(raw.get('version') if isinstance(raw, dict) else raw[0]),
            identity=((raw.get('identity') if isinstance(raw, dict) else raw[1])['__identity__'] if isinstance((raw.get('identity') if isinstance(raw, dict) else raw[1]), dict) else (raw.get('identity') if isinstance(raw, dict) else raw[1]))
        )
