# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .server_teleport_reason import ServerTeleportReason



@dataclass
class ServerTeleportEvent:
    player_entity_id: int = 0
    reason: ServerTeleportReason = 0

    @classmethod
    def from_row(cls, raw) -> 'ServerTeleportEvent':
        if raw is None:
            return cls()
        return cls(
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[0]),
            reason=ServerTeleportReason.from_row((raw.get('reason') if isinstance(raw, dict) else raw[1]))
        )
