# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class ServerTeleportReason(IntEnum):
    RUINCOLLAPSE = 0
    INTERIORDECONSTRUCTED = 1
    PLAYERDIED = 2
    TELEPORTITEM = 3
    PLAYERHOUSINGCHANGEDLOCATION = 4
    PLAYERHOUSINGUNDERMAINTENANCE = 5
    PLAYERHOUSINGDECONSTRUCTED = 6


    @classmethod
    def from_row(cls, raw) -> 'ServerTeleportReason':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for RuinCollapse
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse ServerTeleportReason from {raw!r}')
