# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .resource_clump_info import ResourceClumpInfo



@dataclass
class SingleResourceClumpInfo:
    clump_id: int = 0
    resource_clump_info: ResourceClumpInfo = 0

    @classmethod
    def from_row(cls, raw) -> 'SingleResourceClumpInfo':
        if raw is None:
            return cls()
        return cls(
            clump_id=(raw.get('clump_id') if isinstance(raw, dict) else raw[0]),
            resource_clump_info=ResourceClumpInfo.from_row((raw.get('resource_clump_info') if isinstance(raw, dict) else raw[1]))
        )
