# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class SkillLevelKnowledgeDesc:
    id: int = 0
    skill_id: int = 0
    level: int = 0
    secondary_knowledge_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'SkillLevelKnowledgeDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            skill_id=(raw.get('skill_id') if isinstance(raw, dict) else raw[1]),
            level=(raw.get('level') if isinstance(raw, dict) else raw[2]),
            secondary_knowledge_id=(raw.get('secondary_knowledge_id') if isinstance(raw, dict) else raw[3])
        )
