# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class SystemChatBroadcastTimer:
    scheduled_id: int = 0
    scheduled_at: object = 0
    message: str = ''

    @classmethod
    def from_row(cls, raw) -> 'SystemChatBroadcastTimer':
        if raw is None:
            return cls()
        return cls(
            scheduled_id=(raw.get('scheduled_id') if isinstance(raw, dict) else raw[0]),
            scheduled_at=(raw.get('scheduled_at') if isinstance(raw, dict) else raw[1]),
            message=(raw.get('message') if isinstance(raw, dict) else raw[2])
        )
