# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class TargetUpdateRequest:
    owner_entity_id: int = 0
    target_entity_id: int = 0
    generate_aggro: bool = False

    @classmethod
    def from_row(cls, raw) -> 'TargetUpdateRequest':
        if raw is None:
            return cls()
        return cls(
            owner_entity_id=(raw.get('owner_entity_id') if isinstance(raw, dict) else raw[0]),
            target_entity_id=(raw.get('target_entity_id') if isinstance(raw, dict) else raw[1]),
            generate_aggro=(raw.get('generate_aggro') if isinstance(raw, dict) else raw[2])
        )
