# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class TeleportationEnergyState:
    entity_id: int = 0
    energy: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'TeleportationEnergyState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            energy=(raw.get('energy') if isinstance(raw, dict) else raw[1])
        )
