# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .offset_coordinates_float import OffsetCoordinatesFloat
from .server_teleport_reason import ServerTeleportReason



@dataclass
class TeleportPlayerTimer:
    scheduled_id: int = 0
    scheduled_at: object = 0
    location: int = 0
    player_entity_id: int = 0
    reason: int = 0

    @classmethod
    def from_row(cls, raw) -> 'TeleportPlayerTimer':
        if raw is None:
            return cls()
        return cls(
            scheduled_id=(raw.get('scheduled_id') if isinstance(raw, dict) else raw[0]),
            scheduled_at=(raw.get('scheduled_at') if isinstance(raw, dict) else raw[1]),
            location=(raw.get('location') if isinstance(raw, dict) else raw[2]),
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[3]),
            reason=(raw.get('reason') if isinstance(raw, dict) else raw[4])
        )
