# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class TerrainCell:
    x: int = 0
    z: int = 0
    dimension: int = 0
    elevation: int = 0
    water_level: int = 0
    biomes: int = 0
    biome_density: int = 0
    original_elevation: int = 0
    zoning_type: int = 0
    water_body_type: int = 0

    @classmethod
    def from_row(cls, raw) -> 'TerrainCell':
        if raw is None:
            return cls()
        return cls(
            x=(raw.get('x') if isinstance(raw, dict) else raw[0]),
            z=(raw.get('z') if isinstance(raw, dict) else raw[1]),
            dimension=(raw.get('dimension') if isinstance(raw, dict) else raw[2]),
            elevation=(raw.get('elevation') if isinstance(raw, dict) else raw[3]),
            water_level=(raw.get('water_level') if isinstance(raw, dict) else raw[4]),
            biomes=(raw.get('biomes') if isinstance(raw, dict) else raw[5]),
            biome_density=(raw.get('biome_density') if isinstance(raw, dict) else raw[6]),
            original_elevation=(raw.get('original_elevation') if isinstance(raw, dict) else raw[7]),
            zoning_type=(raw.get('zoning_type') if isinstance(raw, dict) else raw[8]),
            water_body_type=(raw.get('water_body_type') if isinstance(raw, dict) else raw[9])
        )
