# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .tool_requirement import ToolRequirement



@dataclass
class TerraformRecipeDesc:
    difference: int = 0
    actions_count: int = 0
    tool_requirement: ToolRequirement | None = None
    stamina_per_action: float = 0.0
    time_per_action: float = 0.0
    tool_mesh_index: int = 0
    recipe_performance_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'TerraformRecipeDesc':
        if raw is None:
            return cls()
        return cls(
            difference=(raw.get('difference') if isinstance(raw, dict) else raw[0]),
            actions_count=(raw.get('actions_count') if isinstance(raw, dict) else raw[1]),
            tool_requirement=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (ToolRequirement.from_row(_v[1])))((raw.get('tool_requirement') if isinstance(raw, dict) else raw[2])),
            stamina_per_action=(raw.get('stamina_per_action') if isinstance(raw, dict) else raw[3]),
            time_per_action=(raw.get('time_per_action') if isinstance(raw, dict) else raw[4]),
            tool_mesh_index=(raw.get('tool_mesh_index') if isinstance(raw, dict) else raw[5]),
            recipe_performance_id=(raw.get('recipe_performance_id') if isinstance(raw, dict) else raw[6])
        )
