# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ToolTypeDesc:
    id: int = 0
    name: str = ''
    skill_id: int = 0

    @classmethod
    def from_row(cls, raw) -> 'ToolTypeDesc':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            name=(raw.get('name') if isinstance(raw, dict) else raw[1]),
            skill_id=(raw.get('skill_id') if isinstance(raw, dict) else raw[2])
        )
