# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class ToolbarState:
    entity_id: int = 0
    owner_entity_id: int = 0
    index: int = 0
    actions: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'ToolbarState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            owner_entity_id=(raw.get('owner_entity_id') if isinstance(raw, dict) else raw[1]),
            index=(raw.get('index') if isinstance(raw, dict) else raw[2]),
            actions=[_item for _item in ((raw.get('actions') if isinstance(raw, dict) else raw[3]) or [])]
        )
