# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .trade_pocket import TradePocket
from .trade_session_status import TradeSessionStatus



@dataclass
class TradeSessionState:
    entity_id: int = 0
    status: TradeSessionStatus = 0
    initiator_entity_id: int = 0
    acceptor_entity_id: int = 0
    initiator_offer: list = field(default_factory=list)
    acceptor_offer: list = field(default_factory=list)
    updated_at: object = 0
    resolution_message: str = ''

    @classmethod
    def from_row(cls, raw) -> 'TradeSessionState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            status=TradeSessionStatus.from_row((raw.get('status') if isinstance(raw, dict) else raw[1])),
            initiator_entity_id=(raw.get('initiator_entity_id') if isinstance(raw, dict) else raw[2]),
            acceptor_entity_id=(raw.get('acceptor_entity_id') if isinstance(raw, dict) else raw[3]),
            initiator_offer=[TradePocket.from_row(_item) for _item in ((raw.get('initiator_offer') if isinstance(raw, dict) else raw[4]) or [])],
            acceptor_offer=[TradePocket.from_row(_item) for _item in ((raw.get('acceptor_offer') if isinstance(raw, dict) else raw[5]) or [])],
            updated_at=(raw.get('updated_at') if isinstance(raw, dict) else raw[6]),
            resolution_message=(raw.get('resolution_message') if isinstance(raw, dict) else raw[7])
        )
