# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .npc_type import NpcType



@dataclass
class TravelerWeeklyTaskCredits:
    traveler_type: NpcType = 0
    weekly_task_credits: int = 0

    @classmethod
    def from_row(cls, raw) -> 'TravelerWeeklyTaskCredits':
        if raw is None:
            return cls()
        return cls(
            traveler_type=NpcType.from_row((raw.get('traveler_type') if isinstance(raw, dict) else raw[0])),
            weekly_task_credits=(raw.get('weekly_task_credits') if isinstance(raw, dict) else raw[1])
        )
