# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class TravelerTaskState:
    entity_id: int = 0
    player_entity_id: int = 0
    traveler_id: int = 0
    task_id: int = 0
    completed: bool = False

    @classmethod
    def from_row(cls, raw) -> 'TravelerTaskState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            player_entity_id=(raw.get('player_entity_id') if isinstance(raw, dict) else raw[1]),
            traveler_id=(raw.get('traveler_id') if isinstance(raw, dict) else raw[2]),
            task_id=(raw.get('task_id') if isinstance(raw, dict) else raw[3]),
            completed=(raw.get('completed') if isinstance(raw, dict) else raw[4])
        )
