# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class TravelerTaskKnowledgeRequirementDesc:
    traveler_task_id: int = 0
    required_knowledges: list = field(default_factory=list)
    blocking_knowledges: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'TravelerTaskKnowledgeRequirementDesc':
        if raw is None:
            return cls()
        return cls(
            traveler_task_id=(raw.get('traveler_task_id') if isinstance(raw, dict) else raw[0]),
            required_knowledges=[_item for _item in ((raw.get('required_knowledges') if isinstance(raw, dict) else raw[1]) or [])],
            blocking_knowledges=[_item for _item in ((raw.get('blocking_knowledges') if isinstance(raw, dict) else raw[2]) or [])]
        )
