# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .float_hex_tile_message import FloatHexTileMessage



@dataclass
class UserPreviousRegionState:
    identity: str = 0
    previous_region_location: FloatHexTileMessage = 0
    with_vehicle: bool = False
    allow_cancel: bool = False
    teleport_energy_cost: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'UserPreviousRegionState':
        if raw is None:
            return cls()
        return cls(
            identity=((raw.get('identity') if isinstance(raw, dict) else raw[0])['__identity__'] if isinstance((raw.get('identity') if isinstance(raw, dict) else raw[0]), dict) else ((raw.get('identity') if isinstance(raw, dict) else raw[0])[0] if isinstance((raw.get('identity') if isinstance(raw, dict) else raw[0]), list) else (raw.get('identity') if isinstance(raw, dict) else raw[0]))),
            previous_region_location=FloatHexTileMessage.from_row((raw.get('previous_region_location') if isinstance(raw, dict) else raw[1])),
            with_vehicle=(raw.get('with_vehicle') if isinstance(raw, dict) else raw[2]),
            allow_cancel=(raw.get('allow_cancel') if isinstance(raw, dict) else raw[3]),
            teleport_energy_cost=(raw.get('teleport_energy_cost') if isinstance(raw, dict) else raw[4])
        )
