# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .vault_collectible import VaultCollectible



@dataclass
class VaultState:
    entity_id: int = 0
    collectibles: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'VaultState':
        if raw is None:
            return cls()
        return cls(
            entity_id=(raw.get('entity_id') if isinstance(raw, dict) else raw[0]),
            collectibles=[VaultCollectible.from_row(_item) for _item in ((raw.get('collectibles') if isinstance(raw, dict) else raw[1]) or [])]
        )
