# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from enum import IntEnum


class WorldGenNoiseBasedElevationLayerBlendingMode(IntEnum):
    ADD = 0
    OVERRIDE = 1


    @classmethod
    def from_row(cls, raw) -> 'WorldGenNoiseBasedElevationLayerBlendingMode':
        """
        Raw wire format: [variant_index, payload]
        e.g. [0, []] for Add
        """
        if isinstance(raw, list):
            return cls(raw[0])
        if isinstance(raw, int):
            return cls(raw)
        raise ValueError(f'Cannot parse WorldGenNoiseBasedElevationLayerBlendingMode from {raw!r}')
