# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .world_gen_animation_curve import WorldGenAnimationCurve
from .world_gen_river_pathfinding_costs import WorldGenRiverPathfindingCosts



@dataclass
class WorldGenRiverGenerationSettings:
    radius: int = 0
    depth_curve: WorldGenAnimationCurve = 0
    erosion: float = 0.0
    min_lake_circumference: int = 0
    pathfinding_node_limit: int = 0
    pathfinding_costs: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'WorldGenRiverGenerationSettings':
        if raw is None:
            return cls()
        return cls(
            radius=(raw.get('radius') if isinstance(raw, dict) else raw[0]),
            depth_curve=WorldGenAnimationCurve.from_row((raw.get('depth_curve') if isinstance(raw, dict) else raw[1])),
            erosion=(raw.get('erosion') if isinstance(raw, dict) else raw[2]),
            min_lake_circumference=(raw.get('min_lake_circumference') if isinstance(raw, dict) else raw[3]),
            pathfinding_node_limit=(raw.get('pathfinding_node_limit') if isinstance(raw, dict) else raw[4]),
            pathfinding_costs=[WorldGenRiverPathfindingCosts.from_row(_item) for _item in ((raw.get('pathfinding_costs') if isinstance(raw, dict) else raw[5]) or [])]
        )
