# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .world_gen_noise_specs import WorldGenNoiseSpecs
from .world_gen_rect_int import WorldGenRectInt



@dataclass
class WorldGenLandShapeDefinition:
    noise_specs: WorldGenNoiseSpecs = 0
    bounds: WorldGenRectInt = 0
    land_threshold: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'WorldGenLandShapeDefinition':
        if raw is None:
            return cls()
        return cls(
            noise_specs=WorldGenNoiseSpecs.from_row((raw.get('noise_specs') if isinstance(raw, dict) else raw[0])),
            bounds=WorldGenRectInt.from_row((raw.get('bounds') if isinstance(raw, dict) else raw[1])),
            land_threshold=(raw.get('land_threshold') if isinstance(raw, dict) else raw[2])
        )
