# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .world_gen_mountain import WorldGenMountain



@dataclass
class WorldGenMountainsMapDefinition:
    mountains: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'WorldGenMountainsMapDefinition':
        if raw is None:
            return cls()
        return cls(
            mountains=[WorldGenMountain.from_row(_item) for _item in ((raw.get('mountains') if isinstance(raw, dict) else raw[0]) or [])]
        )
