# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class WorldGenBuildingDetails:
    index: int = 0
    id: int = 0
    direction: int = 0

    @classmethod
    def from_row(cls, raw) -> 'WorldGenBuildingDetails':
        if raw is None:
            return cls()
        return cls(
            index=(raw.get('index') if isinstance(raw, dict) else raw[0]),
            id=(raw.get('id') if isinstance(raw, dict) else raw[1]),
            direction=(raw.get('direction') if isinstance(raw, dict) else raw[2])
        )
