# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .world_gen_building_details import WorldGenBuildingDetails



@dataclass
class WorldGenBuildingsMapDefinition:
    buildings: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'WorldGenBuildingsMapDefinition':
        if raw is None:
            return cls()
        return cls(
            buildings=[WorldGenBuildingDetails.from_row(_item) for _item in ((raw.get('buildings') if isinstance(raw, dict) else raw[0]) or [])]
        )
