# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class WorldGenNoiseSpecs:
    seed: int = 0
    scale: float = 0.0
    octaves: int = 0
    persistance: float = 0.0
    lacunarity: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'WorldGenNoiseSpecs':
        if raw is None:
            return cls()
        return cls(
            seed=(raw.get('seed') if isinstance(raw, dict) else raw[0]),
            scale=(raw.get('scale') if isinstance(raw, dict) else raw[1]),
            octaves=(raw.get('octaves') if isinstance(raw, dict) else raw[2]),
            persistance=(raw.get('persistance') if isinstance(raw, dict) else raw[3]),
            lacunarity=(raw.get('lacunarity') if isinstance(raw, dict) else raw[4])
        )
