# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .world_gen_noise_specs import WorldGenNoiseSpecs
from .world_gen_vector2 import WorldGenVector2



@dataclass
class WorldGenResourceBiome:
    biome_definition_index: int = 0
    chance: float = 0.0
    noise_threshold: WorldGenVector2 = 0
    noise_specs: WorldGenNoiseSpecs = 0

    @classmethod
    def from_row(cls, raw) -> 'WorldGenResourceBiome':
        if raw is None:
            return cls()
        return cls(
            biome_definition_index=(raw.get('biome_definition_index') if isinstance(raw, dict) else raw[0]),
            chance=(raw.get('chance') if isinstance(raw, dict) else raw[1]),
            noise_threshold=WorldGenVector2.from_row((raw.get('noise_threshold') if isinstance(raw, dict) else raw[2])),
            noise_specs=WorldGenNoiseSpecs.from_row((raw.get('noise_specs') if isinstance(raw, dict) else raw[3]))
        )
