# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class WorldGenRectInt:
    x: int = 0
    y: int = 0
    width: int = 0
    height: int = 0

    @classmethod
    def from_row(cls, raw) -> 'WorldGenRectInt':
        if raw is None:
            return cls()
        return cls(
            x=(raw.get('x') if isinstance(raw, dict) else raw[0]),
            y=(raw.get('y') if isinstance(raw, dict) else raw[1]),
            width=(raw.get('width') if isinstance(raw, dict) else raw[2]),
            height=(raw.get('height') if isinstance(raw, dict) else raw[3])
        )
