# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .world_gen_vector2_int import WorldGenVector2Int



@dataclass
class WorldGenRiverPathfindingCosts:
    elevation_difference_range: WorldGenVector2Int = 0
    pathfinding_costs: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'WorldGenRiverPathfindingCosts':
        if raw is None:
            return cls()
        return cls(
            elevation_difference_range=WorldGenVector2Int.from_row((raw.get('elevation_difference_range') if isinstance(raw, dict) else raw[0])),
            pathfinding_costs=(raw.get('pathfinding_costs') if isinstance(raw, dict) else raw[1])
        )
