# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .world_gen_animation_curve import WorldGenAnimationCurve
from .world_gen_noise_based_elevation_layer import WorldGenNoiseBasedElevationLayer
from .world_gen_noise_specs import WorldGenNoiseSpecs
from .world_gen_river_generation_settings import WorldGenRiverGenerationSettings



@dataclass
class WorldGenBiomeDefinition:
    distance_to_sea_curve: WorldGenAnimationCurve = 0
    distance_to_biomes_curve: WorldGenAnimationCurve = 0
    transition_length: int = 0
    noise_sea_multiplier: WorldGenAnimationCurve = 0
    noise_based_elevation_layers: list = field(default_factory=list)
    max_lake_depth: int = 0
    terracing: bool = False
    grass_density: int = 0
    lake_noise_specs: WorldGenNoiseSpecs = 0
    lake_noise_threshold: float = 0.0
    lake_depth_multiplier: int = 0
    lake_depth_smoothing: float = 0.0
    lake_sea_barriers: bool = False
    river_generation_settings: WorldGenRiverGenerationSettings | None = None

    @classmethod
    def from_row(cls, raw) -> 'WorldGenBiomeDefinition':
        if raw is None:
            return cls()
        return cls(
            distance_to_sea_curve=WorldGenAnimationCurve.from_row((raw.get('distance_to_sea_curve') if isinstance(raw, dict) else raw[0])),
            distance_to_biomes_curve=WorldGenAnimationCurve.from_row((raw.get('distance_to_biomes_curve') if isinstance(raw, dict) else raw[1])),
            transition_length=(raw.get('transition_length') if isinstance(raw, dict) else raw[2]),
            noise_sea_multiplier=WorldGenAnimationCurve.from_row((raw.get('noise_sea_multiplier') if isinstance(raw, dict) else raw[3])),
            noise_based_elevation_layers=[WorldGenNoiseBasedElevationLayer.from_row(_item) for _item in ((raw.get('noise_based_elevation_layers') if isinstance(raw, dict) else raw[4]) or [])],
            max_lake_depth=(raw.get('max_lake_depth') if isinstance(raw, dict) else raw[5]),
            terracing=(raw.get('terracing') if isinstance(raw, dict) else raw[6]),
            grass_density=(raw.get('grass_density') if isinstance(raw, dict) else raw[7]),
            lake_noise_specs=WorldGenNoiseSpecs.from_row((raw.get('lake_noise_specs') if isinstance(raw, dict) else raw[8])),
            lake_noise_threshold=(raw.get('lake_noise_threshold') if isinstance(raw, dict) else raw[9]),
            lake_depth_multiplier=(raw.get('lake_depth_multiplier') if isinstance(raw, dict) else raw[10]),
            lake_depth_smoothing=(raw.get('lake_depth_smoothing') if isinstance(raw, dict) else raw[11]),
            lake_sea_barriers=(raw.get('lake_sea_barriers') if isinstance(raw, dict) else raw[12]),
            river_generation_settings=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (WorldGenRiverGenerationSettings.from_row(_v[1])))((raw.get('river_generation_settings') if isinstance(raw, dict) else raw[13]))
        )
