# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .world_gen_resource_biome import WorldGenResourceBiome
from .world_gen_resource_details import WorldGenResourceDetails



@dataclass
class WorldGenResourceDefinition:
    resource_details: WorldGenResourceDetails = 0
    biomes: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'WorldGenResourceDefinition':
        if raw is None:
            return cls()
        return cls(
            resource_details=WorldGenResourceDetails.from_row((raw.get('resource_details') if isinstance(raw, dict) else raw[0])),
            biomes=[WorldGenResourceBiome.from_row(_item) for _item in ((raw.get('biomes') if isinstance(raw, dict) else raw[1]) or [])]
        )
