# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class WorldGenAnimationCurveKeyframe:
    time: float = 0.0
    value: float = 0.0
    in_tangent: float = 0.0
    out_tangent: float = 0.0

    @classmethod
    def from_row(cls, raw) -> 'WorldGenAnimationCurveKeyframe':
        if raw is None:
            return cls()
        return cls(
            time=(raw.get('time') if isinstance(raw, dict) else raw[0]),
            value=(raw.get('value') if isinstance(raw, dict) else raw[1]),
            in_tangent=(raw.get('in_tangent') if isinstance(raw, dict) else raw[2]),
            out_tangent=(raw.get('out_tangent') if isinstance(raw, dict) else raw[3])
        )
