# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .world_gen_resource_definition import WorldGenResourceDefinition



@dataclass
class WorldGenResourcesMapDefinition:
    seed: int = 0
    resources: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'WorldGenResourcesMapDefinition':
        if raw is None:
            return cls()
        return cls(
            seed=(raw.get('seed') if isinstance(raw, dict) else raw[0]),
            resources=[WorldGenResourceDefinition.from_row(_item) for _item in ((raw.get('resources') if isinstance(raw, dict) else raw[1]) or [])]
        )
