# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .resource_state import ResourceState



@dataclass
class WorldGenGeneratedResourceDeposit:
    x: int = 0
    z: int = 0
    deposit: ResourceState | None = None
    dimension: int = 0

    @classmethod
    def from_row(cls, raw) -> 'WorldGenGeneratedResourceDeposit':
        if raw is None:
            return cls()
        return cls(
            x=(raw.get('x') if isinstance(raw, dict) else raw[0]),
            z=(raw.get('z') if isinstance(raw, dict) else raw[1]),
            deposit=(lambda _v: None if (_v is None or (isinstance(_v, list) and _v[0] == 1)) else (ResourceState.from_row(_v[1])))((raw.get('deposit') if isinstance(raw, dict) else raw[2])),
            dimension=(raw.get('dimension') if isinstance(raw, dict) else raw[3])
        )
