# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .world_gen_land_shape_definition import WorldGenLandShapeDefinition



@dataclass
class WorldGenWorldMapDefinition:
    debug_step: int = 0
    shapes: list = field(default_factory=list)

    @classmethod
    def from_row(cls, raw) -> 'WorldGenWorldMapDefinition':
        if raw is None:
            return cls()
        return cls(
            debug_step=(raw.get('debug_step') if isinstance(raw, dict) else raw[0]),
            shapes=[WorldGenLandShapeDefinition.from_row(_item) for _item in ((raw.get('shapes') if isinstance(raw, dict) else raw[1]) or [])]
        )
