# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .world_gen_animation_curve import WorldGenAnimationCurve
from .world_gen_vector2 import WorldGenVector2



@dataclass
class WorldGenMountain:
    center: WorldGenVector2 = 0
    radius: float = 0.0
    height: int = 0
    peak_offset: WorldGenVector2 = 0
    shape: WorldGenAnimationCurve = 0

    @classmethod
    def from_row(cls, raw) -> 'WorldGenMountain':
        if raw is None:
            return cls()
        return cls(
            center=WorldGenVector2.from_row((raw.get('center') if isinstance(raw, dict) else raw[0])),
            radius=(raw.get('radius') if isinstance(raw, dict) else raw[1]),
            height=(raw.get('height') if isinstance(raw, dict) else raw[2]),
            peak_offset=WorldGenVector2.from_row((raw.get('peak_offset') if isinstance(raw, dict) else raw[3])),
            shape=WorldGenAnimationCurve.from_row((raw.get('shape') if isinstance(raw, dict) else raw[4]))
        )
