# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

from .world_gen_animation_curve import WorldGenAnimationCurve
from .world_gen_biomes_map_definition import WorldGenBiomesMapDefinition
from .world_gen_buildings_map_definition import WorldGenBuildingsMapDefinition
from .world_gen_mountains_map_definition import WorldGenMountainsMapDefinition
from .world_gen_resources_map_definition import WorldGenResourcesMapDefinition
from .world_gen_vector2_int import WorldGenVector2Int
from .world_gen_world_map_definition import WorldGenWorldMapDefinition



@dataclass
class WorldGenWorldDefinition:
    size: WorldGenVector2Int = 0
    land_curve: WorldGenAnimationCurve = 0
    noise_influence: float = 0.0
    sea_level: int = 0
    world_map: WorldGenWorldMapDefinition = 0
    biomes_map: WorldGenBiomesMapDefinition = 0
    mountains_map: WorldGenMountainsMapDefinition = 0
    buildings_map: WorldGenBuildingsMapDefinition = 0
    resources_map: WorldGenResourcesMapDefinition = 0

    @classmethod
    def from_row(cls, raw) -> 'WorldGenWorldDefinition':
        if raw is None:
            return cls()
        return cls(
            size=WorldGenVector2Int.from_row((raw.get('size') if isinstance(raw, dict) else raw[0])),
            land_curve=WorldGenAnimationCurve.from_row((raw.get('land_curve') if isinstance(raw, dict) else raw[1])),
            noise_influence=(raw.get('noise_influence') if isinstance(raw, dict) else raw[2]),
            sea_level=(raw.get('sea_level') if isinstance(raw, dict) else raw[3]),
            world_map=WorldGenWorldMapDefinition.from_row((raw.get('world_map') if isinstance(raw, dict) else raw[4])),
            biomes_map=WorldGenBiomesMapDefinition.from_row((raw.get('biomes_map') if isinstance(raw, dict) else raw[5])),
            mountains_map=WorldGenMountainsMapDefinition.from_row((raw.get('mountains_map') if isinstance(raw, dict) else raw[6])),
            buildings_map=WorldGenBuildingsMapDefinition.from_row((raw.get('buildings_map') if isinstance(raw, dict) else raw[7])),
            resources_map=WorldGenResourcesMapDefinition.from_row((raw.get('resources_map') if isinstance(raw, dict) else raw[8]))
        )
