# AUTO-GENERATED by generate_bindings.py — DO NOT EDIT MANUALLY.
# Re-run generate_bindings.py to update from the latest bindings graph.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional



@dataclass
class WorldRegionNameState:
    id: int = 0
    player_facing_name: str = ''
    module_name_prefix: str = ''

    @classmethod
    def from_row(cls, raw) -> 'WorldRegionNameState':
        if raw is None:
            return cls()
        return cls(
            id=(raw.get('id') if isinstance(raw, dict) else raw[0]),
            player_facing_name=(raw.get('player_facing_name') if isinstance(raw, dict) else raw[1]),
            module_name_prefix=(raw.get('module_name_prefix') if isinstance(raw, dict) else raw[2])
        )
